# generated by clj2nix-1.1.0-rc
{ fetchMavenArtifact, fetchgit, lib }:

let repos = [
        "https://repo1.maven.org/maven2/"
        "https://repo.clojars.org/" ];

  in rec {
      makePaths = {extraClasspaths ? []}:
        if (builtins.typeOf extraClasspaths != "list")
        then builtins.throw "extraClasspaths must be of type 'list'!"
        else (lib.concatMap (dep:
          builtins.map (path:
            if builtins.isString path then
              path
            else if builtins.hasAttr "jar" path then
              path.jar
            else if builtins.hasAttr "outPath" path then
              path.outPath
            else
              path
            )
          dep.paths)
        packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}:
       if (builtins.typeOf extraClasspaths != "list")
       then builtins.throw "extraClasspaths must be of type 'list'!"
       else builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});
      packageSources = builtins.map (dep: dep.src) packages;
      packages = [
  rec {
    name = "transit-java/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-java";
      groupId = "com.cognitect";
      sha512 = "660d4f034af67793ec53f00c661e57dd94817a3d1ab978163fe6289e06f16fe3f8431496c8e4eff1b9729cc2c47e906b6afb933605034fc2b64829c33fb47d99";
      version = "1.0.343";
      
    };
    paths = [ src ];
  }

  rec {
    name = "javax.inject/javax.inject";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javax.inject";
      groupId = "javax.inject";
      sha512 = "e126b7ccf3e42fd1984a0beef1004a7269a337c202e59e04e8e2af714280d2f2d8d2ba5e6f59481b8dcd34aaf35c966a688d0b48ec7e96f102c274dc0d3b381e";
      version = "1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "bcprov-jdk15on/org.bouncycastle";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "bcprov-jdk15on";
      groupId = "org.bouncycastle";
      sha512 = "b2d267e5d198a4c51318a53fa3cac5a769521f217ea69dd40c3d2372ea3a00d1245585f8916cad77c9a11d561aed04840c73c6095d785b598a385561f99af8ac";
      version = "1.68";
      
    };
    paths = [ src ];
  }

  rec {
    name = "buddy-core/buddy";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "buddy-core";
      groupId = "buddy";
      sha512 = "0daaf122ecbb6aeb695f88a8d0c423b6bb9a467cb037dad3197e41327c1c58562ea00909b21ff1b8cdab958b4764315f4518b17cbfba21fd609ba85c7a9eabf7";
      version = "1.10.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "selmer/selmer";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "selmer";
      groupId = "selmer";
      sha512 = "c1eec23309037ad83b056cfb45fba1cfb9b8f0c5833783f09384cf91335730b40ae5845b8cfbf3e1b2cfc4b854581e1c4027f91ca803d924a7fa1f624f679b11";
      version = "1.12.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.json/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.json";
      groupId = "org.clojure";
      sha512 = "04b7c0c90cb26d643a0b3e7e1ffa2d2d423e977c1454ee5ea7c2e75547ecbc113838df17b797902a975f5ea2184a81a45b605a4d82970805e2bbb02feebc578d";
      version = "2.4.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "lz4-java/org.lz4";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "lz4-java";
      groupId = "org.lz4";
      sha512 = "98d59086a6021ca571d9c1d64b715e43044c730e1ac563f514c40cf44302615d30378b6d5cc69990446522de6260dc8e7b303e3990a3139dc326d058dfb6dbd9";
      version = "1.8.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clojure/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "4bb567b9262d998f554f44e677a8628b96e919bc8bcfb28ab2e80d9810f8adf8f13a8898142425d92f3515e58c57b16782cff12ba1b5ffb38b7d0ccd13d99bbc";
      version = "1.10.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "profiles/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "profiles";
      groupId = "software.amazon.awssdk";
      sha512 = "ced7fe4a5a6f6368f8205a03ef1b6d4349cba9065cf6c991e8a3d262cd1c9d21fcda645bf3c4691ef31701c92cfbc1a2abd06dc58bb05b10f89bf4ca04fc8bac";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-codec/commons-codec";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-codec";
      groupId = "commons-codec";
      sha512 = "da30a716770795fce390e4dd340a8b728f220c6572383ffef55bd5839655d5611fcc06128b2144f6cdcb36f53072a12ec80b04afee787665e7ad0b6e888a6787";
      version = "1.15";
      
    };
    paths = [ src ];
  }

  rec {
    name = "dependency/weavejester";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "dependency";
      groupId = "weavejester";
      sha512 = "ad4c19339b54da3156dab22998ed1aed8995c1e1f682dc42b04e1fb6950aa72d070f364ea36fd20db8e7b75a101c66d54857c4406f55fed60ea5d23a631fd34b";
      version = "0.2.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "api/com.cognitect.aws";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "api";
      groupId = "com.cognitect.aws";
      sha512 = "31d6275364e92e1d9f6e3810cd64e6f64421a3965314a5f61902c9a797808901f118f01e05dfe0bc2d4e2288432b264c8197aa5847289a46452ed4bb24e14fd5";
      version = "0.8.536";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.analyzer/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.analyzer";
      groupId = "org.clojure";
      sha512 = "c51752a714848247b05c6f98b54276b4fe8fd44b3d970070b0f30cd755ac6656030fd8943a1ffd08279af8eeff160365be47791e48f05ac9cc2488b6e2dfe504";
      version = "1.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "criterium/criterium";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "criterium";
      groupId = "criterium";
      sha512 = "e3ed38fa5f02f42a78691453a1f0a19f6c742417047ed84ca9c75fe69557dcd0ab2202011bae080ecd56bd105c97631bae1f9a3a659a716e3bcd0e4c7b53cdb9";
      version = "0.4.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-xml/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-xml";
      groupId = "org.eclipse.jetty";
      sha512 = "76962417c1eed8401a3560616709373c2c0db724aa4d15c65fc88639bfb4fb72801937fea63a9baaca3419ef22c86ccf485d014b9d3990ea641a7fa1e28176fc";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "HikariCP/com.zaxxer";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "HikariCP";
      groupId = "com.zaxxer";
      sha512 = "a41b6d8b1c4656e633459824f10320965976eeead01bd5cb24911040073181730e61feb797aef89d9e01c922e89cb58654f364df0a6b1bf62ab3e6f9cc367d77";
      version = "5.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-servlet/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-servlet";
      groupId = "org.eclipse.jetty";
      sha512 = "65c1d467eda23939682823a35ee39d058b280affec38e1c53261b4d464cb56fba3bc5bb0563e36bbf908f6cedee5fa12ce3d38887132d304efc95a53a90fc736";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-component-annotations/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-component-annotations";
      groupId = "org.codehaus.plexus";
      sha512 = "cc534fda54272f074fe9edd581a6c3e1ea98127340c7f852c4b4953a44dad048ace22dfa10f30d6adcdfc15efd319dac778a03ebbe20de7779fd1df640506e88";
      version = "2.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "endpoints/com.cognitect.aws";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "endpoints";
      groupId = "com.cognitect.aws";
      sha512 = "c5ea8379bd1d2bec5696f1b564781eaee5f00d477566613b01bd45d499ea856f850b5511cc4217fe5e39b3a88e755f8a1d80b79142c2324d140e067ac021ef7b";
      version = "1.1.12.93";
      
    };
    paths = [ src ];
  }

  rec {
    name = "error_prone_annotations/com.google.errorprone";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "error_prone_annotations";
      groupId = "com.google.errorprone";
      sha512 = "bd2135cc9eb2c652658a2814ec9c565fa3e071d4cff590cbe17b853885c78c9f84c1b7b24ba736f4f30ed8cec60a6af983827fcbed61ff142f27ac808e97fc6b";
      version = "2.1.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient";
      groupId = "io.prometheus";
      sha512 = "ac990d9286eda0044f12b3dbaa94fb04772ee58f21b2759af862d0b506ddd2d304d4e1d82ef8dd3620d30716aed900dc21c19f869a23716a304d45da688944be";
      version = "0.9.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-lang3/org.apache.commons";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-lang3";
      groupId = "org.apache.commons";
      sha512 = "fb0fe98385496a565678a000c26a3245082abfbf879cc29a35112b4bf18c966697a7a63bb1fd2fae4a42512cd3de5a2e6dc9d1df4a4058332a6ddeae06cdf667";
      version = "3.8.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.logging/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.logging";
      groupId = "org.clojure";
      sha512 = "af7fd2d53c589de7f29ed9568d14a3cd23d6276595eb73043c7b96785ce5f470e8d3ac8934963aee241b5251936cad6c88f41fce66c4927b28318c0bdfbc5237";
      version = "1.2.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "aws-query-protocol/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "aws-query-protocol";
      groupId = "software.amazon.awssdk";
      sha512 = "9903ada55069c1b0dddff7e24094265f0e06f826ed1473230a592f91f5da12248e7486799adf321d0663f46739e7775fd066339bf748066843d8b8f7698ff480";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.specs.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "c1d2a740963896d97cd6b9a8c3dcdcc84459ea66b44170c05b8923e5fbb731b4b292b217ed3447bbc9e744c9a496552f77a6c38aea232e5e69f8faa627dea4b5";
      version = "0.2.56";
      
    };
    paths = [ src ];
  }

  rec {
    name = "websocket-jetty-api/org.eclipse.jetty.websocket";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "websocket-jetty-api";
      groupId = "org.eclipse.jetty.websocket";
      sha512 = "c7b15f61e22752793e631b5c40bef99c818b1b54f7f1df7a4bc102b751b685f2df7a478479110f145abab4c1a35558f32f55b680fd512cb73061643ed7a5969d";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "xz/org.tukaani";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "xz";
      groupId = "org.tukaani";
      sha512 = "8cf42ae7d57c2115b9d86dc22eb782f0e0b3348a3927d013ef6a04cf444074592a4614f5e43328f6a55560b90945381a697fa01c47faf54be5b0ef202472ad0d";
      version = "1.8";
      
    };
    paths = [ src ];
  }

  rec {
    name = "websocket-jetty-common/org.eclipse.jetty.websocket";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "websocket-jetty-common";
      groupId = "org.eclipse.jetty.websocket";
      sha512 = "78440166fb84c9105a6e15464534f3d2ca6f2937d89c510796ea1fe576dd5d730c06786e7c3bce8a90304c95936dd78122c39a9d6dc67617c495f4bcf54c64a6";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "javax.annotation-api/javax.annotation";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javax.annotation-api";
      groupId = "javax.annotation";
      sha512 = "2453330b27a0822bba440c28b98ae1d83d60d97dfa2d040562dd5126b3548e0caa040fea3b886ac6feb0a858e6c1bc45b6c5472b180f1f14792e5ca33e355959";
      version = "1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "bcpkix-jdk15on/org.bouncycastle";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "bcpkix-jdk15on";
      groupId = "org.bouncycastle";
      sha512 = "1d18b43537370e0c7eb29332c9f9a4f0162f9bf68a79d6df3fb76080a8b96e1e378537e5a7aff481f2e1390cf45558b18679a1557ffd3c3b670b7ba1d625e8dd";
      version = "1.68";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-common/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-common";
      groupId = "io.netty";
      sha512 = "b26b4e736749c5a75be06d83c08afb1645c3e748786b48c71b059c7d22b95324a5a23a0c2a8347d89124535b7f0fb66569575a675fd7f935d20e189658b8044f";
      version = "4.1.68.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient_jetty/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient_jetty";
      groupId = "io.prometheus";
      sha512 = "4560eee4b19c50955391fd73193fffc91b514cb357e7fd040ae62d62e4af33917f3f9159e7b2643e52e8bf55e3c83b933c22bfff07c149cf27a5a7eb6ae34f38";
      version = "0.9.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "kaocha/lambdaisland";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "kaocha";
      groupId = "lambdaisland";
      sha512 = "1b8e3f6e3ce93ae3ce2312a4df562606d4eb481b3e3f851c997ed87cebb3737a363e96b9fa6d1ea2181a4b9cf1b3b1740bfbdfc5e70caaf74bb522973f143032";
      version = "1.0.887";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jeromq/org.zeromq";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jeromq";
      groupId = "org.zeromq";
      sha512 = "bd502d345926160b1a09e45f60eb81254dc67d6d9d7b79e025c08018dd16a18d32ff85b2440c352d530e61c96cd3b2d88fee2a8a912b436015ed31039e308ff4";
      version = "0.5.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clj-ldap/org.clojars.pntblnk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-ldap";
      groupId = "org.clojars.pntblnk";
      sha512 = "78240d3e0b6a57b9c9cac1ebc1c2fc55299aea482b650abf4be6f5cadaa9ed176b0f1a04d2c944fdb1eccb7968696cc318f115256615d849b6546a1156c682f4";
      version = "0.0.17";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-databind/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-databind";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "2e7b06d78565254718954ad5ca180476ac4327a4ddd8e07d84a5cb52c55d81870cdcfd08bd54ee984e75b4b7c30e21a9100962cda6275f16106357b7cca4478f";
      version = "2.12.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "expound/expound";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "expound";
      groupId = "expound";
      sha512 = "19fc1c525247edd4bbcdb206452e67021ec7f787eed82dfcd017189c6d30048a9884259ffefd15feb26555fb2ef559be05a0cbe59c5af3e0850f95e2fde5ff05";
      version = "0.8.9";
      
    };
    paths = [ src ];
  }

  rec {
    name = "spec.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "0740dc3a755530f52e32d27139a9ebfd7cbdb8d4351c820de8d510fe2d52a98acd6e4dfc004566ede3d426e52ec98accdca1156965218f269e60dd1cd4242a73";
      version = "0.2.194";
      
    };
    paths = [ src ];
  }

  rec {
    name = "apache-client/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "apache-client";
      groupId = "software.amazon.awssdk";
      sha512 = "e133f6345871315cb6cfb2f904e7e5a7ce5b973f7b6764c64093f18c4c138b17120eb44df817e64e70e7ef0c038a02ac48349cde01dc35aad5a0219bbd834616";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.cli/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.cli";
      groupId = "org.clojure";
      sha512 = "1d88aa03eb6a664bf2c0ce22c45e7296d54d716e29b11904115be80ea1661623cf3e81fc222d164047058239010eb678af92ffedc7c3006475cceb59f3b21265";
      version = "1.0.206";
      
    };
    paths = [ src ];
  }

  rec {
    name = "http2-server/org.eclipse.jetty.http2";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "http2-server";
      groupId = "org.eclipse.jetty.http2";
      sha512 = "3eb311679c749d27a23b36c951f7c5118f8af94dc39a759771993b0ea77ea5c44cc06ddc38df91588e946b04d846c97066f8907189d4b3c61988bc22d7de080d";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clj-uuid/danlentz";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-uuid";
      groupId = "danlentz";
      sha512 = "10c0ba460baadda446b1291423185e25e5a1bd82eb3ed82b0ee589f3e15bbe3f3a2c679767c228e01316ef27aaf60b7c1bceacef78f5604b7a11efe99207c227";
      version = "0.1.9";
      
    };
    paths = [ src ];
  }

  rec {
    name = "puget/mvxcvi";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "puget";
      groupId = "mvxcvi";
      sha512 = "2e18d3335888a394f24afd1e4d84a7f0feb4ead5878a5ad180c01c6e3cc539685b0b8df3374e71f7d2828e9f75b5b867380de055a317c7dbb7506ba8a065abfb";
      version = "1.1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "lettuce-core/io.lettuce";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "lettuce-core";
      groupId = "io.lettuce";
      sha512 = "c6365f8db12b11c34fcc4187dbe6d462961f15b41a16194ac053127a7a9fc8db935ce2ca6a51d791689a77a2aad0d558068f759e6a2bcd297815b9580c7850b7";
      version = "6.1.5.RELEASE";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-fileupload/commons-fileupload";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-fileupload";
      groupId = "commons-fileupload";
      sha512 = "a8780b7dd7ab68f9e1df38e77a5207c45ff50ec53d8b1476570d069edc8f59e52fb1d0fc534d7e513ac5a01b385ba73c320794c82369a72bd6d817a3b3b21f39";
      version = "1.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "s3/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "s3";
      groupId = "software.amazon.awssdk";
      sha512 = "c9a72a6876131de4c9203e7c5dea6f1b62bad1ca90b6917929d6d240a2738504117a59753b687638a59d1f16cc53312102f17aa6c40851233df6421c12e3d9bc";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "im4java/org.im4java";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "im4java";
      groupId = "org.im4java";
      sha512 = "9e5e68e71f07a8a5ecee344df3f6da27d19cd14b308ef2b89826e4aec5e3f4637c8bafde44379fb28c09356b5cb3b2f9e10c1b30aa5c695cb6c4aa5b486f4dc7";
      version = "1.4.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "animal-sniffer-annotations/org.codehaus.mojo";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "animal-sniffer-annotations";
      groupId = "org.codehaus.mojo";
      sha512 = "9e5e3ea9e06e0ac9463869fd0e08ed38f7042784995a7b50c9bfd7f692a53f0e1430b9e1367dc772d0d4eafe5fd2beabbcc60da5008bd792f9e7ec8436c0f136";
      version = "1.14";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jakarta.transaction-api/jakarta.transaction";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jakarta.transaction-api";
      groupId = "jakarta.transaction";
      sha512 = "02d8b4d559073298a2c49e41bc4dddd902c5e4142a56439188d6212cf5386c966a02aed2825993a25429ca5b7291eb3b60e57e1868f0a0197390fc40c37f4c4b";
      version = "1.3.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-http/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-http";
      groupId = "org.eclipse.jetty";
      sha512 = "22c06a0bad8648f635babfbd93a9266e70417d62c23d493681644896ed95b04192fdd4b68e33fa7ad43ee22ff6d4965b7959dc2c60881df24007f9bb6557eec2";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-util/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-util";
      groupId = "org.eclipse.jetty";
      sha512 = "cceb62d815904ef718df24ee5e9a63305bddbe4143ff2000ee76c55be225078fe4c9773ec760c24c4b073e88705e8d404f65dbb247c4a97f1dfd59742cf886c0";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "encore/com.taoensso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "encore";
      groupId = "com.taoensso";
      sha512 = "52649b4099427ebc13c82f46385ef34a5f3a2134900599c8eebf2532b0d47e967384c84be4348320ab5d6ee8d1c85a525a7d4b86c00c695d519ba8b62492dd0c";
      version = "3.9.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.zip/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.zip";
      groupId = "org.clojure";
      sha512 = "c8292624d89ad67c336230870bffcdb19c018e0607ad76cf52c6ec2975791b22a08a8d840d36135edbda78c67c6d1d1e39d3024820598c932efda7d3dfc3e46f";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jcl-over-slf4j/org.slf4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jcl-over-slf4j";
      groupId = "org.slf4j";
      sha512 = "aed539305114718bd76da54f29a391362eb331108d9c033956bf68df29c62a44874c73ae39d19a25342625b6092326d39b4d8720aed6c62234a234e0855b00b5";
      version = "1.7.30";
      
    };
    paths = [ src ];
  }

  (rec {
    name = "io.github.cognitect-labs/test-runner";
    src = fetchgit {
      name = "test-runner";
      url = "https://github.com/cognitect-labs/test-runner.git";
      rev = "dd6da11611eeb87f08780a30ac8ea6012d4c05ce";
      sha256 = "0ydhv733sjz7s65qdy9a968vdyd52iglxpfivyqi6sslz76r0gmk";
    };
    paths = map (path: src + path) [
      "/src"
    ];
  })

  rec {
    name = "tools.analyzer.jvm/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.analyzer.jvm";
      groupId = "org.clojure";
      sha512 = "36ad50a7a79c47dea16032fc4b927bd7b56b8bedcbd20cc9c1b9c85edede3a455369b8806509b56a48457dcd32e1f708f74228bce2b4492bd6ff6fc4f1219d56";
      version = "1.2.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "barbary-watchservice/net.incongru.watchservice";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "barbary-watchservice";
      groupId = "net.incongru.watchservice";
      sha512 = "94df2c848b711e49f08bafb407c9a12779eff7127b12a3b645917d4c4ff987782905de24bef479c4aa5543af9b4ccae92ce3cd5312799bf69ed75d7d00a39af1";
      version = "1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-codec-http2/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-codec-http2";
      groupId = "io.netty";
      sha512 = "fdcb80f2900a6a6438068784db048897aa0a83cbcad57d492914138bfbcf363b62ff312ffbcbf55fa51f134fd0f1ace38444c1a8053830228de090d90cc2cf63";
      version = "4.1.68.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-codec/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-codec";
      groupId = "io.netty";
      sha512 = "39611457765449f0409a5532a5991d0ba53a4462d98f4830b427139bbd66a999f92c19fb49bd1df439be9a501d10592613445ec9ac62eefbbec5ec43d6635ae7";
      version = "4.1.68.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "zstd-jni/com.github.luben";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "zstd-jni";
      groupId = "com.github.luben";
      sha512 = "920084f05e16291cb930b4ccdfbb51bd32d27abd80283895d7136b386a27bb96c2cfe8a056e3dab6bfd58663217eec4fd8f7914afc0b427d02e94a0629ef89e8";
      version = "1.5.0-4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-jul/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-jul";
      groupId = "org.apache.logging.log4j";
      sha512 = "5e9a12caa1bb1aebef7c0b93d23262987e687ba039bbe48ecb5ad77f749935eb51d70bb9acde46aee117de691cd54481dcd48d4742014f1a8a476a7f71b11937";
      version = "2.17.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-annotations/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-annotations";
      groupId = "org.eclipse.jetty";
      sha512 = "e1f9e8814fbb2afc674b9ef8ecf6ab0bf2b498abc35c2aa00885f221edca3d634240a35cb89c5e1547d2eefb0d9fd7dad6e3e782320236847e73045a518e1117";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "deep-diff/lambdaisland";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "deep-diff";
      groupId = "lambdaisland";
      sha512 = "7dccf8b2e260004bcfe1dde9b5ab3e24853b440173ac1f224e03650e1ffcb25d760625b2b919c1b7e913cf224217457b19278786514e34e2e85abd8ff86e94e6";
      version = "0.0-47";
      
    };
    paths = [ src ];
  }

  rec {
    name = "third-party-jackson-core/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "third-party-jackson-core";
      groupId = "software.amazon.awssdk";
      sha512 = "d5b1e14896d834b8ad30b88f91bc899eb3e246fc880456648a8637a42d767c887b1d7e34cc6d3906c90505d25b9206d47edddb6224e228650f09ef9d7aa46a8a";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-dataformat-cbor/com.fasterxml.jackson.dataformat";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-dataformat-cbor";
      groupId = "com.fasterxml.jackson.dataformat";
      sha512 = "575a00fec1760571403aaadbe0aa6c74f8bb01f40feae00741df6604e7c2bf199ac739a789bbd5d83af75ec6d9fcc55f5a1515b05aef33e0d3cc3046acad9e89";
      version = "2.10.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "websocket-core-common/org.eclipse.jetty.websocket";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "websocket-core-common";
      groupId = "org.eclipse.jetty.websocket";
      sha512 = "5319a8ffcc2525b24a81c86fccb033b71ed11876f13ee664a7d0c92e6185adaceb88f22286bb4172fa59831e87894da81d34466ee07cd3892e1603e5e4e799ba";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-transport-http/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-transport-http";
      groupId = "org.apache.maven.resolver";
      sha512 = "0650fdfa290cfa43e7d723d1092743016d8b2bb4fad825ef93e43e4ce687d41310967015e6faa14a0d3fcaac75cc8916a4b50053d77a60686d2d3fa6e51e9976";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jline-terminal-jansi/org.jline";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jline-terminal-jansi";
      groupId = "org.jline";
      sha512 = "4ccb0b89d7523d65e5f4ff02749be935aa2d4da2fbd6c18ff72c70f4cd279a67c4dccc7cdbacc4581e37c9984322cd184af2bf051939f457cfd4546675bd8b15";
      version = "3.5.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "json-simple/com.googlecode.json-simple";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "json-simple";
      groupId = "com.googlecode.json-simple";
      sha512 = "f8798bfbcc8ab8001baf90ce47ec2264234dc1da2d4aa97fdcdc0990472a6b5a5a32f828e776140777d598a99d8a0c0f51c6d0767ae1a829690ab9200ae35742";
      version = "1.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "snappy/org.iq80.snappy";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "snappy";
      groupId = "org.iq80.snappy";
      sha512 = "dfd2559bf0388c6f1987d1393497a423203b2a72febbe648b3429e4d07b47a504797228e6e4e39a94c6800c5d3df8d3792863a3b841e6e8f65cfdcda91b6f0ab";
      version = "0.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "sentry/io.sentry";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "sentry";
      groupId = "io.sentry";
      sha512 = "31e0e73855ecb05c76ce188db5c7df496af727e013724afaec1c8f8f8544d35d313f950de98fbf906f119983fcf6198783bce2f3d02b93147e783658ae18f3f4";
      version = "5.1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-cljs/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-cljs";
      groupId = "com.cognitect";
      sha512 = "526d3331857586ab7e8edb78795c375aaafe6dc3da24706663918a7dc38e25db7d0f554c334ec3be0334050d59d8616bd9cd6c9a90cf4bb4b33b1e0ea294d29c";
      version = "0.8.269";
      
    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library";
      groupId = "org.clojure";
      sha512 = "cf74661c5bc4658674397e498366ed12ce8b6f6cf51cdfa4cd0ce99415203028ec0bc4b59032a73ad4bf29421a643b2e6799fcd8a35f4f1e8676b3c04900a0b3";
      version = "0.0-20201211-3e6c510d";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-model-builder/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-model-builder";
      groupId = "org.apache.maven";
      sha512 = "31ce438801c4e402dce94a11661da33598888189a478a7d4019cb1e5a1ba9ed99ba527812491728e41382b8fc9c726dbf2d574c3fe1851d71d5c19ddc3083eeb";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "pretty/io.aviso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "pretty";
      groupId = "io.aviso";
      sha512 = "416433ae5c5773a3a12e7cff3f75a43f1a2d3f4454aad04d065c1e4e13627130f289dbb41355a5665236082b6535939fc4c40a2fddcc22a40d0d4ba290544bfb";
      version = "1.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "rebel-readline/com.bhauman";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "rebel-readline";
      groupId = "com.bhauman";
      sha512 = "5a6881ffc5a5fd0726938ab54d5917113f7f02a79a1ca8afc1f44967fa57877d30574ac1b6c1eccb37aaaf86b523ae35abe05430851f4087c12ab7a6ef9b10ba";
      version = "0.1.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "aws-xml-protocol/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "aws-xml-protocol";
      groupId = "software.amazon.awssdk";
      sha512 = "80fd1a0f483dfed4c31c995c4309c35eda518994ab4c13d9ff72c34b403921b2bf1907b215175b83002ba6ccc97f5be801cbb730c47bb1e736aeb42c099fa64d";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "cljfmt/cljfmt";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cljfmt";
      groupId = "cljfmt";
      sha512 = "0b1276cd8d7aa45b6615cf0361ff31f8c24d1e656767c5eb751fc50ad6a2936edecc3092d4606eef8b600ca79336f7094816f7b2ac3e1c68b3a0c01277cb501a";
      version = "0.5.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "rewrite-clj/rewrite-clj";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "rewrite-clj";
      groupId = "rewrite-clj";
      sha512 = "6e878952f453d7b6df9dd47db977623b59e6d9f6965f67b463c35e0457e45baf298378ae175b0be61c11d38e0906334e2f2862bcf3dfba60d947a2ce4c2a2fc9";
      version = "1.0.699-alpha";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-cipher/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-cipher";
      groupId = "org.codehaus.plexus";
      sha512 = "8f187b07867a7c29d77454aae4b76479300238d9c4e777c1afa2aebe33b88dab916e29111dd55acac1341849f4579fe91a5470fdd45ccba0e05709c2ce3a1d65";
      version = "2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clojurescript/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojurescript";
      groupId = "org.clojure";
      sha512 = "cba372c69db8ef710227434595e672d9654aad3359f3b17ee898d721e067df1691ec48a64e9b1f509e80443e4919a47ebf8e9301808abc072014a3dcb5e7e65a";
      version = "1.10.844";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-utils/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-utils";
      groupId = "org.codehaus.plexus";
      sha512 = "0668d413520a713d9279123eccae3b5e9bc79f41dd8da3b3a1ba79b7b60086c009639d91d84df230e490192fe63b10390f3901478c69bfd452a1280364d24876";
      version = "3.4.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-transport-file/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-transport-file";
      groupId = "org.apache.maven.resolver";
      sha512 = "8037285f888cf37cc3563528bedb3171a3987750b137ff2c6f77e6ed25fcd0d84be3aa80bebd283bfd5decfb8c55452e701f513a2f4e89ac765cb683b332e87a";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "org.eclipse.sisu.plexus/org.eclipse.sisu";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "org.eclipse.sisu.plexus";
      groupId = "org.eclipse.sisu";
      sha512 = "38d7dbe023f9751cb5e30bf154e31696590317dc7b7f768811fe0f5940513fcea4665670cd47d0b72ded85453b10f7d129b0b7428b155a41c903c7b56c986e8d";
      version = "0.3.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-buffer/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-buffer";
      groupId = "io.netty";
      sha512 = "591d6741b784ac712c855489c76e8d6bba36c9685640e522228435508fd82953ffaa9560282e70c177e1b3fcbc1d876f9f9b4415ace990dee2f6ddf1cef7ae05";
      version = "4.1.68.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "slingshot/slingshot";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "slingshot";
      groupId = "slingshot";
      sha512 = "ff2b2a27b441d230261c7f3ec8c38aa551865e05ab6438a74bd12bfcbc5f6bdc88199d42aaf5932b47df84f3d2700c8f514b9f4e9b5da28d29da7ff6b09a7fb5";
      version = "0.12.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clj-async-profiler/com.clojure-goes-fast";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-async-profiler";
      groupId = "com.clojure-goes-fast";
      sha512 = "c0eeb645c44b7e1c3d98242e8fe44faad5a48375475ed238c33fdb622a1cc6f64fdd7ceaac4e6664121ebcd2f32c22522d3a745e8a45a6a78b6bee4b0a3b046e";
      version = "0.5.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-handler/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-handler";
      groupId = "io.netty";
      sha512 = "69a18e338c9bc4ad1298577d857697ef3e3c5d5fd94817e52800d9b460744dae9657a388752b3a81c1096f7530dc37fcd6f188de1d15b0791987ba18fa10e305";
      version = "4.1.68.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ordered/org.flatland";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ordered";
      groupId = "org.flatland";
      sha512 = "676db4c71999127822349f5f97960115aa5f3124eb3a93b441680c5ba747ebc1981718f93e8dc94fe34f0c1c84ea3568c452691967b92509e5e125dac3ee59eb";
      version = "1.5.9";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-io/commons-io";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-io";
      groupId = "commons-io";
      sha512 = "6af22dffaaecd1553147e788b5cf50368582318f396e456fe9ff33f5175836713a5d700e51720465c932c2b1987daa83027358005812d6a95d5755432de3a79d";
      version = "2.10.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-settings-builder/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-settings-builder";
      groupId = "org.apache.maven";
      sha512 = "6edfc7281dbb75596c6d87bcfa38b120539eb3e99e85a8763a06b27e90778b59032191b4380b3630e37e68599ef9092d04fa8ab823d9ffecd1ed45af3d9c302e";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "websocket-core-server/org.eclipse.jetty.websocket";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "websocket-core-server";
      groupId = "org.eclipse.jetty.websocket";
      sha512 = "c503d6c127e6763b63e84af58d8adc45224e7fc93c530f6e513647bac4f0cf5ec68661f6677d9a96c61d20622ab3d334d47cf1a1048f0596504fcf1670af05b8";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "postgresql/org.postgresql";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "postgresql";
      groupId = "org.postgresql";
      sha512 = "b68480b04dfd352e7b4655949a85eefea88bb6d1ecddfccb73fd5513136716f711c006ef2e104524d24bc608d83f63d54f474df65695c5c83a364a1d9b092aa8";
      version = "42.2.23";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.namespace/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.namespace";
      groupId = "org.clojure";
      sha512 = "8d3b51778c09f69385eaffb9d288f53cf88310210fff9360211ef8f340dace698be0b235e28c6a953033f8b8471665033f9004382ddeecd0d30cd80ecea52da1";
      version = "1.2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "http2-hpack/org.eclipse.jetty.http2";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "http2-hpack";
      groupId = "org.eclipse.jetty.http2";
      sha512 = "bacf48aae6b94024865416988698b40d302108554a4854f3cf0f4c5af68ef389280231fb0bc847979967f14e8d6967888bd5c83f5d9e91d07380a729dac5a110";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "fipp/fipp";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fipp";
      groupId = "fipp";
      sha512 = "4697699e9d5b792998e8c7ab6bf08d0d84c3e88793a0ff7024c10105f0db5703bccca9c43bb7fea00c1621af0d0604c89d623d74fde771a0d2e17835e1ab87b7";
      version = "0.6.24";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-plus/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-plus";
      groupId = "org.eclipse.jetty";
      sha512 = "0aaf4ccfdee256d6581cfc3ed8734e339d17d81536bcf5769cd3587f73aab975e497fc06076b71820547b3f5c9aa64046f2361673166660214af904ce5ef616b";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-core/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-core";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "bbbc4fba33448854627f9764b1e086370e607b29819884415f21d1943243b0bddc781d71d56021dea52386f1b230a344f852dc3ea0e904559b95ca60e03068ca";
      version = "2.12.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "pretty-spec/pretty-spec";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "pretty-spec";
      groupId = "pretty-spec";
      sha512 = "eac4574f49d307cf8df28c6c14cdfbdd2f4a34a4f6f9e9a76e9ae30509217b1e643750c31fde67f0059dff3bae0739e4d469a3ba53339640315ec4cfc00d7796";
      version = "0.1.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "snakeyaml/org.yaml";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "snakeyaml";
      groupId = "org.yaml";
      sha512 = "dce610268daab6fd6bac54f819f2f5795b17a57792b0f5553ee72acfbe8b9f81367ba7419655be8348369eb489259b14ddab7cea7a0c3c1b193bd62e0715cfd3";
      version = "1.26";
      
    };
    paths = [ src ];
  }

  rec {
    name = "websocket-servlet/org.eclipse.jetty.websocket";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "websocket-servlet";
      groupId = "org.eclipse.jetty.websocket";
      sha512 = "fd19f5e53688eaef4e9b691cf64533ad7d145220e9de93d9862781c79efda14cbc70524cc9dc77bae6ebd4f671a39e61fb076257810146215ce1de4da36adad2";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "aero/aero";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "aero";
      groupId = "aero";
      sha512 = "e4a90df681e1121152593e837312971ae8cdadba3014726f4a6259e2b341452287ee2e8793823da6209cd6f85b1be7ea179e713a55d81d10b4651e3c9c5cc3b2";
      version = "1.1.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm/org.ow2.asm";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "asm";
      groupId = "org.ow2.asm";
      sha512 = "876eac7406e60ab8b9bd6cd3c221960eaa53febea176a88ae02f4fa92dbcfe80a3c764ba390d96b909c87269a30a69b1ee037a4c642c2f535df4ea2e0dd499f2";
      version = "9.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "websocket-jetty-server/org.eclipse.jetty.websocket";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "websocket-jetty-server";
      groupId = "org.eclipse.jetty.websocket";
      sha512 = "254c740123e323f81a0c490e3fb7880778ca53ac59561e05a2d179c2ebfc6554096d86da738a83bf46703cfe4e24e71da05d6a5757cd9a2669c02771ffbc9105";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-settings/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-settings";
      groupId = "org.apache.maven";
      sha512 = "9135e9a135a47a6456650c098908fc4ebfe6c978c7ada08d6509834d9b5abdcaadff1e9024c9372c1e0dded4f23a98f22e261c8d5d7f8ebd306e6c4538962ec0";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reitit-ring/metosin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "reitit-ring";
      groupId = "metosin";
      sha512 = "6ad8e3535a3d8552895f1211adb2e164985e69b34492ceb50f8c7560d1c13c639a6387c54bd5b759ddb59beb591b2796f897892451af89a0012122c7e5a15253";
      version = "0.5.15";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-core/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-core";
      groupId = "org.apache.logging.log4j";
      sha512 = "e28fa0f1cbac0d925055b4c89de3c1f7293a001574b8479b7ae912dff051ed35477847509d70586a3b7637f0f529f701235766abdfc755f261a2aaf6dc2a70b8";
      version = "2.17.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.namespace/lambdaisland";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.namespace";
      groupId = "lambdaisland";
      sha512 = "0e950a891166f7014465c811a633ff0c77da6a346f3411a66b88e1b04fc7796439ccad25bbcd1c431456a5e50b1bf0005d14294450d3006f2f5ca24020fb1abd";
      version = "0.0-237";
      
    };
    paths = [ src ];
  }

  rec {
    name = "httpcore/org.apache.httpcomponents";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "httpcore";
      groupId = "org.apache.httpcomponents";
      sha512 = "23430cde8b9bed33c91474ba49f1143284135df1b25fdcbc37bc3bb7e9549e77b3918eb40250093db652ae200367e87316129b23b4f6987e94939d60f467498d";
      version = "4.4.13";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-security/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-security";
      groupId = "org.eclipse.jetty";
      sha512 = "be64bc3fd794b5df461b61aaad38e0741132266553b8bc455a20a1a9bc60e6bfa49d1ab02a0a9c86716abd7b45350c7e68df3e1e5514250d9dbd737a39207057";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-reactive-streams-http/com.typesafe.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-reactive-streams-http";
      groupId = "com.typesafe.netty";
      sha512 = "e387b8a681082960309d1cd0c4f1311f75e1244c9ac3895374c148adde9f00f5e4951b05e170503f6e647fec75846ffe1aed4353c1751d8d74251fc6e8cbed29";
      version = "2.0.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "primitive-math/primitive-math";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "primitive-math";
      groupId = "primitive-math";
      sha512 = "02fd7cabe27cbb11a944059b1b5261ed089f3e5c641246da6d5a2ab2a6afd3d33c9fb1300f948255f4958551f91b93c5fd930bc3d657cbb9c95fb05bf0a238b9";
      version = "0.1.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-sec-dispatcher/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-sec-dispatcher";
      groupId = "org.codehaus.plexus";
      sha512 = "ad4e814c8baff780a4eee064903e52b09ae00420a59fb075ef72dbb8d64d12d3d5009b03d56c15f93587d931c3a7f06cad6351ab2dc9415ccc6eeab0daebeb07";
      version = "2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "arrangement/mvxcvi";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "arrangement";
      groupId = "mvxcvi";
      sha512 = "f94a0fa8f434f3a2115840729ce428adec81ebb97e649625780382e714a92074208b3e21d7dba5b15824eced4e565da02c96210f705991f6945bcde33dac67d6";
      version = "1.2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-core/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-core";
      groupId = "org.apache.maven";
      sha512 = "f786dfde86ece3208a96f652ab2994de6b0975945a6e981900a137b6b7ad89c9d52ab05f82acf4f59872ee75a404e817bd9774f052a294b9792964252b06c5d9";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jakarta.annotation-api/jakarta.annotation";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jakarta.annotation-api";
      groupId = "jakarta.annotation";
      sha512 = "d1acff146c0f9ea923a9325ad4c22ba2052ec474341ab8392abab7e8abd3ca010db2400ff9b5849fc4f1fa5c0a18830eb104da07a13bd26b4f0a43d167935878";
      version = "1.3.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "integrant/integrant";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "integrant";
      groupId = "integrant";
      sha512 = "cc0360e9f3ecb38854582db6b83004f51a8ac64a467b26e71289ffe6a594c7d96f634371d43ccf90c562eb5beda24ee5db98c1fe7ca0ce7d54d27375b6bb7d66";
      version = "0.8.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-web/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-web";
      groupId = "org.apache.logging.log4j";
      sha512 = "dd9ed3baec6a8eb81fe75e56d66ce535f074cbb0d5fb1cf416127b8dde40a649e79669fad42a38bce1d1895cf45e25dff019d1bd470519a1e835c7e7a93c4eb7";
      version = "2.17.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "buddy-hashers/buddy";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "buddy-hashers";
      groupId = "buddy";
      sha512 = "ee04b90b329e38436275192ae355069dc516a87ecaf23ac05155b6672c9bf0418efd7650ebb45dada35938e9ba6b3ec27912e8d1d7a6ab8e28c7fe8de78221b1";
      version = "1.8.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "sdk-core/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "sdk-core";
      groupId = "software.amazon.awssdk";
      sha512 = "2c86383618936446f9ba622deacfa550537df422bb3b7be41930983663b192d9d1f8add30c9f83a34a3555d4c7e126099f0b8a8024cf54e278c20eafe9d7759c";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "scrypt/com.lambdaworks";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "scrypt";
      groupId = "com.lambdaworks";
      sha512 = "bdf4e64b5b7231edf13e92b788593facb9e125ff9b1c69f48016314956d7fb58dbef00db27e8c1b7fe44d4b49aaef6253f8162c7d76723ec066c10f474bd5ae6";
      version = "1.4.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-js/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-js";
      groupId = "com.cognitect";
      sha512 = "bab8c657449a1d01e884923b77c5ef3d7a1a246c3ad1bd85a5b0c98b7952dbdeea97ce7d340ab50aa0dca647a1ef7eb846a52a1a4eecc55e1ff22145b8e820fe";
      version = "0.8.874";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jnacl/eu.neilalexander";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jnacl";
      groupId = "eu.neilalexander";
      sha512 = "addba1eae1975a71a204557dafb111c5c2aab39d9a7bb6428a26107935d95290139381c0a283b77e67b44e1d8110d3fa3919d7e7fc73e0023771beece4eab994";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reitit-core/metosin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "reitit-core";
      groupId = "metosin";
      sha512 = "05896174f32ba1f49df4d2a70e43fb8e36445ff483d67696afc969056431d340db9d6f91ea13d21790475c872871bb468903345abe19195af4cbcd6afd1be29e";
      version = "0.5.15";
      
    };
    paths = [ src ];
  }

  rec {
    name = "scrypt/clojurewerkz";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "scrypt";
      groupId = "clojurewerkz";
      sha512 = "70b5bed1b89318ee1eb0333fa11d88d10627cac372f498ab672bf1eba3639506fed10a44af452352b4002b5c7746c52e7407e034b437f31a61f445dadcd6fe9b";
      version = "1.2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jansi/org.fusesource.jansi";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jansi";
      groupId = "org.fusesource.jansi";
      sha512 = "300885d77568256b907bb9cdad5bd8bf91ab3b8dc67ad52c96f62d14b055a756f122edce0627b99984bd24df739189706bf824b1dfe273be43fe6dee018549dd";
      version = "1.16";
      
    };
    paths = [ src ];
  }

  rec {
    name = "truss/com.taoensso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "truss";
      groupId = "com.taoensso";
      sha512 = "79a515306228e8e8f1c1cf5bb65ac8c979954f3a6e8461c059a7b9402967163a1eb7a70de3ad41e8195d9dbfac2d17af8cc03e09bf72f8e9f6704b842656c0b9";
      version = "1.6.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "cuerdas/funcool";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cuerdas";
      groupId = "funcool";
      sha512 = "f52cfefdb9cf90cf43f51fae6d7e3e32e594f4cd2544afeff1a2487fddc5d4f8e986cdb2ba658aea6d8ee6034b3866cf1ee23c604d9c5f44d9cc6570c3519a0a";
      version = "2021.05.29-0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library-third-party/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library-third-party";
      groupId = "org.clojure";
      sha512 = "b0be9cdb227ce189d74a2c0e9fe8cfe53ae5608f0e00382c6c12b0087672c6caeb96890beefd9f285ca7e0c7e4bee760299e14d48512e3e37f1f274838a1693d";
      version = "0.0-20201211-3e6c510d";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-api/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-api";
      groupId = "org.apache.maven.resolver";
      sha512 = "002cb75f6e07b27108e79a4d37d94fa882e89a2db30dd2ac69ecf0907cc548e13f579ebfbb5c019da6df4a950e3420b69dac3d49ae94b5646b7968ef7ea811ca";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "regions/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "regions";
      groupId = "software.amazon.awssdk";
      sha512 = "8f4b3e4cd3576c3da9954679e4bfd7d20d63614743ef88c0a58b07ca191b10259099d80f29c7e952840335cdf6bef9f4be9a315c7c3b15462df7cdc739eb593e";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-annotations/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-annotations";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "5a1e45f0afe34eb36605b8763990f92ac5b4390432f058f682cf186bf3ba0f7325a67d4d35158ab22ac4fff025869722dd49365f19c47fc5f4c268f003ae773e";
      version = "2.12.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient_hotspot/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient_hotspot";
      groupId = "io.prometheus";
      sha512 = "91358202a44fe25eba94d9962b8f827478c119f2fa51f5e65df388b0947ca922508036a72fc947c1c4c71777176ceb29e0fa5a38d28bb9df5b4ef087b49452ca";
      version = "0.9.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "progrock/progrock";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "progrock";
      groupId = "progrock";
      sha512 = "68698e7d597eaf225244a321d395db1cdb01e9c4e76effd3d06499f129b8074631a68dd03c1e8739bdad94f056d6901b98d1b194fce024e72eb96b4e39b6679c";
      version = "0.1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "http-client/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "http-client";
      groupId = "com.cognitect";
      sha512 = "5507956051ce71d5f521537a443390d49be8fa629074fc19781d0e5e072207afa543ec690876eb895174d82b85810888eb839a0a3ee82ad3394244c7fb78e015";
      version = "1.0.110";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-provider/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-provider";
      groupId = "org.apache.maven";
      sha512 = "3ad268c56e63cbe87f8e6a9f16ac8260213a1567baef53fc7d69cca213fc479d9a543eae91fa1166c38cf88d8225c70f4f33a7064af3190f916b5f97fd8f35ad";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "javassist/org.javassist";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javassist";
      groupId = "org.javassist";
      sha512 = "ad65ee383ed83bedecc2073118cb3780b68b18d5fb79a1b2b665ff8529df02446ad11e68f9faaf4f2e980065f5946761a59ada379312cbb22d002625abed6a4f";
      version = "3.18.1-GA";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-webapp/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-webapp";
      groupId = "org.eclipse.jetty";
      sha512 = "94bb844c13024564ab3d8d266d6a2f706c5e6d7a099c2349d20588aeb2dc547cdb95fc7bcb6a482dc54bfc495a54584a6a22b17d611cb3b1b2c3449699ad66e9";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "checker-compat-qual/org.checkerframework";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "checker-compat-qual";
      groupId = "org.checkerframework";
      sha512 = "fdecc20efd6943426e7f8bdfb8bef9d28258f9f934cf29090e2f5b297c501454606cc28593cd7d089a5c14f6d2dcafc59f4606053405d7f91d623a0e3202f4a8";
      version = "2.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "linked/frankiesardo";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "linked";
      groupId = "frankiesardo";
      sha512 = "d47354631d642a603f1f64e1bd872f623d8e6e7a8c40e968bcf124681585920c423a51f3388f6a4101c5f346b3e10a17b7e256da617ca0d1f19a25169dac46f7";
      version = "1.3.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-shared-utils/org.apache.maven.shared";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-shared-utils";
      groupId = "org.apache.maven.shared";
      sha512 = "c6693f8a061de74ac59c61d185f5b130cb574405cfc37febb8e73806ea64eea822a4a75c24098fb49b7871373091543a6f4c526c0842589e528cacad40e5554a";
      version = "3.3.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "java.classpath/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "java.classpath";
      groupId = "org.clojure";
      sha512 = "90cd8edeaea02bd908d8cfb0cf5b1cf901aeb38ea3f4971c4b813d33210438aae6fff8e724a8272d2ea9441d373e7d936fa5870e309c1e9721299f662dbbdb9a";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.deps.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.deps.alpha";
      groupId = "org.clojure";
      sha512 = "204ac11ea37e817e8dcd147b9cd6b05785c025af2733bb3f757b8cc2f4452beefe3bafba553633b8bfc848d613f986964187aee3486ee30adb413358ce57775c";
      version = "0.12.1090";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-logging/commons-logging";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-logging";
      groupId = "commons-logging";
      sha512 = "ed00dbfabd9ae00efa26dd400983601d076fe36408b7d6520084b447e5d1fa527ce65bd6afdcb58506c3a808323d28e88f26cb99c6f5db9ff64f6525ecdfa557";
      version = "1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "environ/environ";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "environ";
      groupId = "environ";
      sha512 = "e318da117facf51a27b9ae39279363c4d824393215ce63fa69e5bdb65a910d1f8632d712598ad0c3f4248d0ab9274a97161859393d265d74d50ad2a4cdbddf41";
      version = "1.2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "guava/com.google.guava";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "guava";
      groupId = "com.google.guava";
      sha512 = "c8f95af9f1e97dee807503c8fbb442c87eed2694e43ad0fd9fc2e62ba99c5e93d476d5ee8f4791f173cb8fdabc88abac0e8130a51de280af836a3e0c4eadaff6";
      version = "25.1-android";
      
    };
    paths = [ src ];
  }

  rec {
    name = "datoteka/funcool";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "datoteka";
      groupId = "funcool";
      sha512 = "26826aad46c92f258389a7de77e6e8ab15c8a2ec359c3159dfe6f55e6bdd8d8ca0e4a6ad6efe70b07589338425038cdc63230c3ee8c3d2ccd89d2b330517a45a";
      version = "2.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-transport-native-epoll/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-transport-native-epoll";
      groupId = "io.netty";
      sha512 = "e705a248dbff66eafc68cddba1bbffe7c55e2b47ad10aaf154dc50b9ba6aa95abed95f99dd03c7e69246866a2c265058de5408f8d2060ff2e5ee7f55a900433e";
      version = "4.1.68.Final";
      classifier = "linux-x86_64";
    };
    paths = [ src ];
  }

  rec {
    name = "data.xml/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.xml";
      groupId = "org.clojure";
      sha512 = "12ea6e7ee27be4a0329a766f3449f3e3b756772e3cd8588b4666bb175faaabd0780b96300b10e17ccb3016b0ba5d9f020c7d976211ff398e7bebef718aa4d5f5";
      version = "0.2.0-alpha6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "aws-core/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "aws-core";
      groupId = "software.amazon.awssdk";
      sha512 = "52a565e3d1a16ef1fe3f7be41b0b3e4cbcf3eb93c4463368d67ed0299958659d4f2bf00633748ec1cb2f354f5dd9e6acb8535804de05b6fd5d6893bb9d1fe7a5";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-spi/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-spi";
      groupId = "org.apache.maven.resolver";
      sha512 = "2972b721213bfee654460468b2a2aa50546d7f1957be40d955728875af3a9801f8d78a2f796e832b9332d1f90ffb5ccb651289e7b5c8a175628b21b13594df43";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-slf4j18-impl/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-slf4j18-impl";
      groupId = "org.apache.logging.log4j";
      sha512 = "99eea70960abbe3f672cfdb9dd235bdfb4abc0ae0c9cf3b3ae95d91f5c61800639756a0412426696d92f2316980f2f178994dcd83d229c288df4207f996ba0ab";
      version = "2.17.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "http2-common/org.eclipse.jetty.http2";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "http2-common";
      groupId = "org.eclipse.jetty.http2";
      sha512 = "771a96b521e6f300433222470a4554efc00775ee819af75a4e5380da1b83039894e6d3a2ad324e43b48bffc681fe2ab3347755a300da3838d1f0fea9b3a7dba1";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "msgpack/org.msgpack";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "msgpack";
      groupId = "org.msgpack";
      sha512 = "a2741bed01f9c37ba3dbe6a7ab9ce936d36d4da97c35e215250ac89ac0851fc5948d83975ea6257d5dce1d43b6b5147254ecfb4b33f9bbdc489500b3ff060449";
      version = "0.6.12";
      
    };
    paths = [ src ];
  }

  rec {
    name = "j2objc-annotations/com.google.j2objc";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "j2objc-annotations";
      groupId = "com.google.j2objc";
      sha512 = "a4a0b58ffc2d9f9b516f571bcd0ac14e4d3eec15aacd6320a4a1a12045acce8c6081e8ce922c4e882221cedb2cc266399ab468487ae9a08124d65edc07ae30f0";
      version = "1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.csv/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.csv";
      groupId = "org.clojure";
      sha512 = "b039775a859ed27eca8f8ae74ccb6afde3ad1fe2b3cbe542240c324d60fe1237e495eb1300ee9eb4ff4ef59f01faf7aec6ef1dd6a025ee4fe556c1d91acfcf1b";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-clj/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-clj";
      groupId = "com.cognitect";
      sha512 = "efe5483c188c8e6fb7327e2b312424de920b913ec9ca89580fddceb2a964de4ce75aab79d7d3671bb362b9af73a9e25a331abd4f53ce544d9b50f83a1a07adf4";
      version = "1.0.324";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-classworlds/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-classworlds";
      groupId = "org.codehaus.plexus";
      sha512 = "6a58048d9db54e603b9cfd35373cf695b66dd860bec878c663b4fc53b6b3d44dd5b0c92e7603654911b1f78e63ef277cf6b272fe069a360989138550545f274d";
      version = "2.6.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "next.jdbc/com.github.seancorfield";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "next.jdbc";
      groupId = "com.github.seancorfield";
      sha512 = "a4a3d44d50ccc1d534eaed34c12bc9fabe9f2329e96a92c5a0f5020fa6bf1393dd2224058217488f8fa88738f3da7b2c316d5c724473f61f6ae4d5ece837e57a";
      version = "1.2.709";
      
    };
    paths = [ src ];
  }

  rec {
    name = "json-utils/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "json-utils";
      groupId = "software.amazon.awssdk";
      sha512 = "d2570758cc19657f958f75d9d36508687802161a187f0a9b66a2f84a69cf77d3bba548af26929a964ebc2f4262d588b20db48f9fac80330132c5410769d70d50";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-transport/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-transport";
      groupId = "io.netty";
      sha512 = "a2d4e31457cca06ef04854dece6f8845c8c2efcaef55892054722d5a695a1b31473b9d47fb90e4362babfddff32bd936f0124068a258b66a719227e54dbde424";
      version = "4.1.68.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm-commons/org.ow2.asm";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "asm-commons";
      groupId = "org.ow2.asm";
      sha512 = "68c21ff751756cdd4c01f8ca9be110be86e1e694b818b4958e489f3ed47d1a3b3c9210a1f14d078200b0fec5230f817a793551ad7a6dec84b7d948a234a12247";
      version = "9.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "auth/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "auth";
      groupId = "software.amazon.awssdk";
      sha512 = "63fef5856c38f21b06b2b1f3e3d951e5e3cdc5176da20597f1b6878eaa74b3b78f66f68a3c60a00ecc2ce22eb3a86ad2d315f5834f16011a126b1305a870e799";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "crypto-random/crypto-random";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-random";
      groupId = "crypto-random";
      sha512 = "3520df744f250dbe061d1a5d7a05b7143f3a67a4c3f9ad87b8044ee68a36a702a0bcb3a203e35d380899dd01c28e01988b0a7af914b942ccbe0c35c9bdb22e11";
      version = "1.2.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-transport-native-unix-common/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-transport-native-unix-common";
      groupId = "io.netty";
      sha512 = "da97ae017829532d407dc39e54700ddfdeb5d53607590efb5c0b1439791efe7f2888670c462b5bda9b8fde01d84f3c50fbdccbe9e01af4362f7ad7337b3da486";
      version = "4.1.68.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "http-client-spi/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "http-client-spi";
      groupId = "software.amazon.awssdk";
      sha512 = "0a37119bec5c0b2a544859c96a0eb799a7a2206bc111b23bc0ea445ea58bf96ea029e1a4fd19d39b04163f719f54db8b33cbbf4003624cbf2d582341d6f4acf8";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient_httpserver/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient_httpserver";
      groupId = "io.prometheus";
      sha512 = "3f09336782afeaed75dbfb1f08064e41dabe7285f32c85a0e77808031fe95c6ad5af1ab7340a01a069f3090fe7a23bbcbf72fccb901290075a7b38caaebad484";
      version = "0.9.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clj-yaml/clj-commons";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-yaml";
      groupId = "clj-commons";
      sha512 = "b6cfdd848431eff4df30cf27e644440c82b18a316d813d1ef620f80102d8d47973b33c9b6c46bc187c5800da939ef47cd0e43602e15c65c8f19e9abb82fb6d38";
      version = "0.7.107";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-codec-http/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-codec-http";
      groupId = "io.netty";
      sha512 = "2f39c8b332e64d9c76b3cc0feb122fd774910089822074ff68bad3530c88541131929a55838b579776d2fdaa7ec6d5c25942463ef4961ae84fe3c216aa129938";
      version = "4.1.68.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ring-codec/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-codec";
      groupId = "ring";
      sha512 = "38b9775a794831b8afd8d66991a75aa5910cd50952c9035866bf9cc01353810aedafbc3f35d8f9e56981ebf9e5c37c00b968759ed087d2855348b3f46d8d0487";
      version = "1.1.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-interpolation/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-interpolation";
      groupId = "org.codehaus.plexus";
      sha512 = "6c3b40442adf721d325ee9cbf935d758223a04b3bd8e0f3b60fdb652175c1ca65a6010f7ea8288617ffa73cb1f19d2737c79c403d343b285e0f9afb1729caa60";
      version = "1.26";
      
    };
    paths = [ src ];
  }

  rec {
    name = "httpclient/org.apache.httpcomponents";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "httpclient";
      groupId = "org.apache.httpcomponents";
      sha512 = "3567739186e551f84cad3e4b6b270c5b8b19aba297675a96bcdff3663ff7d20d188611d21f675fe5ff1bfd7d8ca31362070910d7b92ab1b699872a120aa6f089";
      version = "4.5.13";
      
    };
    paths = [ src ];
  }

  rec {
    name = "protocol-core/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "protocol-core";
      groupId = "software.amazon.awssdk";
      sha512 = "b6e7c587c96199fe7c126954646c9d8f48c0b33f665991b9e0c225964c70607cf348d61252a482d96f99a8e8cf74efd8bfff8b0fa468e58da76b6e52a365e55b";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.rrb-vector/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.rrb-vector";
      groupId = "org.clojure";
      sha512 = "7b6546bbd0ff8c7755382a5460029f57f562529ef66fc6ca473c4ba30d897ac5ff0aec8db737da9deeb732fccdd35c9c2317c256b7703e8e5804d1098e9bf77b";
      version = "0.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "crypto-equality/crypto-equality";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-equality";
      groupId = "crypto-equality";
      sha512 = "54cf3bd28f633665962bf6b41f5ccbf2634d0db210a739e10a7b12f635e13c7ef532efe1d5d8c0120bb46478bbd08000b179f4c2dd52123242dab79fea97d6a6";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "promesa/funcool";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "promesa";
      groupId = "funcool";
      sha512 = "7158b61538c58d673aa9f2b82a48b1abc99f5b1b87203d7e4475f9eb63a4f29745308ff01a532f91fb83c36d2e2ee21e37da26fcef757ff182ecfb0bd4237f9e";
      version = "6.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "checker-qual/org.checkerframework";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "checker-qual";
      groupId = "org.checkerframework";
      sha512 = "407d0ac59b02cbef7d93f25c8b287cd587232aa5ddfee6d2c7ba34d712565b0a5adfe52b5daa20d3e6c3ab1e7a5f8b08698078d9179185a1b35ada1eb92213bf";
      version = "3.5.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "java-http-clj/java-http-clj";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "java-http-clj";
      groupId = "java-http-clj";
      sha512 = "50b1037b9b33da63bcf9624eb0b778c6f6de50d7bb756eccb925235e18fd74de6f3e83ae243e072b4ae64d10a3fba151c8ffaaa006657d5c9b493eb9a04eb209";
      version = "0.4.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jna/net.java.dev.jna";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jna";
      groupId = "net.java.dev.jna";
      sha512 = "a380b303d5ece14b3a45dbac8d06e3f39fe5e09f3a5d08c161262c47a14326a9f5cbcdc56d6fabf6efcdb7449c4a2e43e696ec6c8c35730fb34a2993c6647948";
      version = "3.2.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "eventstream/software.amazon.eventstream";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "eventstream";
      groupId = "software.amazon.eventstream";
      sha512 = "461c7b63b3d39247af4073608e346b93d32502322136024868be3f7e40e71f348c3bef2450757b5dc8594ffd596f7af03ed69e4a383000bed8ac2a9e3f0cbe5d";
      version = "1.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "guice/com.google.inject";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "guice";
      groupId = "com.google.inject";
      sha512 = "78f17b090f34564db0fa6903c966e79d8002903d2604f9605a0d713e770a9c772c11d615a5e112dbb15464b9f8945edff6ac3d23ac84ccb08eb1657ec64d4442";
      version = "4.2.2";
      classifier = "no_aop";
    };
    paths = [ src ];
  }

  rec {
    name = "cheshire/cheshire";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cheshire";
      groupId = "cheshire";
      sha512 = "5b2a339f8d90951a80105729a080b841e0de671f576bfa164a78bccc08691d548cff6a7124224444f7b3a267c9aca69c18e347657f1d66e407167c9b5b8b52cb";
      version = "5.10.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-reactive-streams/com.typesafe.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-reactive-streams";
      groupId = "com.typesafe.netty";
      sha512 = "51a46a4ecfdf794553b1012c2ac80d9c6343c7a4990e3224514d08c2b6c41979cbee6883601f2f697926cca89558e24d3a13e0b8b0c3341947e220711dbefcbf";
      version = "2.0.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tigris/tigris";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tigris";
      groupId = "tigris";
      sha512 = "fdff4ef5e7175a973aaef98de4f37dee8e125fc711c495382e280aaf3e11341fe8925d52567ca60f3f1795511ade11bc23461c88959632dfae3cf50374d02bf6";
      version = "0.1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-client/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-client";
      groupId = "org.eclipse.jetty";
      sha512 = "f2d70900e345694638a1b969729e4b3c9a3a19a563a53b2c74f26d7f67225dd03d57746a184f4df01fedc86aa9e62b62ca8bbe30ac4492d256ade5753ea2e772";
      version = "9.4.44.v20210927";
      
    };
    paths = [ src ];
  }

  rec {
    name = "arns/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "arns";
      groupId = "software.amazon.awssdk";
      sha512 = "902f39f9f9099daccac9bfb4fa69fa66d634f0b9bc9736a9b840a246291f7a4f42a4b86e0261b2d3eb173dfb5245fbc30050ec8676e9a61d76b82494276dd2f9";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-jndi/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-jndi";
      groupId = "org.eclipse.jetty";
      sha512 = "f7c57ca71ed62e9853a569c65145fb51893c7ba2d7563cef174397a08d308312703a995ec1e8cea95504bf4b1958535b0eaa0f0b803bc0eae7f958e2e91de69a";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-io/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-io";
      groupId = "org.eclipse.jetty";
      sha512 = "ccfb25e99a116519597ffb6dd5159b922c0f7d8863f7ffd083cbd48b8feaa391f4db3c51a278c57fe4406afd852f3459cb357a3a93437faca1b81748ec28288e";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.reader/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.reader";
      groupId = "org.clojure";
      sha512 = "3481259c7a1eac719db2921e60173686726a0c2b65879d51a64d516a37f6120db8ffbb74b8bd273404285d7b25143ab5c7ced37e7c0eaf4ab1e44586ccd3c651";
      version = "1.3.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient_common/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient_common";
      groupId = "io.prometheus";
      sha512 = "b9eebbe200cedfae9de0c9d031abd1cf14af2c6b17cf9f040c05a661c07b98300afd52f0b88c1a8413433ea116e36a60c87a4c7ae11803ef7280be9e012d0283";
      version = "0.9.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "compliment/compliment";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "compliment";
      groupId = "compliment";
      sha512 = "0729cc214b5e60683d02073a6fd2a9f7de9d7e13768f16d4d61c64e986a3b5186e725568cb9ea66cf80a915a7bbb317b9cda76d9833a59496d205a3ff979cd5d";
      version = "0.3.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "dynapath/org.tcrawley";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "dynapath";
      groupId = "org.tcrawley";
      sha512 = "896fb4c7595117e95742715f96ac7f86e1009e6c7c0077a1e2b42450f38783578c7608d004ffd9cb9dbd6c008aeab41d58eb165e1ffa8b7eaddc9bc801ae78a0";
      version = "1.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reactive-streams/org.reactivestreams";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "reactive-streams";
      groupId = "org.reactivestreams";
      sha512 = "aafc86186d82b4f3bd44ef7f955978481172eab267d208aa80b24f8ca218bd902d69b587fcae2fe44a888b7a9f81fc5a209e837958307fdc0ee815248f7065f9";
      version = "1.0.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jline-terminal/org.jline";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jline-terminal";
      groupId = "org.jline";
      sha512 = "2389a8e84763868b3c0d4254557974ce4046e9d8e24301a4875b95f288e8792f8c9359a99fc7f3ed79bf3be09c29f27ad1dcbffa7c8f743f5361a314644eefb0";
      version = "3.5.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jsoup/org.jsoup";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jsoup";
      groupId = "org.jsoup";
      sha512 = "a0705121b33359ebfe2bbf747e46874dfc7b0bd090904acad34434185b34e52862c811e3b98f75f64ac104a4aabacb6fb5c762bdc57711d5bdf7c162d34b70db";
      version = "1.14.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-servlet-api/org.eclipse.jetty.toolchain";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-servlet-api";
      groupId = "org.eclipse.jetty.toolchain";
      sha512 = "758454d41cd0c08ec5b25c1e8ba7249fb11f753ea04c337614db9b99f2da9c1dd9a26bd0048aa6d1b95906d8aa67d0a9c719901b611d3017547adda9f7d4a289";
      version = "4.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "nippy/com.taoensso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "nippy";
      groupId = "com.taoensso";
      sha512 = "146aaf1b0d0a0f73d26125067b4549e9df1f66dc62aa5980f07b5586e03f55fa08ae0303c0b83d69fd989473a336cf7077da3686fccab8c7482c2bfa505a3bb9";
      version = "3.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.gitlibs/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.gitlibs";
      groupId = "org.clojure";
      sha512 = "9f2bfe18d5eea42cb09fee0d35e323ac5844c287e9073c2644c933fd89f41d64eca4d24a40e859a9cb7154da61e96550b39d52c766064cc0f7298f8a915b8f20";
      version = "2.4.172";
      
    };
    paths = [ src ];
  }

  rec {
    name = "antq/com.github.liquidz";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "antq";
      groupId = "com.github.liquidz";
      sha512 = "aefb509a061ec192fbe84ba3c204bcea2c436b4d78d829a0fa42aa7cb57a1c6778cbf32d3c7abe6cfd6c143d873c20defc4d402cb31179e350fe3a875e420708";
      version = "1.3.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ring-jetty9-adapter/info.sunng";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-jetty9-adapter";
      groupId = "info.sunng";
      sha512 = "3961d2803099218bfa724149a1451639904420aab1cdc91418e7d368f97f5b5c340c7605c33e8a1d442a4e303415e314cdb05a7dc5e2e45650d4cb9d1f925917";
      version = "0.15.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jline-reader/org.jline";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jline-reader";
      groupId = "org.jline";
      sha512 = "1cf3c039a40795052588c14fd318d9a3a58f4551929aeb7430e8ce1d16b8450ce5bdd335169f3e9ad9a01b3d92ed8fcad6a563e1970046744fbda1a49524c0ac";
      version = "3.5.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-resolver/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-resolver";
      groupId = "io.netty";
      sha512 = "b944c251b80b4f5efce03dc2e7149e19327764ca18b81e66d530e6853b1e0cfea809fb031982359af74d0f4193bb9b438c5fc307d53da59473c2d606e326497e";
      version = "4.1.68.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-connector-basic/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-connector-basic";
      groupId = "org.apache.maven.resolver";
      sha512 = "4554cea39910393557cc8769550c3a12ba64e0f57244f71a1c78a9cd3a6032ae9bbd2b43d4c15579b6b89a766a19d28619fd99eeaa1b4862fda549d8cc9e3610";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "metrics-spi/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "metrics-spi";
      groupId = "software.amazon.awssdk";
      sha512 = "3df1b08c124bdcadeea0aeb9d7c45782fcaa078604705c2c1e86828ab2d99ea11427b9f6a20b60b7f5922c65166c265ec75e5e962881d5baa8b98fabc599321d";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "s3/com.cognitect.aws";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "s3";
      groupId = "com.cognitect.aws";
      sha512 = "e0ddbd294be4de0f29878d26a399034a86f244fcfa527d944f21253f13d52a1181beccf1af43cba2789237bba92c3cc76030b104c9f7e730e7b62ac559e969ca";
      version = "814.2.991.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "utils/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "utils";
      groupId = "software.amazon.awssdk";
      sha512 = "dd38143e1c8e42870a3c424e7d89a0726b2285279fac8a93876a90570d549bb1ead713d9608caa6ba680b24271957fe73a1ca30b3138cf7badccd4331dd7b454";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-impl/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-impl";
      groupId = "org.apache.maven.resolver";
      sha512 = "ef011e67152290379da6db1ce256b70dc436eb1596d58c38ee5bf9df65fbe75ed2ddc7768f6c61901c8cb83af88c42ad0b7bf24ad1775949eb4522511825280d";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "slf4j-api/org.slf4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "slf4j-api";
      groupId = "org.slf4j";
      sha512 = "db7440b47e87215f9cc88c9521bce7a0f2ffa81b07e5f53c5f8afa90a0ab61168755ee6d136245461b57a01f0a857fe0d509c60baa7838c4eb6be1f885438049";
      version = "2.0.0-alpha1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-model/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-model";
      groupId = "org.apache.maven";
      sha512 = "4e7d3561e1c8c9bdf736aaf7115828ffcade3d1d0a009cc09787d93fc2505dadd71e771936f59a5f17e213b89799ed2d281a98aef56d6c6fa02720226a0b85f7";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "version-clj/version-clj";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "version-clj";
      groupId = "version-clj";
      sha512 = "f5eecd356d1206bdaae6cf400c386e06de0f4601828bb3a563d66108073cece0980978cbb171c38ff3e6a2fd46b592de9e29b26c9ed555db0d3b5c43c6ba806a";
      version = "2.0.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "buddy-sign/buddy";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "buddy-sign";
      groupId = "buddy";
      sha512 = "0fb04dfce4d746c0927c857fff617a1f2905051e97b2157c2656aa2655f9f0be2b3810fb16c3e1397a09e89533670d06b0b46814bc913ba2e382a390beeb8f8b";
      version = "3.4.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "closure-compiler-unshaded/com.google.javascript";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "closure-compiler-unshaded";
      groupId = "com.google.javascript";
      sha512 = "bfb6b12fcfde011a5cd26e12dc94dc8d0e2b5502922a2abc8b7952aa8ceabaf11fcff641e22e1e919ad913d6130cff9e829e87a006febc1683d4c91a0f22c437";
      version = "v20210202";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reactor-core/io.projectreactor";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "reactor-core";
      groupId = "io.projectreactor";
      sha512 = "a17cdc272e19b3b8b47639dda4d2aca8dbad571380228ee0717ef021c226276d817cb9fc35947d6ace9312528e42d979c2bd8076aa810a635bc7b88e184d92d2";
      version = "3.3.20.RELEASE";
      
    };
    paths = [ src ];
  }

  rec {
    name = "test.check/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "test.check";
      groupId = "org.clojure";
      sha512 = "b8d7a330b0b5514cd6a00c4382052fab51c3c9d3bc53133f8506791fa670e7c5ecd65094977ea5ced91f59623b0abd1ab8feeec96d63c5c6e459b265a655c577";
      version = "1.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "org.eclipse.sisu.inject/org.eclipse.sisu";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "org.eclipse.sisu.inject";
      groupId = "org.eclipse.sisu";
      sha512 = "f4790768c0d958b3429a3241abb15f9bb6e2fd7f43a5e034dde6a3a6820e6941c00f10ad084d5c38f8edc144e7acbea7ba3dc8952f01dab41e443803db2a4efc";
      version = "0.3.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-util/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-util";
      groupId = "org.apache.maven.resolver";
      sha512 = "45bd05eee2e2e606155916ec06efdb62e4a147af7ed0bb0b443b2a71b72576fec8e0ced0eee3ae3c86778198de227c1c7fe5d423cff0b96ba382fb563239694a";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm-analysis/org.ow2.asm";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "asm-analysis";
      groupId = "org.ow2.asm";
      sha512 = "236729bfae1bd1c3f2c2707bbc9967699e03d72ae5b1f284832ae928e7eefcfd1eeb6c31eb11ce6272d9b4ce4fdc91779edb9febe98a72f0f4d71356c028d4ea";
      version = "9.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-api/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-api";
      groupId = "org.apache.logging.log4j";
      sha512 = "6391788510d015ae2d94527b942cf49a9518e8628932e0a08a1d8a46297499f9cd8a81f7dd99409f69beb06e844f9fc33b6c5c403786202cb3face9e182a5496";
      version = "2.17.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-nio-client/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-nio-client";
      groupId = "software.amazon.awssdk";
      sha512 = "9318ec432aa316142ce77ee53210d1d91d53817d3c443c734304fb26dbdb88fafd2a733a685451741d159c898fea1c7a10ed2f65f847a9dfc127aff82734d98c";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "mockery/mockery";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "mockery";
      groupId = "mockery";
      sha512 = "86c9e9c8408fbc8c3e971f14d5c6bdf03d09aeaebc80819ed96a639da54fe63c82382f2fa7e15297352a361e21399a5a6e59d23ffc92f1f09692f552dfa2d5de";
      version = "0.1.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jakarta.activation/com.sun.activation";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jakarta.activation";
      groupId = "com.sun.activation";
      sha512 = "d1c214d2d6ecc61bba396d913c66c977418e74dfe96e5558951ccf99a60cfca6adfea3fc64b6e2d15f698e30dac870b8f6e8d7a22e0dff975f8dd83864714fc5";
      version = "2.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jsonista/metosin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jsonista";
      groupId = "metosin";
      sha512 = "ce5c8d67b276920969580b2af06b2c448deb909373cdeb7b871125a6fd424faa952cb5dc8c29e73553858c74a0ecf199f77827148ef8d5f3cd0d6d10a5c5fee1";
      version = "0.3.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "uri/lambdaisland";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "uri";
      groupId = "lambdaisland";
      sha512 = "da7e5accad438283e203f62506a7ef3990bcb8fc22989683c6daf6d88ed7bffb04e16b94f0290d44807a06dbebc343366c09f25cd8b9fcb6da3900c4657a7659";
      version = "1.4.70";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ring-servlet/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-servlet";
      groupId = "ring";
      sha512 = "a87164834e97ce37675f129baa34bfaf8c4563c6daa5dfa6fd1abc9ebf92cf45920274455912af24bef3e26ff72eef1d778034992e7831fcde34d5f7d845bc56";
      version = "1.9.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.memoize/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.memoize";
      groupId = "org.clojure";
      sha512 = "67196537084b7cc34a01454d2a3b72de3fddce081b72d7a6dc1592d269a6c2728b79630bd2d52c1bf2d2f903c12add6f23df954c02ef8237f240d7394ccc3dde";
      version = "1.0.253";
      
    };
    paths = [ src ];
  }

  rec {
    name = "hawk/hawk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "hawk";
      groupId = "hawk";
      sha512 = "617ef041b7ef98c96395fd997a0f5f5028db267c4eac367c47a306405ea1eb825f826e42be8aa4462f753d264c52496e39854e4061e9ee40712dde2f57aa9efe";
      version = "0.2.11";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clj-diff/tech.droit";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-diff";
      groupId = "tech.droit";
      sha512 = "7da0e6142793044fd0ca81fca9c169b9a8e076f6642fda6d68d42cb0021bc2442d6e4c8335dd29e745d4f026763380d199b8d5e21e51659f87ad24872090960b";
      version = "1.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "camel-snake-kebab/camel-snake-kebab";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "camel-snake-kebab";
      groupId = "camel-snake-kebab";
      sha512 = "589d34b500560b7113760a16bfb6f0ccd8f162a1ce8c9bc829495432159ba9c95aebf6bc43aa126237a0525806a205a05f9910122074902b659e7fd151d176b1";
      version = "0.4.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-repository-metadata/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-repository-metadata";
      groupId = "org.apache.maven";
      sha512 = "0ad9b30c7d739bcfc02ce9bdfab0fa9f33497818513287900fcf5525231c76e0b0ff4f0a13246a896d85e872a2a8fbb28551dd306604cb930c7850c1837a3930";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "unboundid-ldapsdk/com.unboundid";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "unboundid-ldapsdk";
      groupId = "com.unboundid";
      sha512 = "7e7ad070d968fc4383a13f0206c1774330922412c1115d4dae240b223fb55a05e739a41069ec7cf3ae2f95406974d83fa48516c7c024369d828ccc8c6db75c8c";
      version = "5.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.priority-map/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.priority-map";
      groupId = "org.clojure";
      sha512 = "bb8bc5dbfd3738c36b99a51880ac3f1381d6564e67601549ef5e7ae2b900e53cdcdfb8d0fa4bf32fb8ebc4de89d954bfa3ab7e8a1122bc34ee5073c7c707ac13";
      version = "1.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "java.data/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "java.data";
      groupId = "org.clojure";
      sha512 = "b9cbd9dd1699d7f767bcffd36b240f26f900f7536451f2ae276058d3c5982cb72089c98b6cdffb287ab7d7446364cfdfcec8fdda432e568c8794d4e4eefcbb1c";
      version = "1.0.86";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jakarta.mail/com.sun.mail";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jakarta.mail";
      groupId = "com.sun.mail";
      sha512 = "364b705fe3e51b1a612f7812cd4e57cff3b6ed844ca3566c206195d6512664661b0fcc138ecd2284ee33855fa378a4296842668fc66e3447d5dc5a1fc3e9c43d";
      version = "2.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-server/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-server";
      groupId = "org.eclipse.jetty";
      sha512 = "b8655ef10b080571449b21a1769fb214f43711da8122ba1d62dba0f763fdce4ed0a34264c3b9a21e44a046c0400cc37bad3c5dc36c63515861d7956edb1eba68";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "aopalliance/aopalliance";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "aopalliance";
      groupId = "aopalliance";
      sha512 = "3f44a932d8c00cfeee2eb057bcd7c301a2d029063e0a916e1e20b3aec4877d19d67a2fd8aaf58fa2d5a00133d1602128a7f50912ffb6cabc7b0fdc7fbda3f8a1";
      version = "1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-builder-support/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-builder-support";
      groupId = "org.apache.maven";
      sha512 = "8d52795747fbc664901422982f2281592eca8b0222dcdc27d4135fb63b2494af96928f9096eff33a4b843fc1937702aae190011c2e825598d5ecb28343fa34e7";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jsr305/com.google.code.findbugs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jsr305";
      groupId = "com.google.code.findbugs";
      sha512 = "bb09db62919a50fa5b55906013be6ca4fc7acb2e87455fac5eaf9ede2e41ce8bbafc0e5a385a561264ea4cd71bbbd3ef5a45e02d63277a201d06a0ae1636f804";
      version = "3.0.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ring-core/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-core";
      groupId = "ring";
      sha512 = "38d7214a3fc1b80ab55999036638dd1971272e01bec4cb8e0ee0a4aa83f51b8c41ba8a5850b0660227f067d2f9c6d75c0c0737725ea02762bbf8d192dc72febe";
      version = "1.9.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.cache/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.cache";
      groupId = "org.clojure";
      sha512 = "0a07ceffc2fa3a536b23773eefc7ef5e1108913b93c3a5416116a6566de76dd5c218f3fb0cc19415cbaa8843838de310b76282f20bf1fc3467006c9ec373667e";
      version = "1.0.225";
      
    };
    paths = [ src ];
  }

  rec {
    name = "meta-merge/meta-merge";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "meta-merge";
      groupId = "meta-merge";
      sha512 = "079339d69a18e88a7cf5ce37e29bf7d9b25c93011866fac3012b11444f9e3d69f4dc017a3e88ad20faa790b38e343e0b71e9e11c44028434da3f368f377e4458";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm-tree/org.ow2.asm";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "asm-tree";
      groupId = "org.ow2.asm";
      sha512 = "2e7c7e2453b4453db83aa5f13a7a9ec9fa7896d3b13670b171f6e8f186f3ec2f382a985c69018a510ea1b14a2e986f00e1bd3dd6e77a59a28f82b7fbe738916d";
      version = "9.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "rewrite-cljs/rewrite-cljs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "rewrite-cljs";
      groupId = "rewrite-cljs";
      sha512 = "fbf678ff7828ffa8e930730fa28c2149380f80d3c9dab69a5fbdcadb2b47c609df3f43fa992f546e900d6143ef92f44e076402dfd702cf64a0a538b29a34220b";
      version = "0.4.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-plugin-api/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-plugin-api";
      groupId = "org.apache.maven";
      sha512 = "82a12b14c96c8b041647763d8d7d6b1d43c0d726d3810b67d4bacff3663ba39d782d49edd4fb7df50fbd83b5cdd0674981ff8aebc324406fd5b00163050a2fa0";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.async/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.async";
      groupId = "org.clojure";
      sha512 = "160a77da25382d7c257eee56cfe83538620576a331e025a2d672fc26d9f04e606666032395f3c2e26247c782544816a5862348f3a921b1ffffcd309c62ac64f5";
      version = "1.5.648";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-dataformat-smile/com.fasterxml.jackson.dataformat";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-dataformat-smile";
      groupId = "com.fasterxml.jackson.dataformat";
      sha512 = "8998346f7039df868f3387d219efa0c04fc022a948d098296f3d7ac3f7a9a82bde6ec4a8f83b11994ad50318b5aca37781faacb1f20a65ba2ecc6d6d6eb9468e";
      version = "2.10.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-datatype-jsr310/com.fasterxml.jackson.datatype";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-datatype-jsr310";
      groupId = "com.fasterxml.jackson.datatype";
      sha512 = "5e94b811785c715f6d115edec150054a154aa67b2b497569a05a764df42a0d93db2b943d6c076b0cec0c6abd142eaabe411a77a6b397bf08f694629c31914748";
      version = "2.12.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-artifact/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-artifact";
      groupId = "org.apache.maven";
      sha512 = "305174de2499cc68491864c27bd51c1cf91d9bba4e22722a200a60f44864855ea782cde90d5e1b923518e8ae8250245e92e1e4f5f55dc6fbb25430a2ee04c7c8";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.codec/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.codec";
      groupId = "org.clojure";
      sha512 = "c324b62a5f14b2f17e49f1b0fffa3f44d195cb5261e03c5e472ba4f2972135f4b06fd321c0887717c727f025fc1a0121283d16fbf923d7469856702614a288f3";
      version = "0.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jaxb-api/javax.xml.bind";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jaxb-api";
      groupId = "javax.xml.bind";
      sha512 = "0c5bfc2c9f655bf5e6d596e0c196dcb9344d6dc78bf774207c8f8b6be59f69addf2b3121e81491983eff648dfbd55002b9878132de190825dad3ef3a1265b367";
      version = "2.3.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "gson/com.google.code.gson";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "gson";
      groupId = "com.google.code.gson";
      sha512 = "5dd7214c542a7b93aab3eab0ba13e4ac3d6ddb05c795fb6d3992e21925a98dce87cb186ac67b4d3ad146f96e14d38b3892837eca57a27b4e845aca6d4e4f708a";
      version = "2.8.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "annotations/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "annotations";
      groupId = "software.amazon.awssdk";
      sha512 = "3d61b8c49237a5114a956f59bdd116cc50d18444ef45d4c2f82612d0b2738e2b58afe79dc28d58aa9d6943de6cbda99af242a5e8cbb9cb060f5165a586656c4a";
      version = "2.17.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-alpn-server/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-alpn-server";
      groupId = "org.eclipse.jetty";
      sha512 = "2a7ef1ebf2a8ccd3298f28eab5fd46554ed74c515d74bebb8e8208dc86db6a3e758eecb2f349360a164c1bfef19c2dbab9ad09ac447a9fbe4878e60266bb38ff";
      version = "10.0.6";
      
    };
    paths = [ src ];
  }

  ];
  }
  