# generated by clj2nix-1.1.0-rc
{ fetchMavenArtifact, fetchgit, lib }:

let repos = [
        "https://repo1.maven.org/maven2/"
        "https://repo.clojars.org/" ];

  in rec {
      makePaths = {extraClasspaths ? []}:
        if (builtins.typeOf extraClasspaths != "list")
        then builtins.throw "extraClasspaths must be of type 'list'!"
        else (lib.concatMap (dep:
          builtins.map (path:
            if builtins.isString path then
              path
            else if builtins.hasAttr "jar" path then
              path.jar
            else if builtins.hasAttr "outPath" path then
              path.outPath
            else
              path
            )
          dep.paths)
        packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}:
       if (builtins.typeOf extraClasspaths != "list")
       then builtins.throw "extraClasspaths must be of type 'list'!"
       else builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});
      packageSources = builtins.map (dep: dep.src) packages;
      packages = [
  rec {
    name = "transit-java/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-java";
      groupId = "com.cognitect";
      sha512 = "660d4f034af67793ec53f00c661e57dd94817a3d1ab978163fe6289e06f16fe3f8431496c8e4eff1b9729cc2c47e906b6afb933605034fc2b64829c33fb47d99";
      version = "1.0.343";
      
    };
    paths = [ src ];
  }

  rec {
    name = "javax.inject/javax.inject";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javax.inject";
      groupId = "javax.inject";
      sha512 = "e126b7ccf3e42fd1984a0beef1004a7269a337c202e59e04e8e2af714280d2f2d8d2ba5e6f59481b8dcd34aaf35c966a688d0b48ec7e96f102c274dc0d3b381e";
      version = "1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "bcprov-jdk15on/org.bouncycastle";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "bcprov-jdk15on";
      groupId = "org.bouncycastle";
      sha512 = "7dccfc636ee4df1487615818cfa99c69941081df95e8ef1eaf4bca165594dff9547e3774fd70de3418abace77d2c45889f70bcd2e6823f8539f359e68eaf36d1";
      version = "1.70";
      
    };
    paths = [ src ];
  }

  rec {
    name = "buddy-core/buddy";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "buddy-core";
      groupId = "buddy";
      sha512 = "add57d2fc5e82fe2d7ec483551429a772c1699fc6de8e5678375194d58d52057332dbaaea4c7ad49d99abe28c7d5191a9776c3adf46ea43bcb4f6e651b844382";
      version = "1.10.413";
      
    };
    paths = [ src ];
  }

  rec {
    name = "selmer/selmer";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "selmer";
      groupId = "selmer";
      sha512 = "8c71553e8ec3b5571bd5cda98ea8d5975991c22282b2b0ff65bc4dd3ca0814481569a792728b8d863e3e9a1765f18b2393e3c204736e197fe51261afbf03c904";
      version = "1.12.50";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.json/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.json";
      groupId = "org.clojure";
      sha512 = "04b7c0c90cb26d643a0b3e7e1ffa2d2d423e977c1454ee5ea7c2e75547ecbc113838df17b797902a975f5ea2184a81a45b605a4d82970805e2bbb02feebc578d";
      version = "2.4.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "lz4-java/org.lz4";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "lz4-java";
      groupId = "org.lz4";
      sha512 = "98d59086a6021ca571d9c1d64b715e43044c730e1ac563f514c40cf44302615d30378b6d5cc69990446522de6260dc8e7b303e3990a3139dc326d058dfb6dbd9";
      version = "1.8.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clojure/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "4bb567b9262d998f554f44e677a8628b96e919bc8bcfb28ab2e80d9810f8adf8f13a8898142425d92f3515e58c57b16782cff12ba1b5ffb38b7d0ccd13d99bbc";
      version = "1.10.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "profiles/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "profiles";
      groupId = "software.amazon.awssdk";
      sha512 = "f3d3e50cf89c4bb9ef360411c7151f3f118619c4f2b84184a1303f592e1b417cde3d3b92a903f35628caa03771c46b2409947a5911d75cb8b2dd637468f53a14";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "joda-time/joda-time";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "joda-time";
      groupId = "joda-time";
      sha512 = "0d3993b75476050b876e5ead8a85b6db04a5cc586bd4011375b529cfac740a76b268839f5b82c3acc894fca1b583c2d6837f466b224bc262dd6db105d6b2c40d";
      version = "2.9.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-codec/commons-codec";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-codec";
      groupId = "commons-codec";
      sha512 = "da30a716770795fce390e4dd340a8b728f220c6572383ffef55bd5839655d5611fcc06128b2144f6cdcb36f53072a12ec80b04afee787665e7ad0b6e888a6787";
      version = "1.15";
      
    };
    paths = [ src ];
  }

  rec {
    name = "dependency/weavejester";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "dependency";
      groupId = "weavejester";
      sha512 = "ad4c19339b54da3156dab22998ed1aed8995c1e1f682dc42b04e1fb6950aa72d070f364ea36fd20db8e7b75a101c66d54857c4406f55fed60ea5d23a631fd34b";
      version = "0.2.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "api/com.cognitect.aws";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "api";
      groupId = "com.cognitect.aws";
      sha512 = "4592ac413b3ac3dd26d95ce42ba616cfcd97365c10eb86a05414a3c738f39c22b959c70824dbf062d0516f1c5ff4f55fb57eb689ec1c75749f157bd8d21e6e9f";
      version = "0.8.539";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.analyzer/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.analyzer";
      groupId = "org.clojure";
      sha512 = "c51752a714848247b05c6f98b54276b4fe8fd44b3d970070b0f30cd755ac6656030fd8943a1ffd08279af8eeff160365be47791e48f05ac9cc2488b6e2dfe504";
      version = "1.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "criterium/criterium";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "criterium";
      groupId = "criterium";
      sha512 = "e3ed38fa5f02f42a78691453a1f0a19f6c742417047ed84ca9c75fe69557dcd0ab2202011bae080ecd56bd105c97631bae1f9a3a659a716e3bcd0e4c7b53cdb9";
      version = "0.4.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-xml/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-xml";
      groupId = "org.eclipse.jetty";
      sha512 = "8bfb9669b86b48224f965584d6b56c9f999334708a7a749ba642d963ce057db67a973b1960185a30a434689890a7d6afdd581edd2adb5b1a6034943e31042cc2";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "HikariCP/com.zaxxer";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "HikariCP";
      groupId = "com.zaxxer";
      sha512 = "0a932d8c1083d3ba8eb6e004aa1783cc3f6df7424666f1d61ca6606715afbbb3da20bc0b61efd91bb3162f8092100ddad5e90fe019f818c89cc69a8d8d0bd5d5";
      version = "5.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-servlet/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-servlet";
      groupId = "org.eclipse.jetty";
      sha512 = "4fcaa3c37599223b90f564f20a16bac27a08e9e2b2733144a5140b7781b3926381729b38b1ed6a5a2f866fc7141ac07c62ef5d59d4ebc9201deede8e5aceceec";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-component-annotations/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-component-annotations";
      groupId = "org.codehaus.plexus";
      sha512 = "cc534fda54272f074fe9edd581a6c3e1ea98127340c7f852c4b4953a44dad048ace22dfa10f30d6adcdfc15efd319dac778a03ebbe20de7779fd1df640506e88";
      version = "2.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "endpoints/com.cognitect.aws";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "endpoints";
      groupId = "com.cognitect.aws";
      sha512 = "7e5c08319fd3c79630dbf67299906efbf2e4e4aa555d612b288ac49dbc44e702b27bce236fb691072947655bb76a04eff6fc4cfec9000f7d522ab4a0c0cf11ff";
      version = "1.1.12.129";
      
    };
    paths = [ src ];
  }

  rec {
    name = "error_prone_annotations/com.google.errorprone";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "error_prone_annotations";
      groupId = "com.google.errorprone";
      sha512 = "bd2135cc9eb2c652658a2814ec9c565fa3e071d4cff590cbe17b853885c78c9f84c1b7b24ba736f4f30ed8cec60a6af983827fcbed61ff142f27ac808e97fc6b";
      version = "2.1.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient";
      groupId = "io.prometheus";
      sha512 = "294c6fd0a5bfd674a8014c313198bea1d5296a52096b0620f9e0e2e4c8b5a12f1c7cc2b08505fc6c1a69a62e2c292c285ae136f467ff459ffee0401e0fcb9e18";
      version = "0.14.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-lang3/org.apache.commons";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-lang3";
      groupId = "org.apache.commons";
      sha512 = "fb0fe98385496a565678a000c26a3245082abfbf879cc29a35112b4bf18c966697a7a63bb1fd2fae4a42512cd3de5a2e6dc9d1df4a4058332a6ddeae06cdf667";
      version = "3.8.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.logging/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.logging";
      groupId = "org.clojure";
      sha512 = "c7a5959ad990003962628b9ee47d0c89b728d7d7718a145806de1eb0df7799df916bcc12cc7a1ecd71613e298cea435b0b59c52fef79f4553f22f835d67d9e9d";
      version = "1.2.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "aws-query-protocol/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "aws-query-protocol";
      groupId = "software.amazon.awssdk";
      sha512 = "76e225d5410b23654548db7ca9ac5845bacb40d27dd8011218c34edec97e58ce8b01fe4770f4365cbe72b7fb4af3003b42f3d8153f2797cb39ce85ae12ec0e24";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.specs.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "c1d2a740963896d97cd6b9a8c3dcdcc84459ea66b44170c05b8923e5fbb731b4b292b217ed3447bbc9e744c9a496552f77a6c38aea232e5e69f8faa627dea4b5";
      version = "0.2.56";
      
    };
    paths = [ src ];
  }

  rec {
    name = "websocket-jetty-api/org.eclipse.jetty.websocket";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "websocket-jetty-api";
      groupId = "org.eclipse.jetty.websocket";
      sha512 = "3a70fd06fdabd44cf2f36a69a7dd48cd7ed26887ddcdc40c7873a8eff5bec44bfcfc992a8e030ca621aa5539c6d06f83c1f894bed5067f669a140a6ae86914a9";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "xz/org.tukaani";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "xz";
      groupId = "org.tukaani";
      sha512 = "8cf42ae7d57c2115b9d86dc22eb782f0e0b3348a3927d013ef6a04cf444074592a4614f5e43328f6a55560b90945381a697fa01c47faf54be5b0ef202472ad0d";
      version = "1.8";
      
    };
    paths = [ src ];
  }

  rec {
    name = "websocket-jetty-common/org.eclipse.jetty.websocket";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "websocket-jetty-common";
      groupId = "org.eclipse.jetty.websocket";
      sha512 = "8e0ba83f677198f9acff347250dca2ff98027a7b8113d5d5a88d1433a492f28d4930c68e726550e346124cc0c0adee6fe52d771e035a1550bc1da28ff7e7dcc4";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "javax.annotation-api/javax.annotation";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javax.annotation-api";
      groupId = "javax.annotation";
      sha512 = "2453330b27a0822bba440c28b98ae1d83d60d97dfa2d040562dd5126b3548e0caa040fea3b886ac6feb0a858e6c1bc45b6c5472b180f1f14792e5ca33e355959";
      version = "1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "bcpkix-jdk15on/org.bouncycastle";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "bcpkix-jdk15on";
      groupId = "org.bouncycastle";
      sha512 = "477001e9556cdbe7fe9eca0c35b3ce29cd6b4d9cd5e13d1f44e3da6433d56a18e23f3679603a23730d78a93bd401113b804562c8bacb1e745e7944127f7afa4c";
      version = "1.70";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-common/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-common";
      groupId = "io.netty";
      sha512 = "9911e9cca2612a602f14e33748a657f54fa9187abe2b3274f12815d202490ad6b57e8ce26d1c181dedced19a4e9345dc32025e4624a0344f8e220ad255bddcd9";
      version = "4.1.72.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient_jetty/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient_jetty";
      groupId = "io.prometheus";
      sha512 = "6dbedc539903e61ddc9852d20e8fbd037d7e99e6921b8edfe89d29ddd45bef80e342cfc229e65b4c542b6f31efcec16b5b4e7902f2c423df1f241f321b8d8061";
      version = "0.14.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jeromq/org.zeromq";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jeromq";
      groupId = "org.zeromq";
      sha512 = "bd502d345926160b1a09e45f60eb81254dc67d6d9d7b79e025c08018dd16a18d32ff85b2440c352d530e61c96cd3b2d88fee2a8a912b436015ed31039e308ff4";
      version = "0.5.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clj-ldap/org.clojars.pntblnk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-ldap";
      groupId = "org.clojars.pntblnk";
      sha512 = "78240d3e0b6a57b9c9cac1ebc1c2fc55299aea482b650abf4be6f5cadaa9ed176b0f1a04d2c944fdb1eccb7968696cc318f115256615d849b6546a1156c682f4";
      version = "0.0.17";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-databind/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-databind";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "924977f62714ee24ef25ac8c1321df4adb09cd817505a794b52d6057a1b50e38b09b1aaaa4c5aa3960730b94dd83e369079fd87ddfde1146f4e36a76e4e6ed07";
      version = "2.13.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "expound/expound";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "expound";
      groupId = "expound";
      sha512 = "810832065897f33fd105aaf84984ee994ec5d90fe60d1a772b083bc2b1c59ff8e9e368bc0f456468824a65694f58cd47149f40b95488947ec5e5e96b44d44d1d";
      version = "0.9.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "spec.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "0740dc3a755530f52e32d27139a9ebfd7cbdb8d4351c820de8d510fe2d52a98acd6e4dfc004566ede3d426e52ec98accdca1156965218f269e60dd1cd4242a73";
      version = "0.2.194";
      
    };
    paths = [ src ];
  }

  rec {
    name = "apache-client/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "apache-client";
      groupId = "software.amazon.awssdk";
      sha512 = "9ecde1b99093eebf413931e7d9160be189aa4b594fecc75cace23e6dfef383ee7e4d81a5170cf5f9d07f6dfe862615366aaa377f0c45858629c295831ff13396";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.cli/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.cli";
      groupId = "org.clojure";
      sha512 = "1d88aa03eb6a664bf2c0ce22c45e7296d54d716e29b11904115be80ea1661623cf3e81fc222d164047058239010eb678af92ffedc7c3006475cceb59f3b21265";
      version = "1.0.206";
      
    };
    paths = [ src ];
  }

  rec {
    name = "http2-server/org.eclipse.jetty.http2";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "http2-server";
      groupId = "org.eclipse.jetty.http2";
      sha512 = "d4a75c7269c92e0c4609fc75e22c0ef8ecdc30f05edcdda92512357f307789455c80ac815c2f8a9777bd19cf97cf994c456f6c2624b5fddf0829f34c4c224ad6";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clj-uuid/danlentz";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-uuid";
      groupId = "danlentz";
      sha512 = "10c0ba460baadda446b1291423185e25e5a1bd82eb3ed82b0ee589f3e15bbe3f3a2c679767c228e01316ef27aaf60b7c1bceacef78f5604b7a11efe99207c227";
      version = "0.1.9";
      
    };
    paths = [ src ];
  }

  rec {
    name = "lettuce-core/io.lettuce";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "lettuce-core";
      groupId = "io.lettuce";
      sha512 = "3c9fed01f96286845adefe6dbe546666020ecca728bdd670db82afde3d3c42d7cf6b80acb5de356679ee177360e02edb290ebbc0a3a68a42f259604188dcd959";
      version = "6.1.6.RELEASE";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-fileupload/commons-fileupload";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-fileupload";
      groupId = "commons-fileupload";
      sha512 = "a8780b7dd7ab68f9e1df38e77a5207c45ff50ec53d8b1476570d069edc8f59e52fb1d0fc534d7e513ac5a01b385ba73c320794c82369a72bd6d817a3b3b21f39";
      version = "1.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "s3/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "s3";
      groupId = "software.amazon.awssdk";
      sha512 = "a026b6bf9461bdd8ddd212c8dd67767d12776bc1f08b160fd208fbc14407a70d4110fd1c638dccb1f9dd08807f413851b1b96d68fc254a00b1aab3861c73ca69";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "im4java/org.im4java";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "im4java";
      groupId = "org.im4java";
      sha512 = "9e5e68e71f07a8a5ecee344df3f6da27d19cd14b308ef2b89826e4aec5e3f4637c8bafde44379fb28c09356b5cb3b2f9e10c1b30aa5c695cb6c4aa5b486f4dc7";
      version = "1.4.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "animal-sniffer-annotations/org.codehaus.mojo";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "animal-sniffer-annotations";
      groupId = "org.codehaus.mojo";
      sha512 = "9e5e3ea9e06e0ac9463869fd0e08ed38f7042784995a7b50c9bfd7f692a53f0e1430b9e1367dc772d0d4eafe5fd2beabbcc60da5008bd792f9e7ec8436c0f136";
      version = "1.14";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jakarta.transaction-api/jakarta.transaction";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jakarta.transaction-api";
      groupId = "jakarta.transaction";
      sha512 = "764ade8ba807682dcd1ec7382c35275f3d8ab09a03d5b45c48e732501190e2738269080aaf28aa8dd656c11ee84bfb7dae6953dd2768f2acecd3a8cf0ca4961e";
      version = "1.3.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-http/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-http";
      groupId = "org.eclipse.jetty";
      sha512 = "47854b76c3dfa1d359a5c4aa475d7aa4fa166881437e8b421791e09230865eabb963496c07f699cd08f866ce2b05bcba25e906c0d6ceeca13b1d4e1edc107e4e";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-util/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-util";
      groupId = "org.eclipse.jetty";
      sha512 = "0ee699e93fe096aeae9677b5b4d3ac4731c8170547a1dcb54bc9b5796b62ffdb4a621dbd56c6ec00315feb536b9788f29024f39b251f5c4845b97f90e88aae01";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "encore/com.taoensso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "encore";
      groupId = "com.taoensso";
      sha512 = "52649b4099427ebc13c82f46385ef34a5f3a2134900599c8eebf2532b0d47e967384c84be4348320ab5d6ee8d1c85a525a7d4b86c00c695d519ba8b62492dd0c";
      version = "3.9.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.zip/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.zip";
      groupId = "org.clojure";
      sha512 = "c8292624d89ad67c336230870bffcdb19c018e0607ad76cf52c6ec2975791b22a08a8d840d36135edbda78c67c6d1d1e39d3024820598c932efda7d3dfc3e46f";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jcl-over-slf4j/org.slf4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jcl-over-slf4j";
      groupId = "org.slf4j";
      sha512 = "aed539305114718bd76da54f29a391362eb331108d9c033956bf68df29c62a44874c73ae39d19a25342625b6092326d39b4d8720aed6c62234a234e0855b00b5";
      version = "1.7.30";
      
    };
    paths = [ src ];
  }

  (rec {
    name = "io.github.cognitect-labs/test-runner";
    src = fetchgit {
      name = "test-runner";
      url = "https://github.com/cognitect-labs/test-runner.git";
      rev = "48c3c67f98362ba1e20526db4eeb6996209c050a";
      sha256 = "14f47q9gz77y4jv848hqszn1rxw3k2rlrvh9sam5cyw0rm5pz7rm";
    };
    paths = map (path: src + path) [
      "/src"
    ];
  })

  rec {
    name = "tools.analyzer.jvm/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.analyzer.jvm";
      groupId = "org.clojure";
      sha512 = "36ad50a7a79c47dea16032fc4b927bd7b56b8bedcbd20cc9c1b9c85edede3a455369b8806509b56a48457dcd32e1f708f74228bce2b4492bd6ff6fc4f1219d56";
      version = "1.2.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-codec-http2/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-codec-http2";
      groupId = "io.netty";
      sha512 = "d6ee6a3d716f681bc81e1feba1359dbb42863a5d31844f692035a5c2394d7f29b1bc1ba526459e11a656152b7f00eccdb013ff15d61d35fd16e278ef2b9bbcf0";
      version = "4.1.72.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient_tracer_otel/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient_tracer_otel";
      groupId = "io.prometheus";
      sha512 = "3d05f19dad72fb05a81e14f22dc511c8d97df771608579b6687948bd0be8dc4b679afbe710b8d159d8024ed931a32e9cc0140a43318ceb1852ec04c7d51cebe4";
      version = "0.14.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-codec/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-codec";
      groupId = "io.netty";
      sha512 = "53ad477a34c6f8e4efda220f10575d8ac7e0b9d27bfca9814e6160a1626d3b955b9fae8091a531ad968bbee2f8ffe5ab5efc5e2c5aec099a5fbec4296edc8c0b";
      version = "4.1.72.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "zstd-jni/com.github.luben";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "zstd-jni";
      groupId = "com.github.luben";
      sha512 = "92174059714b98d4275dca1b057c857766267afe6ae2b27bfdfe50395cb90a3ec973032977a074c5ce516a3769336e6bf63d3bbde95bea165c409f1c990a651d";
      version = "1.5.2-1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-transport-classes-epoll/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-transport-classes-epoll";
      groupId = "io.netty";
      sha512 = "2590ade253c5022dcb6f3ffd66aaaa44174128124675159d9f8ce4d47bd38fdcb8fe6c9954f669229e482a11efbb7725f1916626fcb4a54df5e4ebcd86e23527";
      version = "4.1.72.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-jul/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-jul";
      groupId = "org.apache.logging.log4j";
      sha512 = "409f06962f1155f89a8b27fc51f98abb89a839bd3bc9e68069807e11eaa64a2934dced23b196c27287420780f54772f1ae8d0f45fc64527f0d2c0acf617088b2";
      version = "2.17.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-annotations/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-annotations";
      groupId = "org.eclipse.jetty";
      sha512 = "5b64266dae1d9038556bcdc2452552581d27e61121b1face8af9495d13c1306a53a38f181a1dfdfb376c3da75e593abd2e02b191e6d02a4f5fe3ebaf94eb698c";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "third-party-jackson-core/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "third-party-jackson-core";
      groupId = "software.amazon.awssdk";
      sha512 = "9d35a860893a05eca98768b8edbd3bac715961ef7aee0f77f0bda5f031fd8445b0b591b73129dc82ee9808711f1c97c835b1ad5e1e06578ca29ded4b06f323fc";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-dataformat-cbor/com.fasterxml.jackson.dataformat";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-dataformat-cbor";
      groupId = "com.fasterxml.jackson.dataformat";
      sha512 = "ea5d049eac1b94666479c5e36de14d8fa4b7f24cb92f0f310d2ec2b4de66ef9023161060e67228ef2d7420a002ef861db12a29cad0864638c21612da49686f4f";
      version = "2.12.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "websocket-core-common/org.eclipse.jetty.websocket";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "websocket-core-common";
      groupId = "org.eclipse.jetty.websocket";
      sha512 = "69d3895752736ed45a24af21549e768f567902e5854def1d013ffa72c69768ccc3c8ddf2e5c2a2a79822b5d4fdd118cd2f3274e74e265038b7793b9d96d06b32";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-transport-http/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-transport-http";
      groupId = "org.apache.maven.resolver";
      sha512 = "0650fdfa290cfa43e7d723d1092743016d8b2bb4fad825ef93e43e4ce687d41310967015e6faa14a0d3fcaac75cc8916a4b50053d77a60686d2d3fa6e51e9976";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jline-terminal-jansi/org.jline";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jline-terminal-jansi";
      groupId = "org.jline";
      sha512 = "4ccb0b89d7523d65e5f4ff02749be935aa2d4da2fbd6c18ff72c70f4cd279a67c4dccc7cdbacc4581e37c9984322cd184af2bf051939f457cfd4546675bd8b15";
      version = "3.5.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "json-simple/com.googlecode.json-simple";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "json-simple";
      groupId = "com.googlecode.json-simple";
      sha512 = "f8798bfbcc8ab8001baf90ce47ec2264234dc1da2d4aa97fdcdc0990472a6b5a5a32f828e776140777d598a99d8a0c0f51c6d0767ae1a829690ab9200ae35742";
      version = "1.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "snappy/org.iq80.snappy";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "snappy";
      groupId = "org.iq80.snappy";
      sha512 = "dfd2559bf0388c6f1987d1393497a423203b2a72febbe648b3429e4d07b47a504797228e6e4e39a94c6800c5d3df8d3792863a3b841e6e8f65cfdcda91b6f0ab";
      version = "0.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "sentry/io.sentry";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "sentry";
      groupId = "io.sentry";
      sha512 = "c6ed255052da0ff70e1914366f06a8ac811cae956c0c44f84e29922ce5ebad652d064a37e3bc5b83d896196c78f15dff2402030959a8029aee02419db7c39702";
      version = "5.6.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-cljs/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-cljs";
      groupId = "com.cognitect";
      sha512 = "526d3331857586ab7e8edb78795c375aaafe6dc3da24706663918a7dc38e25db7d0f554c334ec3be0334050d59d8616bd9cd6c9a90cf4bb4b33b1e0ea294d29c";
      version = "0.8.269";
      
    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library";
      groupId = "org.clojure";
      sha512 = "85e259bd189554659fdcb2f137c7de81a8aac97669b865254c59c713e6a8b79eb4272fa1444b9bfc5d1c8447140daa53aac74cacd21527e6186cf1ec0e776d32";
      version = "0.0-20211011-0726fdeb";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-model-builder/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-model-builder";
      groupId = "org.apache.maven";
      sha512 = "e6493b88baaab589e42286ee4965fbce6842cfbbbbfdaf441c504a22332705d1ed0537683099c2d6d11208137c35a0295898925a17aec0c63884b327f7fc2abf";
      version = "3.8.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "pretty/io.aviso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "pretty";
      groupId = "io.aviso";
      sha512 = "416433ae5c5773a3a12e7cff3f75a43f1a2d3f4454aad04d065c1e4e13627130f289dbb41355a5665236082b6535939fc4c40a2fddcc22a40d0d4ba290544bfb";
      version = "1.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "rebel-readline/com.bhauman";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "rebel-readline";
      groupId = "com.bhauman";
      sha512 = "5a6881ffc5a5fd0726938ab54d5917113f7f02a79a1ca8afc1f44967fa57877d30574ac1b6c1eccb37aaaf86b523ae35abe05430851f4087c12ab7a6ef9b10ba";
      version = "0.1.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "aws-xml-protocol/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "aws-xml-protocol";
      groupId = "software.amazon.awssdk";
      sha512 = "b47f9f21a741c06c268df3b270bc297a961067f2254371b172955f6440a06705bae169b15b2ff2e5b365032512bbd7e8f328cdd2f05e0fc5f5958aa86fddd10e";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "cljfmt/cljfmt";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cljfmt";
      groupId = "cljfmt";
      sha512 = "0b1276cd8d7aa45b6615cf0361ff31f8c24d1e656767c5eb751fc50ad6a2936edecc3092d4606eef8b600ca79336f7094816f7b2ac3e1c68b3a0c01277cb501a";
      version = "0.5.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "rewrite-clj/rewrite-clj";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "rewrite-clj";
      groupId = "rewrite-clj";
      sha512 = "5327be3bf8f0d575e9110dee45e7cb449f906a692eb66c2a2d2fc994c23b4f7102f65b52f22a2e0f8cc5ee4672c21270519d6c0580a999337efb402050d7179a";
      version = "1.0.767-alpha";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-cipher/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-cipher";
      groupId = "org.codehaus.plexus";
      sha512 = "8f187b07867a7c29d77454aae4b76479300238d9c4e777c1afa2aebe33b88dab916e29111dd55acac1341849f4579fe91a5470fdd45ccba0e05709c2ce3a1d65";
      version = "2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clojurescript/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojurescript";
      groupId = "org.clojure";
      sha512 = "29861dc16f4275ea2019b331ec49832e42dfeae0e033599ccf31bc0e647337de4cb139f659c68a4da82ef9a699874523dd4a0406bcaacf003fc3d910d1c510a5";
      version = "1.10.914";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-utils/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-utils";
      groupId = "org.codehaus.plexus";
      sha512 = "0668d413520a713d9279123eccae3b5e9bc79f41dd8da3b3a1ba79b7b60086c009639d91d84df230e490192fe63b10390f3901478c69bfd452a1280364d24876";
      version = "3.4.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-transport-file/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-transport-file";
      groupId = "org.apache.maven.resolver";
      sha512 = "8037285f888cf37cc3563528bedb3171a3987750b137ff2c6f77e6ed25fcd0d84be3aa80bebd283bfd5decfb8c55452e701f513a2f4e89ac765cb683b332e87a";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "org.eclipse.sisu.plexus/org.eclipse.sisu";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "org.eclipse.sisu.plexus";
      groupId = "org.eclipse.sisu";
      sha512 = "38d7dbe023f9751cb5e30bf154e31696590317dc7b7f768811fe0f5940513fcea4665670cd47d0b72ded85453b10f7d129b0b7428b155a41c903c7b56c986e8d";
      version = "0.3.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-buffer/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-buffer";
      groupId = "io.netty";
      sha512 = "fca06b40bf27cc7181ea4a8db4bc75adcef04dca099e06008a0de577aa33f041841e2e2f32a4670ac304deca628ec840fef069a01435dd769eda3bc9e829a290";
      version = "4.1.72.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient_tracer_common/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient_tracer_common";
      groupId = "io.prometheus";
      sha512 = "9b5c53c83083ceaae5810e1ccaf9a4987f720a069c3fec85ed5728d4bf12a26c990b6078614df6e3eec60a8378fdc1e827b9551ea4b72c323e4f4a0286070457";
      version = "0.14.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clj-async-profiler/com.clojure-goes-fast";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-async-profiler";
      groupId = "com.clojure-goes-fast";
      sha512 = "d695cb49bc2f4c922bdf9d786289b799e7351589a295287b68769fa3de760da641a464ce695525f89dafe3f498991ec590fcf9f95b6a1a6b293a7198deb034dc";
      version = "1.0.0-alpha1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-handler/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-handler";
      groupId = "io.netty";
      sha512 = "52c6c19e2eccade9e98dca40f87690bd2ef019588f5205b003fc93833d052360c4b2ef95048f6f046d7e441addf2184c2f0d55d9bc55acce5dcd57b8bbab7e26";
      version = "4.1.72.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ordered/org.flatland";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ordered";
      groupId = "org.flatland";
      sha512 = "676db4c71999127822349f5f97960115aa5f3124eb3a93b441680c5ba747ebc1981718f93e8dc94fe34f0c1c84ea3568c452691967b92509e5e125dac3ee59eb";
      version = "1.5.9";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-io/commons-io";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-io";
      groupId = "commons-io";
      sha512 = "5bd78eed456ede30119319c5bed8e3e4c443b6fd7bdb3a7a5686647bd83094d0c3e2832a7575cfb60e4ef25f08106b93476939d3adcfecf5533cc030b3039e10";
      version = "2.11.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-settings-builder/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-settings-builder";
      groupId = "org.apache.maven";
      sha512 = "233ebc32f26209a0f0615d8737becd396dc4d3f1ce349dbe793b437db1c64ac8c54ce055c636bbcbee7b489d0be7188b7fec0a9a4cf6a2f8d94873a374c91d3d";
      version = "3.8.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.fressian/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.fressian";
      groupId = "org.clojure";
      sha512 = "1377e855766bdf78c1fe57a5d712205ad0895539434dbc7e9e9f1ee5c28bae02955bd3a63016ccca6f916b2cea462e5febd7642b2f9825096f6279ade85c6824";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "websocket-core-server/org.eclipse.jetty.websocket";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "websocket-core-server";
      groupId = "org.eclipse.jetty.websocket";
      sha512 = "a5e6d7dc088dd47af0d6920806afd3eec4bc95e4a80bd60c17869d7454dba351a4678fc6171172104487de000da3ebaa7b82c46e9cb3168623e9fe2f1e9cc6b9";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "postgresql/org.postgresql";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "postgresql";
      groupId = "org.postgresql";
      sha512 = "e28b5a2b15b7b12f3b0c76b914f9aca25867175bc87a0ca84da58e50a5c518c5de94e27ea6d570499b1320c9f8072f1022d08356e9a0e96b3bf9b1084e1f9aea";
      version = "42.3.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.namespace/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.namespace";
      groupId = "org.clojure";
      sha512 = "4430c0d6f3974428cf99b51cd3d4ae6724401ef52257398f435dafd86dcc4294b706412f0abf9c8ac1d99eb8ab29b599210f2588df3f98ecef73651ca3088754";
      version = "1.3.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "http2-hpack/org.eclipse.jetty.http2";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "http2-hpack";
      groupId = "org.eclipse.jetty.http2";
      sha512 = "526f3d6be01822c1de1f441d3f049c3f3d3336b958f197704599b851ac8f600ab5a1f242b9604e2f0cb73f9a31dfef242e7153b74f742b164ebd154878c37dc7";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "fipp/fipp";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fipp";
      groupId = "fipp";
      sha512 = "ca7399b01955ef82cea8bd25079e2d6c037d6c4440af015d861f8d5ed8762613734952758f6de3fbc89cbc258ffb265a613d7d237bed7de0a9283020d16126a2";
      version = "0.6.25";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-plus/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-plus";
      groupId = "org.eclipse.jetty";
      sha512 = "89e69b7f1d5f338c767890426f495bc5edcba974ece6ef69236038e301be353a48a7e6f98c249d613b7c7420bb9da1b8a7025aef8e528179377585e090ab75f7";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-core/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-core";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "8a340c9ce19fcf159fc321ff7bf7491b8d60348b472ad4af2bd6e71ef47f1b485afac4d71e734ab6bbf60541a62254ece3f7b12eedd68a88a6623837743d4bd1";
      version = "2.13.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "pretty-spec/pretty-spec";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "pretty-spec";
      groupId = "pretty-spec";
      sha512 = "eac4574f49d307cf8df28c6c14cdfbdd2f4a34a4f6f9e9a76e9ae30509217b1e643750c31fde67f0059dff3bae0739e4d469a3ba53339640315ec4cfc00d7796";
      version = "0.1.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clj-time/clj-time";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-time";
      groupId = "clj-time";
      sha512 = "e39338f2133f5f6997d21f62c4f0e8dc0487ce308340bc9ea4588c16b824c111de035fadfacc6cf76260bc9d81194d5909637bb033264dc0ccfb43572e1f4a21";
      version = "0.12.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "snakeyaml/org.yaml";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "snakeyaml";
      groupId = "org.yaml";
      sha512 = "dce610268daab6fd6bac54f819f2f5795b17a57792b0f5553ee72acfbe8b9f81367ba7419655be8348369eb489259b14ddab7cea7a0c3c1b193bd62e0715cfd3";
      version = "1.26";
      
    };
    paths = [ src ];
  }

  rec {
    name = "websocket-servlet/org.eclipse.jetty.websocket";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "websocket-servlet";
      groupId = "org.eclipse.jetty.websocket";
      sha512 = "e52fe6fdd53bb47d91f2e2c7d2a1c5b0fff18ea8eff61e2a40aa7d9c88521ab5e4d2243f146de3f8320e95f6cad43642a555937e59679fba930d0ffa5f6b34c7";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm/org.ow2.asm";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "asm";
      groupId = "org.ow2.asm";
      sha512 = "876eac7406e60ab8b9bd6cd3c221960eaa53febea176a88ae02f4fa92dbcfe80a3c764ba390d96b909c87269a30a69b1ee037a4c642c2f535df4ea2e0dd499f2";
      version = "9.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "websocket-jetty-server/org.eclipse.jetty.websocket";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "websocket-jetty-server";
      groupId = "org.eclipse.jetty.websocket";
      sha512 = "2af0c3663049375fb3cb59d5e9fdee04759b74c652f5033f83df2e01b2c186aebd40918f251aa83d877249014e25cd1d7456c463b608df86475aabd0476e4910";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-settings/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-settings";
      groupId = "org.apache.maven";
      sha512 = "3e0d2652164dbdbadccd60aba6ee2d6ca41d4065080f29f5f1654ea4884d28b054703a8a64a01cf8c6ccfa02cf8af29cab161514d8e852abcb1b3411aba74be7";
      version = "3.8.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reitit-ring/metosin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "reitit-ring";
      groupId = "metosin";
      sha512 = "6ad8e3535a3d8552895f1211adb2e164985e69b34492ceb50f8c7560d1c13c639a6387c54bd5b759ddb59beb591b2796f897892451af89a0012122c7e5a15253";
      version = "0.5.15";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-core/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-core";
      groupId = "org.apache.logging.log4j";
      sha512 = "8d3d6a17afc41cde43b19c9a696793d009d9271bc6430762f10157018453f8a53cde6e6aa4f3f0b703eaf1f2944d047398d29b470924ecc3290d1923b0e29750";
      version = "2.17.1";
      
    };
    paths = [ src ];
  }

  (rec {
    name = "funcool/yetti";
    src = fetchgit {
      name = "yetti";
      url = "https://github.com/funcool/yetti.git";
      rev = "59ed2a7eec1b66c6037d7aaa961d2124ad8c60ca";
      sha256 = "1nb0dd7c5sz836100110w9azmrqgmg6im1j2cssxyb2ds0ay9i3v";
    };
    paths = map (path: src + path) [
      "/src"
        "/target/classes"
    ];
  })

  rec {
    name = "httpcore/org.apache.httpcomponents";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "httpcore";
      groupId = "org.apache.httpcomponents";
      sha512 = "23430cde8b9bed33c91474ba49f1143284135df1b25fdcbc37bc3bb7e9549e77b3918eb40250093db652ae200367e87316129b23b4f6987e94939d60f467498d";
      version = "4.4.13";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-security/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-security";
      groupId = "org.eclipse.jetty";
      sha512 = "43d8c3fd241b4ef0e4749f5a182076d7dc2ee9b7040502f39246530e0f3ec8128f291a0bce602628c45b15d0eb7971f587508d37cd68ec14b21aa7431d61e445";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-reactive-streams-http/com.typesafe.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-reactive-streams-http";
      groupId = "com.typesafe.netty";
      sha512 = "e387b8a681082960309d1cd0c4f1311f75e1244c9ac3895374c148adde9f00f5e4951b05e170503f6e647fec75846ffe1aed4353c1751d8d74251fc6e8cbed29";
      version = "2.0.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "primitive-math/primitive-math";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "primitive-math";
      groupId = "primitive-math";
      sha512 = "02fd7cabe27cbb11a944059b1b5261ed089f3e5c641246da6d5a2ab2a6afd3d33c9fb1300f948255f4958551f91b93c5fd930bc3d657cbb9c95fb05bf0a238b9";
      version = "0.1.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-sec-dispatcher/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-sec-dispatcher";
      groupId = "org.codehaus.plexus";
      sha512 = "ad4e814c8baff780a4eee064903e52b09ae00420a59fb075ef72dbb8d64d12d3d5009b03d56c15f93587d931c3a7f06cad6351ab2dc9415ccc6eeab0daebeb07";
      version = "2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-core/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-core";
      groupId = "org.apache.maven";
      sha512 = "228665bba3dfe2423e4738756a3fc6e5128170ca074c905fc46ee328b8726237b9839db481785078624325d7a951a096bf0dc75f632b5f30268f2cc457871e13";
      version = "3.8.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jakarta.annotation-api/jakarta.annotation";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jakarta.annotation-api";
      groupId = "jakarta.annotation";
      sha512 = "d1acff146c0f9ea923a9325ad4c22ba2052ec474341ab8392abab7e8abd3ca010db2400ff9b5849fc4f1fa5c0a18830eb104da07a13bd26b4f0a43d167935878";
      version = "1.3.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-tcnative-classes/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-tcnative-classes";
      groupId = "io.netty";
      sha512 = "673032d09f7151efa7d2e7851bf38d2aa037d54d38fcedb13a6a271684120d10cf4584ede56180cb681a2269e3ffa54965dfd56ec96db8be5194d3ccc56510e2";
      version = "2.0.46.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "integrant/integrant";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "integrant";
      groupId = "integrant";
      sha512 = "cc0360e9f3ecb38854582db6b83004f51a8ac64a467b26e71289ffe6a594c7d96f634371d43ccf90c562eb5beda24ee5db98c1fe7ca0ce7d54d27375b6bb7d66";
      version = "0.8.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-web/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-web";
      groupId = "org.apache.logging.log4j";
      sha512 = "0c4dfd435e96da698dd09cb891548b2d9e8129040b4700f86a233118e5e5d72747910c6c9294552c54e23afd5f140c61728338d8e6b2209c00f7bf2f228a873d";
      version = "2.17.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "buddy-hashers/buddy";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "buddy-hashers";
      groupId = "buddy";
      sha512 = "49ff0d0dbf36e7dde8ca6e1ee294033ac3af12e2e1bb5e9cf9629494a403c10b4fe928f2091fc37e21fae5b83bcce574ce3ad513a121dd8d3e6819eabb56ebee";
      version = "1.8.158";
      
    };
    paths = [ src ];
  }

  rec {
    name = "math.numeric-tower/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "math.numeric-tower";
      groupId = "org.clojure";
      sha512 = "fefa379a827412d58acf118bd522a8a325778c3ced7580fa9f132659d456bd621d85e29349914ed5d8add684c82885cf5fe62d9e2b3fecf88a5f6076dc34366a";
      version = "0.0.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "sdk-core/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "sdk-core";
      groupId = "software.amazon.awssdk";
      sha512 = "ff802aa89f06d3ce314119dc9daf97cb80b55ee33215778b0b122fe25e1bb9563269830cb926aa7d4b1a9c8ba46bae7789fdcfbf84c4a584cd9959d222ef8174";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "scrypt/com.lambdaworks";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "scrypt";
      groupId = "com.lambdaworks";
      sha512 = "bdf4e64b5b7231edf13e92b788593facb9e125ff9b1c69f48016314956d7fb58dbef00db27e8c1b7fe44d4b49aaef6253f8162c7d76723ec066c10f474bd5ae6";
      version = "1.4.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-js/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-js";
      groupId = "com.cognitect";
      sha512 = "bab8c657449a1d01e884923b77c5ef3d7a1a246c3ad1bd85a5b0c98b7952dbdeea97ce7d340ab50aa0dca647a1ef7eb846a52a1a4eecc55e1ff22145b8e820fe";
      version = "0.8.874";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jnacl/eu.neilalexander";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jnacl";
      groupId = "eu.neilalexander";
      sha512 = "addba1eae1975a71a204557dafb111c5c2aab39d9a7bb6428a26107935d95290139381c0a283b77e67b44e1d8110d3fa3919d7e7fc73e0023771beece4eab994";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reitit-core/metosin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "reitit-core";
      groupId = "metosin";
      sha512 = "05896174f32ba1f49df4d2a70e43fb8e36445ff483d67696afc969056431d340db9d6f91ea13d21790475c872871bb468903345abe19195af4cbcd6afd1be29e";
      version = "0.5.15";
      
    };
    paths = [ src ];
  }

  rec {
    name = "scrypt/clojurewerkz";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "scrypt";
      groupId = "clojurewerkz";
      sha512 = "70b5bed1b89318ee1eb0333fa11d88d10627cac372f498ab672bf1eba3639506fed10a44af452352b4002b5c7746c52e7407e034b437f31a61f445dadcd6fe9b";
      version = "1.2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jansi/org.fusesource.jansi";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jansi";
      groupId = "org.fusesource.jansi";
      sha512 = "300885d77568256b907bb9cdad5bd8bf91ab3b8dc67ad52c96f62d14b055a756f122edce0627b99984bd24df739189706bf824b1dfe273be43fe6dee018549dd";
      version = "1.16";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clojure-humanize/clojure-humanize";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure-humanize";
      groupId = "clojure-humanize";
      sha512 = "6272053d813fe8568729a8f7fac3a2ad45fc1b1d773712d8329701c3165d97d886a461dacebb88f3acd06cb7c8ee90a6cf6a02cd54c51b2d1ab9a7708ccd8648";
      version = "0.2.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "truss/com.taoensso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "truss";
      groupId = "com.taoensso";
      sha512 = "79a515306228e8e8f1c1cf5bb65ac8c979954f3a6e8461c059a7b9402967163a1eb7a70de3ad41e8195d9dbfac2d17af8cc03e09bf72f8e9f6704b842656c0b9";
      version = "1.6.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "cuerdas/funcool";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cuerdas";
      groupId = "funcool";
      sha512 = "f268d26ec618ad3f595f22bce4167e60b25696f7a096862a66c6a61380874a533fd7717cf270390c84bb476e403381dfbf37b8d02a08fd961a32e0231d292868";
      version = "2022.01.14-391";
      
    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library-third-party/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library-third-party";
      groupId = "org.clojure";
      sha512 = "2ceef3cbba119d66a38619dc4309ee9eb5e3cccacae0a50e7f099a8df160e345e1abeaa315285fe0328c6afc842a77f6fa9d3c710745b07ce8d484caca7f47bf";
      version = "0.0-20211011-0726fdeb";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-api/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-api";
      groupId = "org.apache.maven.resolver";
      sha512 = "002cb75f6e07b27108e79a4d37d94fa882e89a2db30dd2ac69ecf0907cc548e13f579ebfbb5c019da6df4a950e3420b69dac3d49ae94b5646b7968ef7ea811ca";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "regions/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "regions";
      groupId = "software.amazon.awssdk";
      sha512 = "230f3faea491fe0bc91f0ae911ceabe63f2ee4535726c72b5d84a2ef81d9e693b5b9d9871b1e5bae4c36ecb06fe991b4ca903ddfec6c87c96fbf43417143e0b9";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-annotations/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-annotations";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "95029364686bfd19af46bb93d6dc96262ee021452a862d6c6ddc7fbda49bca52267f0b7afc98c177fd1619907a7cbca673b8ee150b0076f8099dc605836a236e";
      version = "2.13.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient_hotspot/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient_hotspot";
      groupId = "io.prometheus";
      sha512 = "c1c19616fcbf8675382c88d7208a5224937a6bf22569927f41b112b6e24798a81dabf9ca7b39ea411093748a86badc55efaf225ebef0ff804898726d2914e468";
      version = "0.14.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "http-client/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "http-client";
      groupId = "com.cognitect";
      sha512 = "5507956051ce71d5f521537a443390d49be8fa629074fc19781d0e5e072207afa543ec690876eb895174d82b85810888eb839a0a3ee82ad3394244c7fb78e015";
      version = "1.0.110";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-provider/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-provider";
      groupId = "org.apache.maven";
      sha512 = "26a359bf14c2c6c3a748f95a244f5bc0251ef75082155e931481f6c93b4b29db5b032ed3d6659e7241d7a166c662dab55aa41c4e7dd82bf52ae583536eda7b40";
      version = "3.8.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "javassist/org.javassist";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javassist";
      groupId = "org.javassist";
      sha512 = "ad65ee383ed83bedecc2073118cb3780b68b18d5fb79a1b2b665ff8529df02446ad11e68f9faaf4f2e980065f5946761a59ada379312cbb22d002625abed6a4f";
      version = "3.18.1-GA";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-webapp/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-webapp";
      groupId = "org.eclipse.jetty";
      sha512 = "1e2e8528642804b1d245187e87c04c8ce414936e95d9baebedbe53a1dcd0e0369e1717f908358a51f365b1a93216cdaef1f0d6f0ebe9e3ecb2b3515859a5f557";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "checker-compat-qual/org.checkerframework";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "checker-compat-qual";
      groupId = "org.checkerframework";
      sha512 = "fdecc20efd6943426e7f8bdfb8bef9d28258f9f934cf29090e2f5b297c501454606cc28593cd7d089a5c14f6d2dcafc59f4606053405d7f91d623a0e3202f4a8";
      version = "2.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "linked/frankiesardo";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "linked";
      groupId = "frankiesardo";
      sha512 = "d47354631d642a603f1f64e1bd872f623d8e6e7a8c40e968bcf124681585920c423a51f3388f6a4101c5f346b3e10a17b7e256da617ca0d1f19a25169dac46f7";
      version = "1.3.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-shared-utils/org.apache.maven.shared";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-shared-utils";
      groupId = "org.apache.maven.shared";
      sha512 = "c6693f8a061de74ac59c61d185f5b130cb574405cfc37febb8e73806ea64eea822a4a75c24098fb49b7871373091543a6f4c526c0842589e528cacad40e5554a";
      version = "3.3.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "java.classpath/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "java.classpath";
      groupId = "org.clojure";
      sha512 = "90cd8edeaea02bd908d8cfb0cf5b1cf901aeb38ea3f4971c4b813d33210438aae6fff8e724a8272d2ea9441d373e7d936fa5870e309c1e9721299f662dbbdb9a";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.deps.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.deps.alpha";
      groupId = "org.clojure";
      sha512 = "95c53bb637f02dcd2061a26262067ef52a45cdeb780dc8e7d3a1de82b673fefbc16cf07eb56c4289563b1f2dae151c710c13918bc411894ee614358f3270dcfa";
      version = "0.12.1109";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-logging/commons-logging";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-logging";
      groupId = "commons-logging";
      sha512 = "ed00dbfabd9ae00efa26dd400983601d076fe36408b7d6520084b447e5d1fa527ce65bd6afdcb58506c3a808323d28e88f26cb99c6f5db9ff64f6525ecdfa557";
      version = "1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "environ/environ";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "environ";
      groupId = "environ";
      sha512 = "e318da117facf51a27b9ae39279363c4d824393215ce63fa69e5bdb65a910d1f8632d712598ad0c3f4248d0ab9274a97161859393d265d74d50ad2a4cdbddf41";
      version = "1.2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "guava/com.google.guava";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "guava";
      groupId = "com.google.guava";
      sha512 = "c8f95af9f1e97dee807503c8fbb442c87eed2694e43ad0fd9fc2e62ba99c5e93d476d5ee8f4791f173cb8fdabc88abac0e8130a51de280af836a3e0c4eadaff6";
      version = "25.1-android";
      
    };
    paths = [ src ];
  }

  rec {
    name = "datoteka/funcool";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "datoteka";
      groupId = "funcool";
      sha512 = "26826aad46c92f258389a7de77e6e8ab15c8a2ec359c3159dfe6f55e6bdd8d8ca0e4a6ad6efe70b07589338425038cdc63230c3ee8c3d2ccd89d2b330517a45a";
      version = "2.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.xml/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.xml";
      groupId = "org.clojure";
      sha512 = "12ea6e7ee27be4a0329a766f3449f3e3b756772e3cd8588b4666bb175faaabd0780b96300b10e17ccb3016b0ba5d9f020c7d976211ff398e7bebef718aa4d5f5";
      version = "0.2.0-alpha6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "aws-core/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "aws-core";
      groupId = "software.amazon.awssdk";
      sha512 = "7abac1d02d54a011c0050ac7c059e969657134c904f234ddd7c364b68b182a24bf72a0b938876c39283b8e5825ac0d3e0f63a49b89fdcb815058efeb1119473f";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-spi/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-spi";
      groupId = "org.apache.maven.resolver";
      sha512 = "2972b721213bfee654460468b2a2aa50546d7f1957be40d955728875af3a9801f8d78a2f796e832b9332d1f90ffb5ccb651289e7b5c8a175628b21b13594df43";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-slf4j18-impl/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-slf4j18-impl";
      groupId = "org.apache.logging.log4j";
      sha512 = "d001170cac70e8f4df228cb813d52bab714fd3026d653eea4dd4827ce18df74b4b0f08525966e48be0ae3dae068e92fbcb5aa16e441ac01fafa1c3af21e1ba0c";
      version = "2.17.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "http2-common/org.eclipse.jetty.http2";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "http2-common";
      groupId = "org.eclipse.jetty.http2";
      sha512 = "fa5eb8ab2784a26ad9ff83bb3438a9587e38ab99d9f3a7bf9e200c6738bad5c4b2a7147919c27460773fe40b4621c025388f85ed223089d3e8474eaadcdc2e9b";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "msgpack/org.msgpack";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "msgpack";
      groupId = "org.msgpack";
      sha512 = "a2741bed01f9c37ba3dbe6a7ab9ce936d36d4da97c35e215250ac89ac0851fc5948d83975ea6257d5dce1d43b6b5147254ecfb4b33f9bbdc489500b3ff060449";
      version = "0.6.12";
      
    };
    paths = [ src ];
  }

  rec {
    name = "j2objc-annotations/com.google.j2objc";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "j2objc-annotations";
      groupId = "com.google.j2objc";
      sha512 = "a4a0b58ffc2d9f9b516f571bcd0ac14e4d3eec15aacd6320a4a1a12045acce8c6081e8ce922c4e882221cedb2cc266399ab468487ae9a08124d65edc07ae30f0";
      version = "1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.csv/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.csv";
      groupId = "org.clojure";
      sha512 = "6b667a56cbb6632a90564f217f9c28a6670c13c729fb205ced091d9ee006382143dd6b615dd5a4f900660946199cac449fe9fabc90820bb34b92a9e6c8550473";
      version = "1.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient_tracer_otel_agent/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient_tracer_otel_agent";
      groupId = "io.prometheus";
      sha512 = "bcd8c5bacf77784a7e86fd17d94326a2ba5ea01c54fc8f8a82c79cba4fd3ef973711492141d809cbcfad53923aa1893d8a313a85a4554fb82cbbd0c399e7450b";
      version = "0.14.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "slf4j-nop/org.slf4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "slf4j-nop";
      groupId = "org.slf4j";
      sha512 = "3d178b92f340339b8473de9effac62b494c01c2b003d578f693052ad422f3fb653df70ac52a752aa2fd84bac3d87014bbc58beb84406154b8c8bad3470fafa7e";
      version = "1.7.32";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-clj/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-clj";
      groupId = "com.cognitect";
      sha512 = "efe5483c188c8e6fb7327e2b312424de920b913ec9ca89580fddceb2a964de4ce75aab79d7d3671bb362b9af73a9e25a331abd4f53ce544d9b50f83a1a07adf4";
      version = "1.0.324";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-classworlds/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-classworlds";
      groupId = "org.codehaus.plexus";
      sha512 = "6a58048d9db54e603b9cfd35373cf695b66dd860bec878c663b4fc53b6b3d44dd5b0c92e7603654911b1f78e63ef277cf6b272fe069a360989138550545f274d";
      version = "2.6.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "next.jdbc/com.github.seancorfield";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "next.jdbc";
      groupId = "com.github.seancorfield";
      sha512 = "0b4b01ba126bb8b1e2c14262db9fca75456b274d09535d9a7bb386699bf20dc9ac11590d210769e7429ca59ebfdfbb06916b3ff275cc817d74eac5bbabdab8f2";
      version = "1.2.761";
      
    };
    paths = [ src ];
  }

  rec {
    name = "json-utils/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "json-utils";
      groupId = "software.amazon.awssdk";
      sha512 = "daf85b8f39f33bee3bf304741234bc325237925221bbae964d86b8db5fd09bf1db212b2ac621461e92bea4b720efb847f5c4d0db875eb6e3a31e521df35f0113";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-transport/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-transport";
      groupId = "io.netty";
      sha512 = "3f3ae28f47d9f62bcb806065f0d68d8ca168bf5de18b52392ff7f69b9f6cd000f82ce71b84f767a09c5ca9bcc5d8977cc9889a219bd3bc1b6fba15f6b2f41082";
      version = "4.1.72.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm-commons/org.ow2.asm";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "asm-commons";
      groupId = "org.ow2.asm";
      sha512 = "d5bd27f9b8b4eea93635ceda3891665fc9db273818eb02d40da4b110b81524458de3f71a63e87d6bec9423ba0f2e14c20ecdf7706dfeb54f0b05aedb13a63ecc";
      version = "9.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "auth/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "auth";
      groupId = "software.amazon.awssdk";
      sha512 = "941a53def1f7e819ceff90ba9bb4d1c42f66e0b44c2b22e91442dae870d28f65fd9c2db27324d3bdc59cf140df3fbd5cb448418f29a1415176916b6b429814da";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "fressian/org.fressian";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fressian";
      groupId = "org.fressian";
      sha512 = "30aedc721f7627a308ebb08c27672fedd668c3297ac6de79303f79457d97b66166611920f2ec273f3558850767c16d535fbae6e468760491d43c2da3892bcfcf";
      version = "0.6.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "crypto-random/crypto-random";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-random";
      groupId = "crypto-random";
      sha512 = "3520df744f250dbe061d1a5d7a05b7143f3a67a4c3f9ad87b8044ee68a36a702a0bcb3a203e35d380899dd01c28e01988b0a7af914b942ccbe0c35c9bdb22e11";
      version = "1.2.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-transport-native-unix-common/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-transport-native-unix-common";
      groupId = "io.netty";
      sha512 = "726b5a5f17661dc5add0426b5b8a33f2c45c45dd6086ad201170c27fc25f92bcc4efad174ccea07768780dd54f95eb53c12dd21b1c5dd05f9bac7ebe9030d4ce";
      version = "4.1.72.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "http-client-spi/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "http-client-spi";
      groupId = "software.amazon.awssdk";
      sha512 = "f323092ccf94ec69625b18b854f9da9c7fe45b5e79431a27dbab77d29305499e368d2615c7f8d94f7e3c0ed6dcf432f8fab2a0bfe703530d2e69dcbeae5ed518";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient_httpserver/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient_httpserver";
      groupId = "io.prometheus";
      sha512 = "f2003cc777a9b5009b7582703c3f3bf647e9a2c56c9a85485fd061398ad3257bdcde874d5f406b59f3bb3dc50e4fb5becea9b306adb3acd965f1dec332458711";
      version = "0.14.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clj-yaml/clj-commons";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-yaml";
      groupId = "clj-commons";
      sha512 = "a9723bc593559d7081c37bb5920eb2d7d25b0ef18ce0b6721ae68050114089cb3a2cc5141b98d780c808f5199bc670e8295f3257f4b56ba1baca5819666e8683";
      version = "0.7.108";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-codec-http/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-codec-http";
      groupId = "io.netty";
      sha512 = "533c0e5c21f16df1ca0c40aee351a3ec3b06d5d658766964d3b0420137f564eccb2697ce1f2eec90943dac60f746cf8db27cd39b8135f2ac4e54e6d598a31795";
      version = "4.1.72.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ring-codec/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-codec";
      groupId = "ring";
      sha512 = "38b9775a794831b8afd8d66991a75aa5910cd50952c9035866bf9cc01353810aedafbc3f35d8f9e56981ebf9e5c37c00b968759ed087d2855348b3f46d8d0487";
      version = "1.1.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-interpolation/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-interpolation";
      groupId = "org.codehaus.plexus";
      sha512 = "6c3b40442adf721d325ee9cbf935d758223a04b3bd8e0f3b60fdb652175c1ca65a6010f7ea8288617ffa73cb1f19d2737c79c403d343b285e0f9afb1729caa60";
      version = "1.26";
      
    };
    paths = [ src ];
  }

  rec {
    name = "httpclient/org.apache.httpcomponents";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "httpclient";
      groupId = "org.apache.httpcomponents";
      sha512 = "3567739186e551f84cad3e4b6b270c5b8b19aba297675a96bcdff3663ff7d20d188611d21f675fe5ff1bfd7d8ca31362070910d7b92ab1b699872a120aa6f089";
      version = "4.5.13";
      
    };
    paths = [ src ];
  }

  rec {
    name = "protocol-core/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "protocol-core";
      groupId = "software.amazon.awssdk";
      sha512 = "844ac82fce0ca449169a2344e0dbd87fa2a041fe98175d525a96d7e7c1ccc351aa60b0a405526edb24bd18563fb629d02b3a9fd887eed167f70b0f54d0e89e8c";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.rrb-vector/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.rrb-vector";
      groupId = "org.clojure";
      sha512 = "8204b559d2704105741e1c9a5b8c639161a4f4af09e18b93d6af23685dd8bdebd66b64e626a4daa69069759c423640b3a3787216b78c2e62c891650e2269e8a0";
      version = "0.1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "crypto-equality/crypto-equality";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-equality";
      groupId = "crypto-equality";
      sha512 = "54cf3bd28f633665962bf6b41f5ccbf2634d0db210a739e10a7b12f635e13c7ef532efe1d5d8c0120bb46478bbd08000b179f4c2dd52123242dab79fea97d6a6";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "promesa/funcool";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "promesa";
      groupId = "funcool";
      sha512 = "8dc3733efb86d2383d62296d4d3e10c3425de802da11f342fc000927711b98e3f2acca8891f6334f5217b6cefb5f852f41a31b057a47b270e69ae2db570416c3";
      version = "7.0.444";
      
    };
    paths = [ src ];
  }

  rec {
    name = "checker-qual/org.checkerframework";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "checker-qual";
      groupId = "org.checkerframework";
      sha512 = "407d0ac59b02cbef7d93f25c8b287cd587232aa5ddfee6d2c7ba34d712565b0a5adfe52b5daa20d3e6c3ab1e7a5f8b08698078d9179185a1b35ada1eb92213bf";
      version = "3.5.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "java-http-clj/java-http-clj";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "java-http-clj";
      groupId = "java-http-clj";
      sha512 = "50b1037b9b33da63bcf9624eb0b778c6f6de50d7bb756eccb925235e18fd74de6f3e83ae243e072b4ae64d10a3fba151c8ffaaa006657d5c9b493eb9a04eb209";
      version = "0.4.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "eventstream/software.amazon.eventstream";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "eventstream";
      groupId = "software.amazon.eventstream";
      sha512 = "461c7b63b3d39247af4073608e346b93d32502322136024868be3f7e40e71f348c3bef2450757b5dc8594ffd596f7af03ed69e4a383000bed8ac2a9e3f0cbe5d";
      version = "1.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "guice/com.google.inject";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "guice";
      groupId = "com.google.inject";
      sha512 = "78f17b090f34564db0fa6903c966e79d8002903d2604f9605a0d713e770a9c772c11d615a5e112dbb15464b9f8945edff6ac3d23ac84ccb08eb1657ec64d4442";
      version = "4.2.2";
      classifier = "no_aop";
    };
    paths = [ src ];
  }

  rec {
    name = "cheshire/cheshire";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cheshire";
      groupId = "cheshire";
      sha512 = "855e9c42a8d1c64f4db5cda45e31e914eb5ed99a715e8d7a5759a9c4ab6c69a82353635ca7b0837880c6cf9b41b11184ae11e09cbf2c07aa13db32c539e5dfd4";
      version = "5.10.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-reactive-streams/com.typesafe.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-reactive-streams";
      groupId = "com.typesafe.netty";
      sha512 = "51a46a4ecfdf794553b1012c2ac80d9c6343c7a4990e3224514d08c2b6c41979cbee6883601f2f697926cca89558e24d3a13e0b8b0c3341947e220711dbefcbf";
      version = "2.0.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tigris/tigris";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tigris";
      groupId = "tigris";
      sha512 = "fdff4ef5e7175a973aaef98de4f37dee8e125fc711c495382e280aaf3e11341fe8925d52567ca60f3f1795511ade11bc23461c88959632dfae3cf50374d02bf6";
      version = "0.1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-client/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-client";
      groupId = "org.eclipse.jetty";
      sha512 = "f2d70900e345694638a1b969729e4b3c9a3a19a563a53b2c74f26d7f67225dd03d57746a184f4df01fedc86aa9e62b62ca8bbe30ac4492d256ade5753ea2e772";
      version = "9.4.44.v20210927";
      
    };
    paths = [ src ];
  }

  rec {
    name = "arns/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "arns";
      groupId = "software.amazon.awssdk";
      sha512 = "3e61cf4b7f6d542d890fe36a052d233bbc3c204a5a51c5b9ca90b75ef92eb30bd4e04a8d299782267c83db626957635cae28e3d577556d77fcd5c9b54cb3b23d";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "cljs-time/com.andrewmcveigh";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cljs-time";
      groupId = "com.andrewmcveigh";
      sha512 = "f1f9c13f1bc0d71f64d40eee94aef3b202e94b220e408183ac4ff7995ac5db1521c67e8e02a3b12896ebff1d4568b63e7415c2a945854396095b0f337fcc4899";
      version = "0.4.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-jndi/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-jndi";
      groupId = "org.eclipse.jetty";
      sha512 = "d2b80c52a768d9a1a8b65abb6816e6a363153831f43680f7d5599bee2383e570c72ac1eb91e3fb7079090ed04c6ae14b39da83d5042f9236e7963efc5c811dda";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-io/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-io";
      groupId = "org.eclipse.jetty";
      sha512 = "07f4b069ad77146932e937ea983e5a562d1e1a3b429d1f62c4a2b5f385d128eddd56183d953e216d1928f02fdeb95e803589726d756fd3f362bbf24e75e5090a";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.reader/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.reader";
      groupId = "org.clojure";
      sha512 = "3481259c7a1eac719db2921e60173686726a0c2b65879d51a64d516a37f6120db8ffbb74b8bd273404285d7b25143ab5c7ced37e7c0eaf4ab1e44586ccd3c651";
      version = "1.3.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "simpleclient_common/io.prometheus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "simpleclient_common";
      groupId = "io.prometheus";
      sha512 = "4a2fefbe414e8822fdb54402cd6fd43ff50fc6ccbb938466d68a30b4ba8e544d79396eb5d6fb554224bee4dd391aee4aca12b5abfc5ecd6195fdbe94854d86f7";
      version = "0.14.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "compliment/compliment";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "compliment";
      groupId = "compliment";
      sha512 = "0729cc214b5e60683d02073a6fd2a9f7de9d7e13768f16d4d61c64e986a3b5186e725568cb9ea66cf80a915a7bbb317b9cda76d9833a59496d205a3ff979cd5d";
      version = "0.3.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "bcutil-jdk15on/org.bouncycastle";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "bcutil-jdk15on";
      groupId = "org.bouncycastle";
      sha512 = "f65fc2af60be9b4a0cfa227cede3ba5ef994716dcd462a9935ef74535a32e67c56cff92e6af9d5168c7a866e5f7c9fd17797485b89eb020eda12f7018af0fca1";
      version = "1.70";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reactive-streams/org.reactivestreams";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "reactive-streams";
      groupId = "org.reactivestreams";
      sha512 = "aafc86186d82b4f3bd44ef7f955978481172eab267d208aa80b24f8ca218bd902d69b587fcae2fe44a888b7a9f81fc5a209e837958307fdc0ee815248f7065f9";
      version = "1.0.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jline-terminal/org.jline";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jline-terminal";
      groupId = "org.jline";
      sha512 = "2389a8e84763868b3c0d4254557974ce4046e9d8e24301a4875b95f288e8792f8c9359a99fc7f3ed79bf3be09c29f27ad1dcbffa7c8f743f5361a314644eefb0";
      version = "3.5.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jsoup/org.jsoup";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jsoup";
      groupId = "org.jsoup";
      sha512 = "d06e42e2da5b852a966e137d9e5915d091c4e35d52ca0034e52bd938bc85f74b8c951238c138ce22086bf2ce20c72047c4d70e816a3e19fc42c1bae3d74533cb";
      version = "1.14.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-servlet-api/org.eclipse.jetty.toolchain";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-servlet-api";
      groupId = "org.eclipse.jetty.toolchain";
      sha512 = "758454d41cd0c08ec5b25c1e8ba7249fb11f753ea04c337614db9b99f2da9c1dd9a26bd0048aa6d1b95906d8aa67d0a9c719901b611d3017547adda9f7d4a289";
      version = "4.0.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "nippy/com.taoensso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "nippy";
      groupId = "com.taoensso";
      sha512 = "146aaf1b0d0a0f73d26125067b4549e9df1f66dc62aa5980f07b5586e03f55fa08ae0303c0b83d69fd989473a336cf7077da3686fccab8c7482c2bfa505a3bb9";
      version = "3.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.gitlibs/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.gitlibs";
      groupId = "org.clojure";
      sha512 = "9f2bfe18d5eea42cb09fee0d35e323ac5844c287e9073c2644c933fd89f41d64eca4d24a40e859a9cb7154da61e96550b39d52c766064cc0f7298f8a915b8f20";
      version = "2.4.172";
      
    };
    paths = [ src ];
  }

  rec {
    name = "antq/com.github.liquidz";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "antq";
      groupId = "com.github.liquidz";
      sha512 = "dd645b8252d369bda82097f4b06a64474679371c18d3c2557718655538a4a2e3d44b48c74e1176aa116960a7edb596e65d6d4f0744bd6d8e428ded889307bdc7";
      version = "1.6.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jline-reader/org.jline";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jline-reader";
      groupId = "org.jline";
      sha512 = "1cf3c039a40795052588c14fd318d9a3a58f4551929aeb7430e8ce1d16b8450ce5bdd335169f3e9ad9a01b3d92ed8fcad6a563e1970046744fbda1a49524c0ac";
      version = "3.5.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-resolver/io.netty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-resolver";
      groupId = "io.netty";
      sha512 = "e9efcf1255cf016fdbc9f1a92d4744f24a97bddfeff51389241267d6122d79c234223a0a4665cc3dc436af4817c864304710ee70d9590b229bd40d6aa07e58f5";
      version = "4.1.72.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-connector-basic/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-connector-basic";
      groupId = "org.apache.maven.resolver";
      sha512 = "4554cea39910393557cc8769550c3a12ba64e0f57244f71a1c78a9cd3a6032ae9bbd2b43d4c15579b6b89a766a19d28619fd99eeaa1b4862fda549d8cc9e3610";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "metrics-spi/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "metrics-spi";
      groupId = "software.amazon.awssdk";
      sha512 = "8b050eb749ec4042835a819044f561697885ff4595c0f55f0184c9d594b711e2bddb44d60f7069f5a0a8e51f7f1a083a3d69107b04d17a44be0da54a372b56d8";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "s3/com.cognitect.aws";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "s3";
      groupId = "com.cognitect.aws";
      sha512 = "e0ddbd294be4de0f29878d26a399034a86f244fcfa527d944f21253f13d52a1181beccf1af43cba2789237bba92c3cc76030b104c9f7e730e7b62ac559e969ca";
      version = "814.2.991.0";
      
    };
    paths = [ src ];
  }

  (rec {
    name = "io.github.clojure/tools.build";
    src = fetchgit {
      name = "tools.build";
      url = "https://github.com/clojure/tools.build.git";
      rev = "34727f790d0b4d568fe3b5699ce6ebfcc1f55d39";
      sha256 = "0glmy4hp54dhlhd1h99z84qi8zlz1bk6dz9p7zidynan6g656ar5";
    };
    paths = map (path: src + path) [
      "/src/main/clojure"
        "/src/main/resources"
    ];
  })

  rec {
    name = "utils/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "utils";
      groupId = "software.amazon.awssdk";
      sha512 = "56427b221e7e47adac214d76e528e24b8530a9b097c905f77729a44eefe18a63ea2be1a1a7c494c6ea2fbd4982eb6cae53810de03fb76a83c3f8b4d67b005d1d";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-impl/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-impl";
      groupId = "org.apache.maven.resolver";
      sha512 = "ef011e67152290379da6db1ce256b70dc436eb1596d58c38ee5bf9df65fbe75ed2ddc7768f6c61901c8cb83af88c42ad0b7bf24ad1775949eb4522511825280d";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "slf4j-api/org.slf4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "slf4j-api";
      groupId = "org.slf4j";
      sha512 = "db7440b47e87215f9cc88c9521bce7a0f2ffa81b07e5f53c5f8afa90a0ab61168755ee6d136245461b57a01f0a857fe0d509c60baa7838c4eb6be1f885438049";
      version = "2.0.0-alpha1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-model/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-model";
      groupId = "org.apache.maven";
      sha512 = "64b96a0f8779efe75103afd1ec685a9e50e810fd51c5afb5e6839fd875365cb61e534818a6ec1119520541e960f63692172d8bdae3d8e63a583558296f9ecb4d";
      version = "3.8.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "version-clj/version-clj";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "version-clj";
      groupId = "version-clj";
      sha512 = "f5eecd356d1206bdaae6cf400c386e06de0f4601828bb3a563d66108073cece0980978cbb171c38ff3e6a2fd46b592de9e29b26c9ed555db0d3b5c43c6ba806a";
      version = "2.0.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "buddy-sign/buddy";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "buddy-sign";
      groupId = "buddy";
      sha512 = "b71ca0c8e70c2498b043d2f303791305d9aeb9e41c7dfee0c5f11522206efb7db527ffaf8abc0d068325375235fc93fe32bd34102e807a3a79ac5c267764481b";
      version = "3.4.333";
      
    };
    paths = [ src ];
  }

  rec {
    name = "closure-compiler-unshaded/com.google.javascript";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "closure-compiler-unshaded";
      groupId = "com.google.javascript";
      sha512 = "bb71ff0784f0151ff6b5ab15e7ee576493eada86a4f9f784befccdc50c8edb27fa6c999330a5c55412fe3fd4f09034fde2bb9c3a45123ce1109a7f3c1d4deff4";
      version = "v20210808";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reactor-core/io.projectreactor";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "reactor-core";
      groupId = "io.projectreactor";
      sha512 = "a22a37200a1d05c7f8b977edc44c625845124eef8811f3699eb0a11ac5165128e603a99f6cfd523efdb852bacb98b728ae1b32a07833c0eb342483a1ffe7e9b5";
      version = "3.3.22.RELEASE";
      
    };
    paths = [ src ];
  }

  rec {
    name = "test.check/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "test.check";
      groupId = "org.clojure";
      sha512 = "b8d7a330b0b5514cd6a00c4382052fab51c3c9d3bc53133f8506791fa670e7c5ecd65094977ea5ced91f59623b0abd1ab8feeec96d63c5c6e459b265a655c577";
      version = "1.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "org.eclipse.sisu.inject/org.eclipse.sisu";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "org.eclipse.sisu.inject";
      groupId = "org.eclipse.sisu";
      sha512 = "f4790768c0d958b3429a3241abb15f9bb6e2fd7f43a5e034dde6a3a6820e6941c00f10ad084d5c38f8edc144e7acbea7ba3dc8952f01dab41e443803db2a4efc";
      version = "0.3.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-util/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-util";
      groupId = "org.apache.maven.resolver";
      sha512 = "45bd05eee2e2e606155916ec06efdb62e4a147af7ed0bb0b443b2a71b72576fec8e0ced0eee3ae3c86778198de227c1c7fe5d423cff0b96ba382fb563239694a";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm-analysis/org.ow2.asm";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "asm-analysis";
      groupId = "org.ow2.asm";
      sha512 = "6f40139d81934ee67af8f9d35ebe1415ad8641a3c667dbf38af8d8b17160198b1eb7edf11add986afaa495352966866c64928cbba23273ab83d4f2c5a93d5130";
      version = "9.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-api/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-api";
      groupId = "org.apache.logging.log4j";
      sha512 = "48a58c2f317d451ac1622bdfbfa5d3cd9de45d40d5d5df98f39fe6d53c74da56e200f8e3d19a309d4e1ea364369379c0ef9d79b928fc20ea743857f347259c03";
      version = "2.17.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "netty-nio-client/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "netty-nio-client";
      groupId = "software.amazon.awssdk";
      sha512 = "2f2de66c87385f857cdb79ba66f19bafc1c93f5a9b7f043f2eb144beca2ca50af7a1e67e2a77b8e953e8ed7523777cfd3dcc42d8514e8000228a6794ec5db713";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  rec {
    name = "mockery/mockery";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "mockery";
      groupId = "mockery";
      sha512 = "86c9e9c8408fbc8c3e971f14d5c6bdf03d09aeaebc80819ed96a639da54fe63c82382f2fa7e15297352a361e21399a5a6e59d23ffc92f1f09692f552dfa2d5de";
      version = "0.1.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jakarta.activation/com.sun.activation";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jakarta.activation";
      groupId = "com.sun.activation";
      sha512 = "d1c214d2d6ecc61bba396d913c66c977418e74dfe96e5558951ccf99a60cfca6adfea3fc64b6e2d15f698e30dac870b8f6e8d7a22e0dff975f8dd83864714fc5";
      version = "2.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jsonista/metosin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jsonista";
      groupId = "metosin";
      sha512 = "cdc3f005af6ef8821f6d1d26d6d1cc8300b608d1b8f0e5b6cb54e8f3376506d80e76ebc5818a31c6fa767d5c2561a900b96b5e5e174ce56d9f372f59395b28b1";
      version = "0.3.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "uri/lambdaisland";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "uri";
      groupId = "lambdaisland";
      sha512 = "48b803d913a5698192606de00802304479e5f1b1790dba5368c41ba288b84e9c899fbf4196ba10ecc36d386f8f30b680b463e4100bca6d0fabbabd5d91b8f19f";
      version = "1.13.95";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.memoize/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.memoize";
      groupId = "org.clojure";
      sha512 = "67196537084b7cc34a01454d2a3b72de3fddce081b72d7a6dc1592d269a6c2728b79630bd2d52c1bf2d2f903c12add6f23df954c02ef8237f240d7394ccc3dde";
      version = "1.0.253";
      
    };
    paths = [ src ];
  }

  rec {
    name = "camel-snake-kebab/camel-snake-kebab";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "camel-snake-kebab";
      groupId = "camel-snake-kebab";
      sha512 = "589d34b500560b7113760a16bfb6f0ccd8f162a1ce8c9bc829495432159ba9c95aebf6bc43aa126237a0525806a205a05f9910122074902b659e7fd151d176b1";
      version = "0.4.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-repository-metadata/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-repository-metadata";
      groupId = "org.apache.maven";
      sha512 = "67f0a5048054e8cf03c608fc846021a3be64b6733595260ccd46796673b2abdebb5afedd9599f7060fb560932e16c6f7637281969a1e7b43d352fde0b99945f3";
      version = "3.8.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "unboundid-ldapsdk/com.unboundid";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "unboundid-ldapsdk";
      groupId = "com.unboundid";
      sha512 = "7e7ad070d968fc4383a13f0206c1774330922412c1115d4dae240b223fb55a05e739a41069ec7cf3ae2f95406974d83fa48516c7c024369d828ccc8c6db75c8c";
      version = "5.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.priority-map/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.priority-map";
      groupId = "org.clojure";
      sha512 = "bb8bc5dbfd3738c36b99a51880ac3f1381d6564e67601549ef5e7ae2b900e53cdcdfb8d0fa4bf32fb8ebc4de89d954bfa3ab7e8a1122bc34ee5073c7c707ac13";
      version = "1.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "java.data/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "java.data";
      groupId = "org.clojure";
      sha512 = "225e1eafd1a659278212d831f7cd8609359f8c880ef3d69b4ade6301ce3c511307ce31d94cb82d5407314b990bd04714ec26273bb3036b248116a7a75fa75e1f";
      version = "1.0.95";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jakarta.mail/com.sun.mail";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jakarta.mail";
      groupId = "com.sun.mail";
      sha512 = "364b705fe3e51b1a612f7812cd4e57cff3b6ed844ca3566c206195d6512664661b0fcc138ecd2284ee33855fa378a4296842668fc66e3447d5dc5a1fc3e9c43d";
      version = "2.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-server/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-server";
      groupId = "org.eclipse.jetty";
      sha512 = "f460edd02c156bb3d60afc1c65a035294680b9df88d010e2c3382c75727d721c5a82b0b5eecfcb7858de78c57cd038f097c21d0795c81ad7f23bc9f74dffb2cd";
      version = "10.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "aopalliance/aopalliance";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "aopalliance";
      groupId = "aopalliance";
      sha512 = "3f44a932d8c00cfeee2eb057bcd7c301a2d029063e0a916e1e20b3aec4877d19d67a2fd8aaf58fa2d5a00133d1602128a7f50912ffb6cabc7b0fdc7fbda3f8a1";
      version = "1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-builder-support/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-builder-support";
      groupId = "org.apache.maven";
      sha512 = "a9dccb93c090840112045e605a4777bc41fe04fe7e518148095ec31078c6d87c8fae312aefd6d35cc1475fd622b361d7010251735c738ccef85b3f42e8c13f1a";
      version = "3.8.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jsr305/com.google.code.findbugs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jsr305";
      groupId = "com.google.code.findbugs";
      sha512 = "bb09db62919a50fa5b55906013be6ca4fc7acb2e87455fac5eaf9ede2e41ce8bbafc0e5a385a561264ea4cd71bbbd3ef5a45e02d63277a201d06a0ae1636f804";
      version = "3.0.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ring-core/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-core";
      groupId = "ring";
      sha512 = "38d7214a3fc1b80ab55999036638dd1971272e01bec4cb8e0ee0a4aa83f51b8c41ba8a5850b0660227f067d2f9c6d75c0c0737725ea02762bbf8d192dc72febe";
      version = "1.9.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.cache/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.cache";
      groupId = "org.clojure";
      sha512 = "0a07ceffc2fa3a536b23773eefc7ef5e1108913b93c3a5416116a6566de76dd5c218f3fb0cc19415cbaa8843838de310b76282f20bf1fc3467006c9ec373667e";
      version = "1.0.225";
      
    };
    paths = [ src ];
  }

  rec {
    name = "meta-merge/meta-merge";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "meta-merge";
      groupId = "meta-merge";
      sha512 = "079339d69a18e88a7cf5ce37e29bf7d9b25c93011866fac3012b11444f9e3d69f4dc017a3e88ad20faa790b38e343e0b71e9e11c44028434da3f368f377e4458";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm-tree/org.ow2.asm";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "asm-tree";
      groupId = "org.ow2.asm";
      sha512 = "99291fbf7acb7589cc8426e6cfb22bdd99c0b14c9f2c96843f47cb0cdc2d2f2004a2400c80723562721f5f399a42eeb4d2d4b874c484b0dde974a5f1fa9b7639";
      version = "9.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "rewrite-cljs/rewrite-cljs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "rewrite-cljs";
      groupId = "rewrite-cljs";
      sha512 = "fbf678ff7828ffa8e930730fa28c2149380f80d3c9dab69a5fbdcadb2b47c609df3f43fa992f546e900d6143ef92f44e076402dfd702cf64a0a538b29a34220b";
      version = "0.4.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-plugin-api/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-plugin-api";
      groupId = "org.apache.maven";
      sha512 = "f3e8881e3ecdba8725583a214f5133fa23aafcb306b0ae43b20f438c483be446a205841e473eb04d641a84dd1ac3647ff1bd25f0ce1b094b9e975a0f7e3758a2";
      version = "3.8.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.async/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.async";
      groupId = "org.clojure";
      sha512 = "160a77da25382d7c257eee56cfe83538620576a331e025a2d672fc26d9f04e606666032395f3c2e26247c782544816a5862348f3a921b1ffffcd309c62ac64f5";
      version = "1.5.648";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-dataformat-smile/com.fasterxml.jackson.dataformat";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-dataformat-smile";
      groupId = "com.fasterxml.jackson.dataformat";
      sha512 = "69676964a2b09516b8ffd0d847b6f9a9b843424185453731b548c25e7e9ce30e808c56d66923f9183e2b5c1ba007421b146a6806e768b8e6b07470d60227f1dd";
      version = "2.12.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-datatype-jsr310/com.fasterxml.jackson.datatype";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-datatype-jsr310";
      groupId = "com.fasterxml.jackson.datatype";
      sha512 = "017ac3714d9e53326e1bb8e210f57f5533bb8c366db9a0e2ad8d1a1c09fa3c4140971b85baa2c8b6cf59ca9c200adcb541c0a3da453b662339aff7400b8936c9";
      version = "2.13.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-artifact/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-artifact";
      groupId = "org.apache.maven";
      sha512 = "eae74088cf0ef66ff6cecd5ce6cf476e3df39e167988c1efbaa17f3c88fe55c59451125678cd041517702eb865190cdff64e691313f99c2e2f316e3e1c8a9daf";
      version = "3.8.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.codec/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.codec";
      groupId = "org.clojure";
      sha512 = "c324b62a5f14b2f17e49f1b0fffa3f44d195cb5261e03c5e472ba4f2972135f4b06fd321c0887717c727f025fc1a0121283d16fbf923d7469856702614a288f3";
      version = "0.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jaxb-api/javax.xml.bind";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jaxb-api";
      groupId = "javax.xml.bind";
      sha512 = "0c5bfc2c9f655bf5e6d596e0c196dcb9344d6dc78bf774207c8f8b6be59f69addf2b3121e81491983eff648dfbd55002b9878132de190825dad3ef3a1265b367";
      version = "2.3.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "gson/com.google.code.gson";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "gson";
      groupId = "com.google.code.gson";
      sha512 = "5dd7214c542a7b93aab3eab0ba13e4ac3d6ddb05c795fb6d3992e21925a98dce87cb186ac67b4d3ad146f96e14d38b3892837eca57a27b4e845aca6d4e4f708a";
      version = "2.8.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "annotations/software.amazon.awssdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "annotations";
      groupId = "software.amazon.awssdk";
      sha512 = "6153f0c387d2349bf027ae317a24ca22a85895bd7dfe902d3a3d16e142afcd5c8cf29fd14a039820e0106601bf96ca9593bfec7ddc7b662128d4e7bad0ceb809";
      version = "2.17.122";
      
    };
    paths = [ src ];
  }

  ];
  }
  