# generated by clj2nix-1.1.0-rc
{ fetchMavenArtifact, fetchgit, lib }:

let repos = [
        "https://repo1.maven.org/maven2/"
        "https://repo.clojars.org/" ];

  in rec {
      makePaths = {extraClasspaths ? []}:
        if (builtins.typeOf extraClasspaths != "list")
        then builtins.throw "extraClasspaths must be of type 'list'!"
        else (lib.concatMap (dep:
          builtins.map (path:
            if builtins.isString path then
              path
            else if builtins.hasAttr "jar" path then
              path.jar
            else if builtins.hasAttr "outPath" path then
              path.outPath
            else
              path
            )
          dep.paths)
        packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}:
       if (builtins.typeOf extraClasspaths != "list")
       then builtins.throw "extraClasspaths must be of type 'list'!"
       else builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});
      packageSources = builtins.map (dep: dep.src) packages;
      packages = [
  rec {
    name = "transit-java/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-java";
      groupId = "com.cognitect";
      sha512 = "660d4f034af67793ec53f00c661e57dd94817a3d1ab978163fe6289e06f16fe3f8431496c8e4eff1b9729cc2c47e906b6afb933605034fc2b64829c33fb47d99";
      version = "1.0.343";
      
    };
    paths = [ src ];
  }

  rec {
    name = "javax.inject/javax.inject";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javax.inject";
      groupId = "javax.inject";
      sha512 = "e126b7ccf3e42fd1984a0beef1004a7269a337c202e59e04e8e2af714280d2f2d8d2ba5e6f59481b8dcd34aaf35c966a688d0b48ec7e96f102c274dc0d3b381e";
      version = "1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "selmer/selmer";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "selmer";
      groupId = "selmer";
      sha512 = "c1eec23309037ad83b056cfb45fba1cfb9b8f0c5833783f09384cf91335730b40ae5845b8cfbf3e1b2cfc4b854581e1c4027f91ca803d924a7fa1f624f679b11";
      version = "1.12.40";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.json/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.json";
      groupId = "org.clojure";
      sha512 = "04b7c0c90cb26d643a0b3e7e1ffa2d2d423e977c1454ee5ea7c2e75547ecbc113838df17b797902a975f5ea2184a81a45b605a4d82970805e2bbb02feebc578d";
      version = "2.4.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clojure/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "4bb567b9262d998f554f44e677a8628b96e919bc8bcfb28ab2e80d9810f8adf8f13a8898142425d92f3515e58c57b16782cff12ba1b5ffb38b7d0ccd13d99bbc";
      version = "1.10.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "shadow-cljsjs/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-cljsjs";
      groupId = "thheller";
      sha512 = "3d0b79eff075c38389d9f3501c60bf91a28a6ee25fc0a2df3159b365eff556e2ec8499b69860783478705ea33ff18e85fc0150229d5725e58e96f362bdc777f1";
      version = "0.0.22";
      
    };
    paths = [ src ];
  }

  rec {
    name = "pathom/com.wsscode";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "pathom";
      groupId = "com.wsscode";
      sha512 = "56e2125d20f6704f802830f0698e90889fcbd9a315d1835141b132303f7b3043277ded8d120037b09d4b90f7e73adf03a89e0017277a7e018cbedaee30ad909c";
      version = "2.2.31";
      
    };
    paths = [ src ];
  }

  rec {
    name = "icu4j/com.ibm.icu";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "icu4j";
      groupId = "com.ibm.icu";
      sha512 = "07d14b637c4a2975f44d0d70eb8b85ed7b4fa33ba2254a4774b0a3474de20c3ccd5530439a9f2a12a38437400ba361f52a07c4f1c3b7a771798cf9139d7f8ae7";
      version = "68.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-codec/commons-codec";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-codec";
      groupId = "commons-codec";
      sha512 = "da30a716770795fce390e4dd340a8b728f220c6572383ffef55bd5839655d5611fcc06128b2144f6cdcb36f53072a12ec80b04afee787665e7ad0b6e888a6787";
      version = "1.15";
      
    };
    paths = [ src ];
  }

  rec {
    name = "api/com.cognitect.aws";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "api";
      groupId = "com.cognitect.aws";
      sha512 = "31d6275364e92e1d9f6e3810cd64e6f64421a3965314a5f61902c9a797808901f118f01e05dfe0bc2d4e2288432b264c8197aa5847289a46452ed4bb24e14fd5";
      version = "0.8.536";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.analyzer/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.analyzer";
      groupId = "org.clojure";
      sha512 = "c51752a714848247b05c6f98b54276b4fe8fd44b3d970070b0f30cd755ac6656030fd8943a1ffd08279af8eeff160365be47791e48f05ac9cc2488b6e2dfe504";
      version = "1.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "cljs-test-display/com.bhauman";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cljs-test-display";
      groupId = "com.bhauman";
      sha512 = "d8aafc0214bb3719adbb2c957e6a7c939e0db65a0bf69c4369654f736882c3203a4eeb66670e1da18f60faa8bf97b094712472ce883a5a1a5f8dd52b8e413d96";
      version = "0.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-component-annotations/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-component-annotations";
      groupId = "org.codehaus.plexus";
      sha512 = "cc534fda54272f074fe9edd581a6c3e1ea98127340c7f852c4b4953a44dad048ace22dfa10f30d6adcdfc15efd319dac778a03ebbe20de7779fd1df640506e88";
      version = "2.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "endpoints/com.cognitect.aws";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "endpoints";
      groupId = "com.cognitect.aws";
      sha512 = "c5ea8379bd1d2bec5696f1b564781eaee5f00d477566613b01bd45d499ea856f850b5511cc4217fe5e39b3a88e755f8a1d80b79142c2324d140e067ac021ef7b";
      version = "1.1.12.93";
      
    };
    paths = [ src ];
  }

  rec {
    name = "error_prone_annotations/com.google.errorprone";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "error_prone_annotations";
      groupId = "com.google.errorprone";
      sha512 = "bd2135cc9eb2c652658a2814ec9c565fa3e071d4cff590cbe17b853885c78c9f84c1b7b24ba736f4f30ed8cec60a6af983827fcbed61ff142f27ac808e97fc6b";
      version = "2.1.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-lang3/org.apache.commons";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-lang3";
      groupId = "org.apache.commons";
      sha512 = "fb0fe98385496a565678a000c26a3245082abfbf879cc29a35112b4bf18c966697a7a63bb1fd2fae4a42512cd3de5a2e6dc9d1df4a4058332a6ddeae06cdf667";
      version = "3.8.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.logging/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.logging";
      groupId = "org.clojure";
      sha512 = "af7fd2d53c589de7f29ed9568d14a3cd23d6276595eb73043c7b96785ce5f470e8d3ac8934963aee241b5251936cad6c88f41fce66c4927b28318c0bdfbc5237";
      version = "1.2.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.specs.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "c1d2a740963896d97cd6b9a8c3dcdcc84459ea66b44170c05b8923e5fbb731b4b292b217ed3447bbc9e744c9a496552f77a6c38aea232e5e69f8faa627dea4b5";
      version = "0.2.56";
      
    };
    paths = [ src ];
  }

  rec {
    name = "javax.annotation-api/javax.annotation";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javax.annotation-api";
      groupId = "javax.annotation";
      sha512 = "2453330b27a0822bba440c28b98ae1d83d60d97dfa2d040562dd5126b3548e0caa040fea3b886ac6feb0a858e6c1bc45b6c5472b180f1f14792e5ca33e355959";
      version = "1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "eql/edn-query-language";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "eql";
      groupId = "edn-query-language";
      sha512 = "b3ddcd9bad0b9effa8a00add3041fbbde352f36c06d5491e139181160a459d0b71ad2b4b5e5903dea5dfaad9a86f6d7014e1ade3f06843632aa9cd358f062323";
      version = "0.0.9";
      
    };
    paths = [ src ];
  }

  rec {
    name = "undertow-core/io.undertow";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "undertow-core";
      groupId = "io.undertow";
      sha512 = "d1dcc1236ac98518318bea1ab99037c4f447d431319dc9fa8a9bc830c2c3cee0f7b804cfb5492e71e68e96a128f259059de8d6404237572c78643c8824818b9b";
      version = "2.2.4.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "js/org.graalvm.js";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "js";
      groupId = "org.graalvm.js";
      sha512 = "30d24adb24db2fc67fcc06d2adb7a3603c439d98a427a034d903b80ff44f27260262ef7b4a7762473443f3068089583217b6c1459593a7e68225cb206608e676";
      version = "21.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-databind/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-databind";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "2e7b06d78565254718954ad5ca180476ac4327a4ddd8e07d84a5cb52c55d81870cdcfd08bd54ee984e75b4b7c30e21a9100962cda6275f16106357b7cca4478f";
      version = "2.12.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "expound/expound";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "expound";
      groupId = "expound";
      sha512 = "19fc1c525247edd4bbcdb206452e67021ec7f787eed82dfcd017189c6d30048a9884259ffefd15feb26555fb2ef559be05a0cbe59c5af3e0850f95e2fde5ff05";
      version = "0.8.9";
      
    };
    paths = [ src ];
  }

  rec {
    name = "spec.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "0740dc3a755530f52e32d27139a9ebfd7cbdb8d4351c820de8d510fe2d52a98acd6e4dfc004566ede3d426e52ec98accdca1156965218f269e60dd1cd4242a73";
      version = "0.2.194";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.cli/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.cli";
      groupId = "org.clojure";
      sha512 = "1d88aa03eb6a664bf2c0ce22c45e7296d54d716e29b11904115be80ea1661623cf3e81fc222d164047058239010eb678af92ffedc7c3006475cceb59f3b21265";
      version = "1.0.206";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clj-uuid/danlentz";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-uuid";
      groupId = "danlentz";
      sha512 = "10c0ba460baadda446b1291423185e25e5a1bd82eb3ed82b0ee589f3e15bbe3f3a2c679767c228e01316ef27aaf60b7c1bceacef78f5604b7a11efe99207c227";
      version = "0.1.9";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-fileupload/commons-fileupload";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-fileupload";
      groupId = "commons-fileupload";
      sha512 = "a8780b7dd7ab68f9e1df38e77a5207c45ff50ec53d8b1476570d069edc8f59e52fb1d0fc534d7e513ac5a01b385ba73c320794c82369a72bd6d817a3b3b21f39";
      version = "1.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "animal-sniffer-annotations/org.codehaus.mojo";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "animal-sniffer-annotations";
      groupId = "org.codehaus.mojo";
      sha512 = "9e5e3ea9e06e0ac9463869fd0e08ed38f7042784995a7b50c9bfd7f692a53f0e1430b9e1367dc772d0d4eafe5fd2beabbcc60da5008bd792f9e7ec8436c0f136";
      version = "1.14";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-http/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-http";
      groupId = "org.eclipse.jetty";
      sha512 = "712ada0e464a88366285260824846262ed720d777fb0f83aa34942b0ec9583a2ca8dbc393bc2acd59f5441a60f2de5d3c0cad16658983bf31ef058810dbf8427";
      version = "9.4.44.v20210927";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-util/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-util";
      groupId = "org.eclipse.jetty";
      sha512 = "7a5ad20662da63fc19c8cf0bd65c94dc00ac80625d8538619cf3ad9c7358a0225a933cd1ca408017a1869267938b3cdfd30f075fc3364ed6cf384d19b3c0ac8d";
      version = "9.4.44.v20210927";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.zip/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.zip";
      groupId = "org.clojure";
      sha512 = "c8292624d89ad67c336230870bffcdb19c018e0607ad76cf52c6ec2975791b22a08a8d840d36135edbda78c67c6d1d1e39d3024820598c932efda7d3dfc3e46f";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jcl-over-slf4j/org.slf4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jcl-over-slf4j";
      groupId = "org.slf4j";
      sha512 = "aed539305114718bd76da54f29a391362eb331108d9c033956bf68df29c62a44874c73ae39d19a25342625b6092326d39b4d8720aed6c62234a234e0855b00b5";
      version = "1.7.30";
      
    };
    paths = [ src ];
  }

  rec {
    name = "regex/org.graalvm.regex";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "regex";
      groupId = "org.graalvm.regex";
      sha512 = "9452d658af35f9fe061b39285c252d70015c94fd2ac77a75d0fdb92ff6c447564a90b199832e09ce03f55bd233f008d61814a10040d373432feabade8f8be92a";
      version = "21.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.analyzer.jvm/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.analyzer.jvm";
      groupId = "org.clojure";
      sha512 = "ac9aac0d14fd92a66cd9c7bbf8ea8df92116eba5dc7f4819e38ec1b334ee0997fe8be57781300e4d78a6dd138cc8e2041e7d1511198c3f49cd43219444e5f3ec";
      version = "1.2.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "wildfly-common/org.wildfly.common";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "wildfly-common";
      groupId = "org.wildfly.common";
      sha512 = "f99f23af23a1cc45035b87ab422affdb911769ee63dc5a1c9b3e7a39ebefee07542d2388118282b20113c196e28abce8f87cafc8b0213cdc692381edce035c46";
      version = "1.5.2.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-jul/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-jul";
      groupId = "org.apache.logging.log4j";
      sha512 = "5e9a12caa1bb1aebef7c0b93d23262987e687ba039bbe48ecb5ad77f749935eb51d70bb9acde46aee117de691cd54481dcd48d4742014f1a8a476a7f71b11937";
      version = "2.17.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-transport-http/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-transport-http";
      groupId = "org.apache.maven.resolver";
      sha512 = "0650fdfa290cfa43e7d723d1092743016d8b2bb4fad825ef93e43e4ce687d41310967015e6faa14a0d3fcaac75cc8916a4b50053d77a60686d2d3fa6e51e9976";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "json-simple/com.googlecode.json-simple";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "json-simple";
      groupId = "com.googlecode.json-simple";
      sha512 = "f8798bfbcc8ab8001baf90ce47ec2264234dc1da2d4aa97fdcdc0990472a6b5a5a32f828e776140777d598a99d8a0c0f51c6d0767ae1a829690ab9200ae35742";
      version = "1.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-cljs/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-cljs";
      groupId = "com.cognitect";
      sha512 = "526d3331857586ab7e8edb78795c375aaafe6dc3da24706663918a7dc38e25db7d0f554c334ec3be0334050d59d8616bd9cd6c9a90cf4bb4b33b1e0ea294d29c";
      version = "0.8.269";
      
    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library";
      groupId = "org.clojure";
      sha512 = "cf74661c5bc4658674397e498366ed12ce8b6f6cf51cdfa4cd0ce99415203028ec0bc4b59032a73ad4bf29421a643b2e6799fcd8a35f4f1e8676b3c04900a0b3";
      version = "0.0-20201211-3e6c510d";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-model-builder/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-model-builder";
      groupId = "org.apache.maven";
      sha512 = "31ce438801c4e402dce94a11661da33598888189a478a7d4019cb1e5a1ba9ed99ba527812491728e41382b8fc9c726dbf2d574c3fe1851d71d5c19ddc3083eeb";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "pretty/io.aviso";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "pretty";
      groupId = "io.aviso";
      sha512 = "416433ae5c5773a3a12e7cff3f75a43f1a2d3f4454aad04d065c1e4e13627130f289dbb41355a5665236082b6535939fc4c40a2fddcc22a40d0d4ba290544bfb";
      version = "1.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "shadow-cljs/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-cljs";
      groupId = "thheller";
      sha512 = "6a15bc6d13014aad25b468e3651c5c6bad14f122367555bd224f7172a2d76c015b549681c82d3d4d75ab375f019c4bb0c4b0aed230e5fcc1e199be53e5f0bb36";
      version = "2.15.10";
      
    };
    paths = [ src ];
  }

  rec {
    name = "graal-sdk/org.graalvm.sdk";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "graal-sdk";
      groupId = "org.graalvm.sdk";
      sha512 = "fca71a38aa19f0125d99cb67fb9f353261e4f99680f4e0208f29e0c3f37a2db886cff26f9c659dbec59b0650b49bd38f8fbc253bd5d90ae656ce1a07c64eb9b2";
      version = "21.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "rewrite-clj/rewrite-clj";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "rewrite-clj";
      groupId = "rewrite-clj";
      sha512 = "6e878952f453d7b6df9dd47db977623b59e6d9f6965f67b463c35e0457e45baf298378ae175b0be61c11d38e0906334e2f2862bcf3dfba60d947a2ce4c2a2fc9";
      version = "1.0.699-alpha";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-cipher/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-cipher";
      groupId = "org.codehaus.plexus";
      sha512 = "8f187b07867a7c29d77454aae4b76479300238d9c4e777c1afa2aebe33b88dab916e29111dd55acac1341849f4579fe91a5470fdd45ccba0e05709c2ce3a1d65";
      version = "2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clojurescript/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojurescript";
      groupId = "org.clojure";
      sha512 = "51b9fa134f00514573996d4048b91362674d0d013aa163a639156510de92ceea0c2f26b5bf6532956b52f61fa160ca466192882209bb525fdb9af1ff7a7057ab";
      version = "1.10.879";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-utils/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-utils";
      groupId = "org.codehaus.plexus";
      sha512 = "0668d413520a713d9279123eccae3b5e9bc79f41dd8da3b3a1ba79b7b60086c009639d91d84df230e490192fe63b10390f3901478c69bfd452a1280364d24876";
      version = "3.4.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-transport-file/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-transport-file";
      groupId = "org.apache.maven.resolver";
      sha512 = "8037285f888cf37cc3563528bedb3171a3987750b137ff2c6f77e6ed25fcd0d84be3aa80bebd283bfd5decfb8c55452e701f513a2f4e89ac765cb683b332e87a";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "org.eclipse.sisu.plexus/org.eclipse.sisu";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "org.eclipse.sisu.plexus";
      groupId = "org.eclipse.sisu";
      sha512 = "38d7dbe023f9751cb5e30bf154e31696590317dc7b7f768811fe0f5940513fcea4665670cd47d0b72ded85453b10f7d129b0b7428b155a41c903c7b56c986e8d";
      version = "0.3.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ordered/org.flatland";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ordered";
      groupId = "org.flatland";
      sha512 = "676db4c71999127822349f5f97960115aa5f3124eb3a93b441680c5ba747ebc1981718f93e8dc94fe34f0c1c84ea3568c452691967b92509e5e125dac3ee59eb";
      version = "1.5.9";
      
    };
    paths = [ src ];
  }

  rec {
    name = "spec-coerce/spec-coerce";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "spec-coerce";
      groupId = "spec-coerce";
      sha512 = "76fded8a8f1d597b4dc91900b66957b4a717bf61d3c92a61bcdc107d7ad9d3384affda89a396d692a86f540e88ec5a7f37570e82ec833708e81a529d4daa6776";
      version = "1.0.0-alpha6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-io/commons-io";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-io";
      groupId = "commons-io";
      sha512 = "6af22dffaaecd1553147e788b5cf50368582318f396e456fe9ff33f5175836713a5d700e51720465c932c2b1987daa83027358005812d6a95d5755432de3a79d";
      version = "2.10.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-settings-builder/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-settings-builder";
      groupId = "org.apache.maven";
      sha512 = "6edfc7281dbb75596c6d87bcfa38b120539eb3e99e85a8763a06b27e90778b59032191b4380b3630e37e68599ef9092d04fa8ab823d9ffecd1ed45af3d9c302e";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "fipp/fipp";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fipp";
      groupId = "fipp";
      sha512 = "4697699e9d5b792998e8c7ab6bf08d0d84c3e88793a0ff7024c10105f0db5703bccca9c43bb7fea00c1621af0d0604c89d623d74fde771a0d2e17835e1ab87b7";
      version = "0.6.24";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jboss-logging/org.jboss.logging";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jboss-logging";
      groupId = "org.jboss.logging";
      sha512 = "c17b8882481c0cb8fbcdf7ea33d268e2173b1bfe04be71e61d5f07c3040b1c33b58781063f8ebf27325979d02255e62d1df16a633ac22f9d08adeb5c6b83a32a";
      version = "3.4.1.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "spec-inspec/com.wsscode";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "spec-inspec";
      groupId = "com.wsscode";
      sha512 = "6ddd3a1ae290be719f8ea235d962352a7949c38fe404cf43d45e6b975635f13f53525790d77bce5543151daeadea51849499a157ea541ac0c4aa761f040c1636";
      version = "1.0.0-alpha2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-core/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-core";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "bbbc4fba33448854627f9764b1e086370e607b29819884415f21d1943243b0bddc781d71d56021dea52386f1b230a344f852dc3ea0e904559b95ca60e03068ca";
      version = "2.12.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "snakeyaml/org.yaml";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "snakeyaml";
      groupId = "org.yaml";
      sha512 = "dce610268daab6fd6bac54f819f2f5795b17a57792b0f5553ee72acfbe8b9f81367ba7419655be8348369eb489259b14ddab7cea7a0c3c1b193bd62e0715cfd3";
      version = "1.26";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm/org.ow2.asm";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "asm";
      groupId = "org.ow2.asm";
      sha512 = "40614e658138f2eb95bc26999545f996794c622c4d68efb9e10093743504c4b58bf22590767bc6bd93b77cdfb202c507144ba867bbc8b54d74fe7621cbc55e3a";
      version = "5.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-settings/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-settings";
      groupId = "org.apache.maven";
      sha512 = "9135e9a135a47a6456650c098908fc4ebfe6c978c7ada08d6509834d9b5abdcaadff1e9024c9372c1e0dded4f23a98f22e261c8d5d7f8ebd306e6c4538962ec0";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-core/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-core";
      groupId = "org.apache.logging.log4j";
      sha512 = "e28fa0f1cbac0d925055b4c89de3c1f7293a001574b8479b7ae912dff051ed35477847509d70586a3b7637f0f529f701235766abdfc755f261a2aaf6dc2a70b8";
      version = "2.17.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "httpcore/org.apache.httpcomponents";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "httpcore";
      groupId = "org.apache.httpcomponents";
      sha512 = "23430cde8b9bed33c91474ba49f1143284135df1b25fdcbc37bc3bb7e9549e77b3918eb40250093db652ae200367e87316129b23b4f6987e94939d60f467498d";
      version = "4.4.13";
      
    };
    paths = [ src ];
  }

  rec {
    name = "shadow-util/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-util";
      groupId = "thheller";
      sha512 = "803a068159276f5abf6d9cfa25f5c446c4c66d2eaec78393910cb2175b63a734c7c7effaf3064789608b1cf3899c287611c2d170fd78621193acc1fbbff1d5da";
      version = "0.7.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "primitive-math/primitive-math";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "primitive-math";
      groupId = "primitive-math";
      sha512 = "02fd7cabe27cbb11a944059b1b5261ed089f3e5c641246da6d5a2ab2a6afd3d33c9fb1300f948255f4958551f91b93c5fd930bc3d657cbb9c95fb05bf0a238b9";
      version = "0.1.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-sec-dispatcher/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-sec-dispatcher";
      groupId = "org.codehaus.plexus";
      sha512 = "ad4e814c8baff780a4eee064903e52b09ae00420a59fb075ef72dbb8d64d12d3d5009b03d56c15f93587d931c3a7f06cad6351ab2dc9415ccc6eeab0daebeb07";
      version = "2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-core/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-core";
      groupId = "org.apache.maven";
      sha512 = "f786dfde86ece3208a96f652ab2994de6b0975945a6e981900a137b6b7ad89c9d52ab05f82acf4f59872ee75a404e817bd9774f052a294b9792964252b06c5d9";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-web/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-web";
      groupId = "org.apache.logging.log4j";
      sha512 = "dd9ed3baec6a8eb81fe75e56d66ce535f074cbb0d5fb1cf416127b8dde40a649e79669fad42a38bce1d1895cf45e25dff019d1bd470519a1e835c7e7a93c4eb7";
      version = "2.17.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-js/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-js";
      groupId = "com.cognitect";
      sha512 = "bab8c657449a1d01e884923b77c5ef3d7a1a246c3ad1bd85a5b0c98b7952dbdeea97ce7d340ab50aa0dca647a1ef7eb846a52a1a4eecc55e1ff22145b8e820fe";
      version = "0.8.874";
      
    };
    paths = [ src ];
  }

  rec {
    name = "directory-watcher/io.methvin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "directory-watcher";
      groupId = "io.methvin";
      sha512 = "25df4794b9d91bd4f2e79ba2b72cb6016ddfa984925c06443ad95a141589291b59c241cb6b5a401e6618134514ef06282f996f4e22d62f22c29f67c2ac766093";
      version = "0.15.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reitit-core/metosin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "reitit-core";
      groupId = "metosin";
      sha512 = "9419bf2ecab01acfd424fbea2d392498fd8287356d704bccf78d6bff074352647113c4d57baa9dd506f491c5c1bd378c6b99640176d192f545fc522241963530";
      version = "0.5.13";
      
    };
    paths = [ src ];
  }

  rec {
    name = "cuerdas/funcool";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cuerdas";
      groupId = "funcool";
      sha512 = "f52cfefdb9cf90cf43f51fae6d7e3e32e594f4cd2544afeff1a2487fddc5d4f8e986cdb2ba658aea6d8ee6034b3866cf1ee23c604d9c5f44d9cc6570c3519a0a";
      version = "2021.05.29-0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library-third-party/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library-third-party";
      groupId = "org.clojure";
      sha512 = "b0be9cdb227ce189d74a2c0e9fe8cfe53ae5608f0e00382c6c12b0087672c6caeb96890beefd9f285ca7e0c7e4bee760299e14d48512e3e37f1f274838a1693d";
      version = "0.0-20201211-3e6c510d";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-api/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-api";
      groupId = "org.apache.maven.resolver";
      sha512 = "002cb75f6e07b27108e79a4d37d94fa882e89a2db30dd2ac69ecf0907cc548e13f579ebfbb5c019da6df4a950e3420b69dac3d49ae94b5646b7968ef7ea811ca";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-annotations/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-annotations";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "5a1e45f0afe34eb36605b8763990f92ac5b4390432f058f682cf186bf3ba0f7325a67d4d35158ab22ac4fff025869722dd49365f19c47fc5f4c268f003ae773e";
      version = "2.12.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "hiccup/hiccup";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "hiccup";
      groupId = "hiccup";
      sha512 = "034f15be46c35029f41869c912f82cb2929fbbb0524ea64bd98dcdb9cf09875b28c75e926fa5fff53942b0f9e543e85a73a2d03c3f2112eecae30fcef8b148f4";
      version = "1.0.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "http-client/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "http-client";
      groupId = "com.cognitect";
      sha512 = "5507956051ce71d5f521537a443390d49be8fa629074fc19781d0e5e072207afa543ec690876eb895174d82b85810888eb839a0a3ee82ad3394244c7fb78e015";
      version = "1.0.110";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-provider/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-provider";
      groupId = "org.apache.maven";
      sha512 = "3ad268c56e63cbe87f8e6a9f16ac8260213a1567baef53fc7d69cca213fc479d9a543eae91fa1166c38cf88d8225c70f4f33a7064af3190f916b5f97fd8f35ad";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "javassist/org.javassist";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javassist";
      groupId = "org.javassist";
      sha512 = "ad65ee383ed83bedecc2073118cb3780b68b18d5fb79a1b2b665ff8529df02446ad11e68f9faaf4f2e980065f5946761a59ada379312cbb22d002625abed6a4f";
      version = "3.18.1-GA";
      
    };
    paths = [ src ];
  }

  rec {
    name = "checker-compat-qual/org.checkerframework";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "checker-compat-qual";
      groupId = "org.checkerframework";
      sha512 = "fdecc20efd6943426e7f8bdfb8bef9d28258f9f934cf29090e2f5b297c501454606cc28593cd7d089a5c14f6d2dcafc59f4606053405d7f91d623a0e3202f4a8";
      version = "2.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "linked/frankiesardo";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "linked";
      groupId = "frankiesardo";
      sha512 = "d47354631d642a603f1f64e1bd872f623d8e6e7a8c40e968bcf124681585920c423a51f3388f6a4101c5f346b3e10a17b7e256da617ca0d1f19a25169dac46f7";
      version = "1.3.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "xnio-nio/org.jboss.xnio";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "xnio-nio";
      groupId = "org.jboss.xnio";
      sha512 = "7f2c53222caf40793b1c956aa08ff3316a86577e6a79274050bcdf700b68546397b286e3d693c1b3036fe9175f54f76816cbf6a100ae67f9e6c20b4ca028e56d";
      version = "3.8.0.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-shared-utils/org.apache.maven.shared";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-shared-utils";
      groupId = "org.apache.maven.shared";
      sha512 = "c6693f8a061de74ac59c61d185f5b130cb574405cfc37febb8e73806ea64eea822a4a75c24098fb49b7871373091543a6f4c526c0842589e528cacad40e5554a";
      version = "3.3.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.deps.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.deps.alpha";
      groupId = "org.clojure";
      sha512 = "204ac11ea37e817e8dcd147b9cd6b05785c025af2733bb3f757b8cc2f4452beefe3bafba553633b8bfc848d613f986964187aee3486ee30adb413358ce57775c";
      version = "0.12.1090";
      
    };
    paths = [ src ];
  }

  rec {
    name = "environ/environ";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "environ";
      groupId = "environ";
      sha512 = "e318da117facf51a27b9ae39279363c4d824393215ce63fa69e5bdb65a910d1f8632d712598ad0c3f4248d0ab9274a97161859393d265d74d50ad2a4cdbddf41";
      version = "1.2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "guava/com.google.guava";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "guava";
      groupId = "com.google.guava";
      sha512 = "c8f95af9f1e97dee807503c8fbb442c87eed2694e43ad0fd9fc2e62ba99c5e93d476d5ee8f4791f173cb8fdabc88abac0e8130a51de280af836a3e0c4eadaff6";
      version = "25.1-android";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.xml/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.xml";
      groupId = "org.clojure";
      sha512 = "12ea6e7ee27be4a0329a766f3449f3e3b756772e3cd8588b4666bb175faaabd0780b96300b10e17ccb3016b0ba5d9f020c7d976211ff398e7bebef718aa4d5f5";
      version = "0.2.0-alpha6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "truffle-api/org.graalvm.truffle";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "truffle-api";
      groupId = "org.graalvm.truffle";
      sha512 = "a0247b4c15020d27d39e2840b24a56afafbd385957b4844c2a6d3def9e3ce584780667b5c46bda7a7243c60ee69fdc3bf220f19e86534304a5557c2559259088";
      version = "21.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-spi/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-spi";
      groupId = "org.apache.maven.resolver";
      sha512 = "2972b721213bfee654460468b2a2aa50546d7f1957be40d955728875af3a9801f8d78a2f796e832b9332d1f90ffb5ccb651289e7b5c8a175628b21b13594df43";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "devtools/binaryage";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "devtools";
      groupId = "binaryage";
      sha512 = "fde4c7373dabbcfd9d9a61e14271747876bea3085debaaef8a286efbab43d347f2b497883482997278223fcf2976b6a4256593225e246319b57744414458b9e7";
      version = "1.0.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-slf4j18-impl/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-slf4j18-impl";
      groupId = "org.apache.logging.log4j";
      sha512 = "99eea70960abbe3f672cfdb9dd235bdfb4abc0ae0c9cf3b3ae95d91f5c61800639756a0412426696d92f2316980f2f178994dcd83d229c288df4207f996ba0ab";
      version = "2.17.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "msgpack/org.msgpack";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "msgpack";
      groupId = "org.msgpack";
      sha512 = "a2741bed01f9c37ba3dbe6a7ab9ce936d36d4da97c35e215250ac89ac0851fc5948d83975ea6257d5dce1d43b6b5147254ecfb4b33f9bbdc489500b3ff060449";
      version = "0.6.12";
      
    };
    paths = [ src ];
  }

  rec {
    name = "js-scriptengine/org.graalvm.js";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "js-scriptengine";
      groupId = "org.graalvm.js";
      sha512 = "190222663af351d5a63d51c1aa414dacdd7e73f97339697fa3a439df5976f631f2731bbea258c577922d1ce2535332f46f331b8f3bca9296fd3bf3c20a948fa4";
      version = "21.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jboss-threads/org.jboss.threads";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jboss-threads";
      groupId = "org.jboss.threads";
      sha512 = "12d2b4c6c4f732a4b9437ae6e893087981aa2d829c9bad7089cd4cb10bccd7105e136f694e43a36e5bf234ca81294117fd9f6a07795f77c0f80d8f748c8fa529";
      version = "3.1.0.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "j2objc-annotations/com.google.j2objc";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "j2objc-annotations";
      groupId = "com.google.j2objc";
      sha512 = "a4a0b58ffc2d9f9b516f571bcd0ac14e4d3eec15aacd6320a4a1a12045acce8c6081e8ce922c4e882221cedb2cc266399ab468487ae9a08124d65edc07ae30f0";
      version = "1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "slf4j-nop/org.slf4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "slf4j-nop";
      groupId = "org.slf4j";
      sha512 = "f72969e1100136372f806fe820c700eae3dece6c364eab25d4c88b14085e2789ea43a2ce1efded114f98b67534c9305ce3d43d3fd4a1b422148426aa27bd11e6";
      version = "2.0.0-alpha6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-clj/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-clj";
      groupId = "com.cognitect";
      sha512 = "efe5483c188c8e6fb7327e2b312424de920b913ec9ca89580fddceb2a964de4ce75aab79d7d3671bb362b9af73a9e25a331abd4f53ce544d9b50f83a1a07adf4";
      version = "1.0.324";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-classworlds/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-classworlds";
      groupId = "org.codehaus.plexus";
      sha512 = "6a58048d9db54e603b9cfd35373cf695b66dd860bec878c663b4fc53b6b3d44dd5b0c92e7603654911b1f78e63ef277cf6b272fe069a360989138550545f274d";
      version = "2.6.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "crypto-random/crypto-random";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-random";
      groupId = "crypto-random";
      sha512 = "3520df744f250dbe061d1a5d7a05b7143f3a67a4c3f9ad87b8044ee68a36a702a0bcb3a203e35d380899dd01c28e01988b0a7af914b942ccbe0c35c9bdb22e11";
      version = "1.2.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clj-yaml/clj-commons";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-yaml";
      groupId = "clj-commons";
      sha512 = "b6cfdd848431eff4df30cf27e644440c82b18a316d813d1ef620f80102d8d47973b33c9b6c46bc187c5800da939ef47cd0e43602e15c65c8f19e9abb82fb6d38";
      version = "0.7.107";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ring-codec/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-codec";
      groupId = "ring";
      sha512 = "38b9775a794831b8afd8d66991a75aa5910cd50952c9035866bf9cc01353810aedafbc3f35d8f9e56981ebf9e5c37c00b968759ed087d2855348b3f46d8d0487";
      version = "1.1.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "shadow-client/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-client";
      groupId = "thheller";
      sha512 = "b1f2ac82b31841d265af0939ecc0824e6ba8cc28d15b44c77f3abb305b5e88465b839915a222016c2ac8c7e2049d1daa2a3eebb9a58cdc9cf653bc56712b4ca7";
      version = "1.3.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "plexus-interpolation/org.codehaus.plexus";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "plexus-interpolation";
      groupId = "org.codehaus.plexus";
      sha512 = "6c3b40442adf721d325ee9cbf935d758223a04b3bd8e0f3b60fdb652175c1ca65a6010f7ea8288617ffa73cb1f19d2737c79c403d343b285e0f9afb1729caa60";
      version = "1.26";
      
    };
    paths = [ src ];
  }

  rec {
    name = "httpclient/org.apache.httpcomponents";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "httpclient";
      groupId = "org.apache.httpcomponents";
      sha512 = "18ce8b0cd1de30fa397d25b4bcf6760f82706ed00270ed0a1db17f25fab6a7795950a2df171f212c680fc145c2f1125992e184b8f303c97a6498471079fa97fe";
      version = "4.5.12";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.rrb-vector/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.rrb-vector";
      groupId = "org.clojure";
      sha512 = "7b6546bbd0ff8c7755382a5460029f57f562529ef66fc6ca473c4ba30d897ac5ff0aec8db737da9deeb732fccdd35c9c2317c256b7703e8e5804d1098e9bf77b";
      version = "0.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "crypto-equality/crypto-equality";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-equality";
      groupId = "crypto-equality";
      sha512 = "54cf3bd28f633665962bf6b41f5ccbf2634d0db210a739e10a7b12f635e13c7ef532efe1d5d8c0120bb46478bbd08000b179f4c2dd52123242dab79fea97d6a6";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "promesa/funcool";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "promesa";
      groupId = "funcool";
      sha512 = "7158b61538c58d673aa9f2b82a48b1abc99f5b1b87203d7e4475f9eb63a4f29745308ff01a532f91fb83c36d2e2ee21e37da26fcef757ff182ecfb0bd4237f9e";
      version = "6.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "java-http-clj/java-http-clj";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "java-http-clj";
      groupId = "java-http-clj";
      sha512 = "8da413f998d32378760f8e4638915d9e7f02f6377eeed4f874bd8de4335b497e796de50b301d17e1bd179a474d1554c6ba43c1da22dbd845ff866ccf0d710425";
      version = "0.4.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "wildfly-client-config/org.wildfly.client";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "wildfly-client-config";
      groupId = "org.wildfly.client";
      sha512 = "3f442478c57f7dfac7039f6c7ae014bb2d45cdbd690ee631a3349edbca414adfe1984d065d1439f9b1546fa15fbd032c3a6bfe008f1ad50eef74201467b9f55f";
      version = "1.0.1.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "glogi/lambdaisland";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "glogi";
      groupId = "lambdaisland";
      sha512 = "1f0f063933b82771877bf0b961c6dc3c95c90f1b79fddf891d3ed2369d83894b8cb891057f30f2629b63b25779e9f07e77cf8fdeaef0ebf51933ad15426dacdd";
      version = "1.0.106";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jna/net.java.dev.jna";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jna";
      groupId = "net.java.dev.jna";
      sha512 = "ee8d8aa63c67561880626a2f84412fb6996b411e065060cbe4669cc2b4e5537d09acd6d262e1924f0c066d76b18a2bd8a94e96f313b3ffd12f4735b8f6e06bb5";
      version = "5.7.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "guice/com.google.inject";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "guice";
      groupId = "com.google.inject";
      sha512 = "78f17b090f34564db0fa6903c966e79d8002903d2604f9605a0d713e770a9c772c11d615a5e112dbb15464b9f8945edff6ac3d23ac84ccb08eb1657ec64d4442";
      version = "4.2.2";
      classifier = "no_aop";
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-client/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-client";
      groupId = "org.eclipse.jetty";
      sha512 = "f2d70900e345694638a1b969729e4b3c9a3a19a563a53b2c74f26d7f67225dd03d57746a184f4df01fedc86aa9e62b62ca8bbe30ac4492d256ade5753ea2e772";
      version = "9.4.44.v20210927";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jetty-io/org.eclipse.jetty";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-io";
      groupId = "org.eclipse.jetty";
      sha512 = "cc89006ce0fa66d91d6a07cbf48d9dd88c1d847be6e31dba9c5acf20368b80d4c094fc153f52538b8f24e9b4f5b0b762901a4f42f307dba6c9b328694e355be4";
      version = "9.4.44.v20210927";
      
    };
    paths = [ src ];
  }

  rec {
    name = "beicon/funcool";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "beicon";
      groupId = "funcool";
      sha512 = "22965445b4dc8f4a68df4b60246cf541971f0147e4741cc3aa100cf883a3e5359fdfc7674a3f475cb3a22446cba01b57a3744f8c287e441d3ea3b22b91aa3a24";
      version = "2021.07.05-1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.reader/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.reader";
      groupId = "org.clojure";
      sha512 = "3481259c7a1eac719db2921e60173686726a0c2b65879d51a64d516a37f6120db8ffbb74b8bd273404285d7b25143ab5c7ced37e7c0eaf4ab1e44586ccd3c651";
      version = "1.3.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.gitlibs/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.gitlibs";
      groupId = "org.clojure";
      sha512 = "9f2bfe18d5eea42cb09fee0d35e323ac5844c287e9073c2644c933fd89f41d64eca4d24a40e859a9cb7154da61e96550b39d52c766064cc0f7298f8a915b8f20";
      version = "2.4.172";
      
    };
    paths = [ src ];
  }

  rec {
    name = "antq/com.github.liquidz";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "antq";
      groupId = "com.github.liquidz";
      sha512 = "aefb509a061ec192fbe84ba3c204bcea2c436b4d78d829a0fa42aa7cb57a1c6778cbf32d3c7abe6cfd6c143d873c20defc4d402cb31179e350fe3a875e420708";
      version = "1.3.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "nrepl/nrepl";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "nrepl";
      groupId = "nrepl";
      sha512 = "663906ff1c8768c4a73fa9f32619da4c244cc86c93d86e8439eb8de81c79486be5a04140c1df6199ba475b3a3e7fd36304faef8b330672dd644945820cc6eb67";
      version = "0.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-connector-basic/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-connector-basic";
      groupId = "org.apache.maven.resolver";
      sha512 = "4554cea39910393557cc8769550c3a12ba64e0f57244f71a1c78a9cd3a6032ae9bbd2b43d4c15579b6b89a766a19d28619fd99eeaa1b4862fda549d8cc9e3610";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "s3/com.cognitect.aws";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "s3";
      groupId = "com.cognitect.aws";
      sha512 = "e0ddbd294be4de0f29878d26a399034a86f244fcfa527d944f21253f13d52a1181beccf1af43cba2789237bba92c3cc76030b104c9f7e730e7b62ac559e969ca";
      version = "814.2.991.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-impl/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-impl";
      groupId = "org.apache.maven.resolver";
      sha512 = "ef011e67152290379da6db1ce256b70dc436eb1596d58c38ee5bf9df65fbe75ed2ddc7768f6c61901c8cb83af88c42ad0b7bf24ad1775949eb4522511825280d";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "slf4j-api/org.slf4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "slf4j-api";
      groupId = "org.slf4j";
      sha512 = "089a5289e127a124cc0985cfabee063fdd333ea7e7620d833a38f565da7fd2bb74f7fce1e1b37701435554579dc09a46e1292632f72d2cf5b0a098c73c41e050";
      version = "2.0.0-alpha6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-model/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-model";
      groupId = "org.apache.maven";
      sha512 = "4e7d3561e1c8c9bdf736aaf7115828ffcade3d1d0a009cc09787d93fc2505dadd71e771936f59a5f17e213b89799ed2d281a98aef56d6c6fa02720226a0b85f7";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "xnio-api/org.jboss.xnio";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "xnio-api";
      groupId = "org.jboss.xnio";
      sha512 = "eab8904c5e2f6071f076e5f68fc7520fb4e9f292df2cc03be4ac7834f52994e9f539b52be7509280f4fb49a4ded185732e8a50ffd3417e39b540d508db34ac5f";
      version = "3.8.0.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "version-clj/version-clj";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "version-clj";
      groupId = "version-clj";
      sha512 = "f5eecd356d1206bdaae6cf400c386e06de0f4601828bb3a563d66108073cece0980978cbb171c38ff3e6a2fd46b592de9e29b26c9ed555db0d3b5c43c6ba806a";
      version = "2.0.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "closure-compiler-unshaded/com.google.javascript";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "closure-compiler-unshaded";
      groupId = "com.google.javascript";
      sha512 = "7f29e37c6de61cbafad10108fa2465a0140dd124f2e956a9552a6d0bea6125a758e8865490cbd3ce470599e137ec9e069ae436b3e5d7cd43d37f8a5009f4cf78";
      version = "v20210505";
      
    };
    paths = [ src ];
  }

  rec {
    name = "test.check/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "test.check";
      groupId = "org.clojure";
      sha512 = "68caa189e7292da5dfde92d795ce35ff1980108a579dc11ca618bf0e480101b8ded16fc8ab816b30f364afbccbb8f02fc9194271e7f5323b8042d468164ecb64";
      version = "1.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "org.eclipse.sisu.inject/org.eclipse.sisu";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "org.eclipse.sisu.inject";
      groupId = "org.eclipse.sisu";
      sha512 = "f4790768c0d958b3429a3241abb15f9bb6e2fd7f43a5e034dde6a3a6820e6941c00f10ad084d5c38f8edc144e7acbea7ba3dc8952f01dab41e443803db2a4efc";
      version = "0.3.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-resolver-util/org.apache.maven.resolver";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-resolver-util";
      groupId = "org.apache.maven.resolver";
      sha512 = "45bd05eee2e2e606155916ec06efdb62e4a147af7ed0bb0b443b2a71b72576fec8e0ced0eee3ae3c86778198de227c1c7fe5d423cff0b96ba382fb563239694a";
      version = "1.6.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "log4j-api/org.apache.logging.log4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "log4j-api";
      groupId = "org.apache.logging.log4j";
      sha512 = "6391788510d015ae2d94527b942cf49a9518e8628932e0a08a1d8a46297499f9cd8a81f7dd99409f69beb06e844f9fc33b6c5c403786202cb3face9e182a5496";
      version = "2.17.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jakarta.activation/com.sun.activation";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jakarta.activation";
      groupId = "com.sun.activation";
      sha512 = "d1c214d2d6ecc61bba396d913c66c977418e74dfe96e5558951ccf99a60cfca6adfea3fc64b6e2d15f698e30dac870b8f6e8d7a22e0dff975f8dd83864714fc5";
      version = "2.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jsonista/metosin";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jsonista";
      groupId = "metosin";
      sha512 = "ce5c8d67b276920969580b2af06b2c448deb909373cdeb7b871125a6fd424faa952cb5dc8c29e73553858c74a0ecf199f77827148ef8d5f3cd0d6d10a5c5fee1";
      version = "0.3.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "uri/lambdaisland";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "uri";
      groupId = "lambdaisland";
      sha512 = "da7e5accad438283e203f62506a7ef3990bcb8fc22989683c6daf6d88ed7bffb04e16b94f0290d44807a06dbebc343366c09f25cd8b9fcb6da3900c4657a7659";
      version = "1.4.70";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.memoize/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.memoize";
      groupId = "org.clojure";
      sha512 = "67196537084b7cc34a01454d2a3b72de3fddce081b72d7a6dc1592d269a6c2728b79630bd2d52c1bf2d2f903c12add6f23df954c02ef8237f240d7394ccc3dde";
      version = "1.0.253";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-repository-metadata/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-repository-metadata";
      groupId = "org.apache.maven";
      sha512 = "0ad9b30c7d739bcfc02ce9bdfab0fa9f33497818513287900fcf5525231c76e0b0ff4f0a13246a896d85e872a2a8fbb28551dd306604cb930c7850c1837a3930";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.priority-map/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.priority-map";
      groupId = "org.clojure";
      sha512 = "bb8bc5dbfd3738c36b99a51880ac3f1381d6564e67601549ef5e7ae2b900e53cdcdfb8d0fa4bf32fb8ebc4de89d954bfa3ab7e8a1122bc34ee5073c7c707ac13";
      version = "1.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "piggieback/cider";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "piggieback";
      groupId = "cider";
      sha512 = "b3183bbc81fe3a80c6e3c1c08fa0053b33dd9374c3199291aae14511b536e5de286dcc70e4642b6902d22200fb36b77b136eb0d0e7c5e84af2fb41e19fa2ce7a";
      version = "0.5.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "shadow-undertow/thheller";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "shadow-undertow";
      groupId = "thheller";
      sha512 = "9e03307416af711405f358aa828fe7a65e04e319ebe0f207ce5bac99cede456675a438a509cc71f6e71d35d3fcd43b4f187a9643356a1055401a32d3552403c9";
      version = "0.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jakarta.mail/com.sun.mail";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jakarta.mail";
      groupId = "com.sun.mail";
      sha512 = "364b705fe3e51b1a612f7812cd4e57cff3b6ed844ca3566c206195d6512664661b0fcc138ecd2284ee33855fa378a4296842668fc66e3447d5dc5a1fc3e9c43d";
      version = "2.0.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "aopalliance/aopalliance";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "aopalliance";
      groupId = "aopalliance";
      sha512 = "3f44a932d8c00cfeee2eb057bcd7c301a2d029063e0a916e1e20b3aec4877d19d67a2fd8aaf58fa2d5a00133d1602128a7f50912ffb6cabc7b0fdc7fbda3f8a1";
      version = "1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-builder-support/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-builder-support";
      groupId = "org.apache.maven";
      sha512 = "8d52795747fbc664901422982f2281592eca8b0222dcdc27d4135fb63b2494af96928f9096eff33a4b843fc1937702aae190011c2e825598d5ecb28343fa34e7";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jsr305/com.google.code.findbugs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jsr305";
      groupId = "com.google.code.findbugs";
      sha512 = "bb09db62919a50fa5b55906013be6ca4fc7acb2e87455fac5eaf9ede2e41ce8bbafc0e5a385a561264ea4cd71bbbd3ef5a45e02d63277a201d06a0ae1636f804";
      version = "3.0.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ring-core/ring";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-core";
      groupId = "ring";
      sha512 = "38d7214a3fc1b80ab55999036638dd1971272e01bec4cb8e0ee0a4aa83f51b8c41ba8a5850b0660227f067d2f9c6d75c0c0737725ea02762bbf8d192dc72febe";
      version = "1.9.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.cache/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.cache";
      groupId = "org.clojure";
      sha512 = "0a07ceffc2fa3a536b23773eefc7ef5e1108913b93c3a5416116a6566de76dd5c218f3fb0cc19415cbaa8843838de310b76282f20bf1fc3467006c9ec373667e";
      version = "1.0.225";
      
    };
    paths = [ src ];
  }

  rec {
    name = "meta-merge/meta-merge";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "meta-merge";
      groupId = "meta-merge";
      sha512 = "079339d69a18e88a7cf5ce37e29bf7d9b25c93011866fac3012b11444f9e3d69f4dc017a3e88ad20faa790b38e343e0b71e9e11c44028434da3f368f377e4458";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-plugin-api/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-plugin-api";
      groupId = "org.apache.maven";
      sha512 = "82a12b14c96c8b041647763d8d7d6b1d43c0d726d3810b67d4bacff3663ba39d782d49edd4fb7df50fbd83b5cdd0674981ff8aebc324406fd5b00163050a2fa0";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.async/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.async";
      groupId = "org.clojure";
      sha512 = "5df59bdab9db7131f1d8c0a067a8292f287e8ba78f44171555272a9947a82349eee95f7fb935b98e91675b8498d3f7cadce6c35ba46242e55889d2c828d22cac";
      version = "1.5.644";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-datatype-jsr310/com.fasterxml.jackson.datatype";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-datatype-jsr310";
      groupId = "com.fasterxml.jackson.datatype";
      sha512 = "5e94b811785c715f6d115edec150054a154aa67b2b497569a05a764df42a0d93db2b943d6c076b0cec0c6abd142eaabe411a77a6b397bf08f694629c31914748";
      version = "2.12.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "maven-artifact/org.apache.maven";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "maven-artifact";
      groupId = "org.apache.maven";
      sha512 = "305174de2499cc68491864c27bd51c1cf91d9bba4e22722a200a60f44864855ea782cde90d5e1b923518e8ae8250245e92e1e4f5f55dc6fbb25430a2ee04c7c8";
      version = "3.8.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.codec/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.codec";
      groupId = "org.clojure";
      sha512 = "c324b62a5f14b2f17e49f1b0fffa3f44d195cb5261e03c5e472ba4f2972135f4b06fd321c0887717c727f025fc1a0121283d16fbf923d7469856702614a288f3";
      version = "0.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jaxb-api/javax.xml.bind";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jaxb-api";
      groupId = "javax.xml.bind";
      sha512 = "0c5bfc2c9f655bf5e6d596e0c196dcb9344d6dc78bf774207c8f8b6be59f69addf2b3121e81491983eff648dfbd55002b9878132de190825dad3ef3a1265b367";
      version = "2.3.0";
      
    };
    paths = [ src ];
  }

  ];
  }
  